services:
  sinaker-redis:
    image: redis:8.6
    container_name: sinaker-redis
    ports:
      - "6385:6379"
    volumes:
      - sinaker-redis-data:/data
    command: redis-server --appendonly yes
    networks:
      - capstone-global-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  sinaker-db:
    image: postgres:18-alpine
    container_name: sinaker-db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5437:5432"
    volumes:
      - sinaker-postgres-data:/var/lib/postgresql
      - ./db/migrations:/docker-entrypoint-initdb.d
    networks:
      - capstone-global-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  sinaker-api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: sinaker-api
    ports:
      - "5003:8080"
    environment:
      - PORT=8080
      - ENVIRONMENT=${ENVIRONMENT}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
      - CLOUDINARY_URL=${CLOUDINARY_URL}
      - SENDGRID_API_KEY=${SENDGRID_API_KEY}
      - SENDGRID_SENDER_EMAIL=${SENDGRID_SENDER_EMAIL}
    volumes:
      - .:/app
    depends_on:
      sinaker-db:
        condition: service_healthy
      sinaker-redis:
        condition: service_healthy
    networks:
      - capstone-global-network
    restart: unless-stopped

volumes:
  sinaker-postgres-data:
  sinaker-redis-data:
