name: capstone-project

include:
  - ./siskaperbapo-service/docker-compose.yml
  - ./sidita-service/docker-compose.yml
  - ./bapenda-service/docker-compose.yml
  - ./api-gateway/docker-compose.yaml
  - ./klinik-service/docker-compose.yml
  - ./rssa-service/docker-compose.yml
  - ./transjatim-service/docker-compose.yml
  - ./sinaker-service/docker-compose.yml
  - ./jdih-service/docker-compose.yml
  - ./bansos-service/docker-compose.yml
  - ./user-service/docker-compose.yml

networks:
  capstone-global-network:
    driver: bridge
