// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: category_list.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCategory = `-- name: CreateCategory :one
INSERT INTO category_list (name, description)
VALUES ($1, $2)
RETURNING category_list_id, name, description, created_at, is_popular
`

type CreateCategoryParams struct {
	Name        string
	Description pgtype.Text
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (CategoryList, error) {
	row := q.db.QueryRow(ctx, createCategory, arg.Name, arg.Description)
	var i CategoryList
	err := row.Scan(
		&i.CategoryListID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.IsPopular,
	)
	return i, err
}

const deleteCategory = `-- name: DeleteCategory :exec
DELETE FROM category_list
WHERE category_list_id = $1
`

func (q *Queries) DeleteCategory(ctx context.Context, categoryListID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteCategory, categoryListID)
	return err
}

const getCategoryById = `-- name: GetCategoryById :one
SELECT category_list_id, name, description, created_at, is_popular FROM category_list
WHERE category_list_id = $1 LIMIT 1
`

func (q *Queries) GetCategoryById(ctx context.Context, categoryListID pgtype.UUID) (CategoryList, error) {
	row := q.db.QueryRow(ctx, getCategoryById, categoryListID)
	var i CategoryList
	err := row.Scan(
		&i.CategoryListID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.IsPopular,
	)
	return i, err
}

const listCategories = `-- name: ListCategories :many
SELECT category_list_id, name, description, created_at, is_popular FROM category_list
ORDER BY name ASC
`

func (q *Queries) ListCategories(ctx context.Context) ([]CategoryList, error) {
	rows, err := q.db.Query(ctx, listCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CategoryList
	for rows.Next() {
		var i CategoryList
		if err := rows.Scan(
			&i.CategoryListID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.IsPopular,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCategory = `-- name: UpdateCategory :one
UPDATE category_list
SET name = $2, description = $3
WHERE category_list_id = $1
RETURNING category_list_id, name, description, created_at, is_popular
`

type UpdateCategoryParams struct {
	CategoryListID pgtype.UUID
	Name           string
	Description    pgtype.Text
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (CategoryList, error) {
	row := q.db.QueryRow(ctx, updateCategory, arg.CategoryListID, arg.Name, arg.Description)
	var i CategoryList
	err := row.Scan(
		&i.CategoryListID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.IsPopular,
	)
	return i, err
}
