// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: endpoint_list.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEndpoint = `-- name: CreateEndpoint :one
INSERT INTO endpoint_list (slug_name, page_url) 
VALUES ($1, $2) 
RETURNING endpoint_list_id, slug_name, page_url, created_at
`

type CreateEndpointParams struct {
	SlugName string
	PageUrl  string
}

func (q *Queries) CreateEndpoint(ctx context.Context, arg CreateEndpointParams) (EndpointList, error) {
	row := q.db.QueryRow(ctx, createEndpoint, arg.SlugName, arg.PageUrl)
	var i EndpointList
	err := row.Scan(
		&i.EndpointListID,
		&i.SlugName,
		&i.PageUrl,
		&i.CreatedAt,
	)
	return i, err
}

const deleteEndpoint = `-- name: DeleteEndpoint :exec
DELETE FROM endpoint_list 
WHERE endpoint_list_id = $1
`

func (q *Queries) DeleteEndpoint(ctx context.Context, endpointListID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteEndpoint, endpointListID)
	return err
}

const getEndpointById = `-- name: GetEndpointById :one
SELECT endpoint_list_id, slug_name, page_url, created_at FROM endpoint_list 
WHERE endpoint_list_id = $1 LIMIT 1
`

func (q *Queries) GetEndpointById(ctx context.Context, endpointListID pgtype.UUID) (EndpointList, error) {
	row := q.db.QueryRow(ctx, getEndpointById, endpointListID)
	var i EndpointList
	err := row.Scan(
		&i.EndpointListID,
		&i.SlugName,
		&i.PageUrl,
		&i.CreatedAt,
	)
	return i, err
}

const getEndpointBySlug = `-- name: GetEndpointBySlug :one
SELECT endpoint_list_id, slug_name, page_url, created_at FROM endpoint_list 
WHERE slug_name = $1 LIMIT 1
`

func (q *Queries) GetEndpointBySlug(ctx context.Context, slugName string) (EndpointList, error) {
	row := q.db.QueryRow(ctx, getEndpointBySlug, slugName)
	var i EndpointList
	err := row.Scan(
		&i.EndpointListID,
		&i.SlugName,
		&i.PageUrl,
		&i.CreatedAt,
	)
	return i, err
}

const listEndpoints = `-- name: ListEndpoints :many
SELECT endpoint_list_id, slug_name, page_url, created_at FROM endpoint_list 
ORDER BY created_at DESC
`

func (q *Queries) ListEndpoints(ctx context.Context) ([]EndpointList, error) {
	rows, err := q.db.Query(ctx, listEndpoints)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EndpointList
	for rows.Next() {
		var i EndpointList
		if err := rows.Scan(
			&i.EndpointListID,
			&i.SlugName,
			&i.PageUrl,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEndpoint = `-- name: UpdateEndpoint :one
UPDATE endpoint_list 
SET slug_name = $2, page_url = $3 
WHERE endpoint_list_id = $1 
RETURNING endpoint_list_id, slug_name, page_url, created_at
`

type UpdateEndpointParams struct {
	EndpointListID pgtype.UUID
	SlugName       string
	PageUrl        string
}

func (q *Queries) UpdateEndpoint(ctx context.Context, arg UpdateEndpointParams) (EndpointList, error) {
	row := q.db.QueryRow(ctx, updateEndpoint, arg.EndpointListID, arg.SlugName, arg.PageUrl)
	var i EndpointList
	err := row.Scan(
		&i.EndpointListID,
		&i.SlugName,
		&i.PageUrl,
		&i.CreatedAt,
	)
	return i, err
}
