// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: image_list.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createImage = `-- name: CreateImage :one
INSERT INTO image_list (service_list_id, image_url, semantic_label) 
VALUES ($1, $2, $3) 
RETURNING image_list_id, service_list_id, image_url, semantic_label, created_at
`

type CreateImageParams struct {
	ServiceListID pgtype.UUID
	ImageUrl      string
	SemanticLabel pgtype.Text
}

func (q *Queries) CreateImage(ctx context.Context, arg CreateImageParams) (ImageList, error) {
	row := q.db.QueryRow(ctx, createImage, arg.ServiceListID, arg.ImageUrl, arg.SemanticLabel)
	var i ImageList
	err := row.Scan(
		&i.ImageListID,
		&i.ServiceListID,
		&i.ImageUrl,
		&i.SemanticLabel,
		&i.CreatedAt,
	)
	return i, err
}

const deleteImage = `-- name: DeleteImage :exec
DELETE FROM image_list 
WHERE image_list_id = $1
`

func (q *Queries) DeleteImage(ctx context.Context, imageListID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteImage, imageListID)
	return err
}

const getImageById = `-- name: GetImageById :one
SELECT image_list_id, service_list_id, image_url, semantic_label, created_at FROM image_list 
WHERE image_list_id = $1 LIMIT 1
`

func (q *Queries) GetImageById(ctx context.Context, imageListID pgtype.UUID) (ImageList, error) {
	row := q.db.QueryRow(ctx, getImageById, imageListID)
	var i ImageList
	err := row.Scan(
		&i.ImageListID,
		&i.ServiceListID,
		&i.ImageUrl,
		&i.SemanticLabel,
		&i.CreatedAt,
	)
	return i, err
}

const listImagesByServiceId = `-- name: ListImagesByServiceId :many
SELECT image_list_id, service_list_id, image_url, semantic_label, created_at FROM image_list 
WHERE service_list_id = $1 
ORDER BY created_at DESC
`

func (q *Queries) ListImagesByServiceId(ctx context.Context, serviceListID pgtype.UUID) ([]ImageList, error) {
	rows, err := q.db.Query(ctx, listImagesByServiceId, serviceListID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ImageList
	for rows.Next() {
		var i ImageList
		if err := rows.Scan(
			&i.ImageListID,
			&i.ServiceListID,
			&i.ImageUrl,
			&i.SemanticLabel,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateImage = `-- name: UpdateImage :one
UPDATE image_list 
SET image_url = $2, semantic_label = $3 
WHERE image_list_id = $1 
RETURNING image_list_id, service_list_id, image_url, semantic_label, created_at
`

type UpdateImageParams struct {
	ImageListID   pgtype.UUID
	ImageUrl      string
	SemanticLabel pgtype.Text
}

func (q *Queries) UpdateImage(ctx context.Context, arg UpdateImageParams) (ImageList, error) {
	row := q.db.QueryRow(ctx, updateImage, arg.ImageListID, arg.ImageUrl, arg.SemanticLabel)
	var i ImageList
	err := row.Scan(
		&i.ImageListID,
		&i.ServiceListID,
		&i.ImageUrl,
		&i.SemanticLabel,
		&i.CreatedAt,
	)
	return i, err
}
