// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: integration_list.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createIntegration = `-- name: CreateIntegration :one
INSERT INTO integration_list (service_list_id, endpoint_list_id, title, icon_url)
VALUES ($1, $2, $3, $4)
RETURNING integration_list_id, service_list_id, endpoint_list_id, title, icon_url, created_at
`

type CreateIntegrationParams struct {
	ServiceListID  pgtype.UUID
	EndpointListID pgtype.UUID
	Title          string
	IconUrl        pgtype.Text
}

func (q *Queries) CreateIntegration(ctx context.Context, arg CreateIntegrationParams) (IntegrationList, error) {
	row := q.db.QueryRow(ctx, createIntegration,
		arg.ServiceListID,
		arg.EndpointListID,
		arg.Title,
		arg.IconUrl,
	)
	var i IntegrationList
	err := row.Scan(
		&i.IntegrationListID,
		&i.ServiceListID,
		&i.EndpointListID,
		&i.Title,
		&i.IconUrl,
		&i.CreatedAt,
	)
	return i, err
}

const deleteIntegration = `-- name: DeleteIntegration :exec
DELETE FROM integration_list
WHERE integration_list_id = $1
`

func (q *Queries) DeleteIntegration(ctx context.Context, integrationListID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteIntegration, integrationListID)
	return err
}

const getAllIntegrations = `-- name: GetAllIntegrations :many
SELECT integration_list_id, service_list_id, endpoint_list_id, title, icon_url, created_at FROM integration_list
ORDER BY created_at DESC
`

func (q *Queries) GetAllIntegrations(ctx context.Context) ([]IntegrationList, error) {
	rows, err := q.db.Query(ctx, getAllIntegrations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IntegrationList
	for rows.Next() {
		var i IntegrationList
		if err := rows.Scan(
			&i.IntegrationListID,
			&i.ServiceListID,
			&i.EndpointListID,
			&i.Title,
			&i.IconUrl,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getIntegrationById = `-- name: GetIntegrationById :one
SELECT integration_list_id, service_list_id, endpoint_list_id, title, icon_url, created_at FROM integration_list
WHERE integration_list_id = $1 LIMIT 1
`

func (q *Queries) GetIntegrationById(ctx context.Context, integrationListID pgtype.UUID) (IntegrationList, error) {
	row := q.db.QueryRow(ctx, getIntegrationById, integrationListID)
	var i IntegrationList
	err := row.Scan(
		&i.IntegrationListID,
		&i.ServiceListID,
		&i.EndpointListID,
		&i.Title,
		&i.IconUrl,
		&i.CreatedAt,
	)
	return i, err
}

const listIntegrationsByServiceId = `-- name: ListIntegrationsByServiceId :many
SELECT integration_list_id, service_list_id, endpoint_list_id, title, icon_url, created_at FROM integration_list
WHERE service_list_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListIntegrationsByServiceId(ctx context.Context, serviceListID pgtype.UUID) ([]IntegrationList, error) {
	rows, err := q.db.Query(ctx, listIntegrationsByServiceId, serviceListID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IntegrationList
	for rows.Next() {
		var i IntegrationList
		if err := rows.Scan(
			&i.IntegrationListID,
			&i.ServiceListID,
			&i.EndpointListID,
			&i.Title,
			&i.IconUrl,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateIntegration = `-- name: UpdateIntegration :one
UPDATE integration_list
SET endpoint_list_id = $2, title = $3, icon_url = $4
WHERE integration_list_id = $1
RETURNING integration_list_id, service_list_id, endpoint_list_id, title, icon_url, created_at
`

type UpdateIntegrationParams struct {
	IntegrationListID pgtype.UUID
	EndpointListID    pgtype.UUID
	Title             string
	IconUrl           pgtype.Text
}

func (q *Queries) UpdateIntegration(ctx context.Context, arg UpdateIntegrationParams) (IntegrationList, error) {
	row := q.db.QueryRow(ctx, updateIntegration,
		arg.IntegrationListID,
		arg.EndpointListID,
		arg.Title,
		arg.IconUrl,
	)
	var i IntegrationList
	err := row.Scan(
		&i.IntegrationListID,
		&i.ServiceListID,
		&i.EndpointListID,
		&i.Title,
		&i.IconUrl,
		&i.CreatedAt,
	)
	return i, err
}
