// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

// List of Categories available for Services
type CategoryList struct {
	CategoryListID pgtype.UUID
	Name           string
	Description    pgtype.Text
	CreatedAt      pgtype.Timestamptz
}

// Registry of Endpoint available in Backend
type EndpointList struct {
	EndpointListID pgtype.UUID
	SlugName       string
	PageUrl        string
	CreatedAt      pgtype.Timestamptz
}

// Images assets for each services
type ImageList struct {
	ImageListID   pgtype.UUID
	ServiceListID pgtype.UUID
	ImageUrl      string
	SemanticLabel pgtype.Text
	CreatedAt     pgtype.Timestamptz
}

// Per-service integration list
type IntegrationList struct {
	IntegrationListID pgtype.UUID
	ServiceListID     pgtype.UUID
	EndpointListID    pgtype.UUID
	Title             string
	IconUrl           pgtype.Text
	CreatedAt         pgtype.Timestamptz
}

// Data for operational tab
type OperationalList struct {
	OperationalListID pgtype.UUID
	ServiceListID     pgtype.UUID
	ServiceUrl        string
	Address           pgtype.Text
	OperationalHour   []byte
	SocialMedia       []byte
	CreatedAt         pgtype.Timestamptz
}

// Policies data for services
type PolicyList struct {
	PolicyListID  pgtype.UUID
	ServiceListID pgtype.UUID
	Benefit       []byte
	Instruction   []byte
	CreatedAt     pgtype.Timestamptz
}

// Services available for Majadigi
type ServiceList struct {
	ServiceListID pgtype.UUID
	Title         string
	Description   pgtype.Text
	IconUrl       string
	CreatedAt     pgtype.Timestamptz
}

type ServicesHasCategory struct {
	ServiceListID  pgtype.UUID
	CategoryListID pgtype.UUID
	CreatedAt      pgtype.Timestamptz
}
