// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: normalized_service_category.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAllNormalizedServiceCategory = `-- name: GetAllNormalizedServiceCategory :many
SELECT
    sl.service_list_id,
    sl.title,
    sl.long_title,
    sl.description,
    sl.icon_url,
    array_agg(cl.category_list_id::text) FILTER (WHERE cl.category_list_id IS NOT NULL) AS category_ids,
    sl.created_at
FROM service_list sl
LEFT JOIN services_has_categories shc ON sl.service_list_id = shc.service_list_id
LEFT JOIN category_list cl ON shc.category_list_id = cl.category_list_id
GROUP BY sl.service_list_id, sl.title, sl.long_title, sl.description, sl.icon_url, sl.created_at
ORDER BY sl.created_at DESC
`

type GetAllNormalizedServiceCategoryRow struct {
	ServiceListID pgtype.UUID
	Title         string
	LongTitle     pgtype.Text
	Description   pgtype.Text
	IconUrl       string
	CategoryIds   interface{}
	CreatedAt     pgtype.Timestamptz
}

func (q *Queries) GetAllNormalizedServiceCategory(ctx context.Context) ([]GetAllNormalizedServiceCategoryRow, error) {
	rows, err := q.db.Query(ctx, getAllNormalizedServiceCategory)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllNormalizedServiceCategoryRow
	for rows.Next() {
		var i GetAllNormalizedServiceCategoryRow
		if err := rows.Scan(
			&i.ServiceListID,
			&i.Title,
			&i.LongTitle,
			&i.Description,
			&i.IconUrl,
			&i.CategoryIds,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNormalizedServiceCategoryById = `-- name: GetNormalizedServiceCategoryById :one
SELECT
    sl.service_list_id,
    sl.title,
    sl.long_title,
    sl.description,
    sl.icon_url,
    array_agg(cl.category_list_id::text) FILTER (WHERE cl.category_list_id IS NOT NULL) AS category_ids,
    sl.created_at
FROM service_list sl
LEFT JOIN services_has_categories shc ON sl.service_list_id = shc.service_list_id
LEFT JOIN category_list cl ON shc.category_list_id = cl.category_list_id
WHERE sl.service_list_id = $1
GROUP BY sl.service_list_id, sl.title, sl.long_title, sl.description, sl.icon_url, sl.created_at
`

type GetNormalizedServiceCategoryByIdRow struct {
	ServiceListID pgtype.UUID
	Title         string
	LongTitle     pgtype.Text
	Description   pgtype.Text
	IconUrl       string
	CategoryIds   interface{}
	CreatedAt     pgtype.Timestamptz
}

func (q *Queries) GetNormalizedServiceCategoryById(ctx context.Context, serviceListID pgtype.UUID) (GetNormalizedServiceCategoryByIdRow, error) {
	row := q.db.QueryRow(ctx, getNormalizedServiceCategoryById, serviceListID)
	var i GetNormalizedServiceCategoryByIdRow
	err := row.Scan(
		&i.ServiceListID,
		&i.Title,
		&i.LongTitle,
		&i.Description,
		&i.IconUrl,
		&i.CategoryIds,
		&i.CreatedAt,
	)
	return i, err
}
