// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: operational_list.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOperational = `-- name: CreateOperational :one
INSERT INTO operational_list (service_list_id, service_url, address, operational_hour, social_media) 
VALUES ($1, $2, $3, $4, $5) 
RETURNING operational_list_id, service_list_id, service_url, address, operational_hour, social_media, created_at
`

type CreateOperationalParams struct {
	ServiceListID   pgtype.UUID
	ServiceUrl      string
	Address         pgtype.Text
	OperationalHour []byte
	SocialMedia     []byte
}

func (q *Queries) CreateOperational(ctx context.Context, arg CreateOperationalParams) (OperationalList, error) {
	row := q.db.QueryRow(ctx, createOperational,
		arg.ServiceListID,
		arg.ServiceUrl,
		arg.Address,
		arg.OperationalHour,
		arg.SocialMedia,
	)
	var i OperationalList
	err := row.Scan(
		&i.OperationalListID,
		&i.ServiceListID,
		&i.ServiceUrl,
		&i.Address,
		&i.OperationalHour,
		&i.SocialMedia,
		&i.CreatedAt,
	)
	return i, err
}

const deleteOperational = `-- name: DeleteOperational :exec
DELETE FROM operational_list 
WHERE service_list_id = $1
`

func (q *Queries) DeleteOperational(ctx context.Context, serviceListID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteOperational, serviceListID)
	return err
}

const getOperationalByServiceId = `-- name: GetOperationalByServiceId :one
SELECT operational_list_id, service_list_id, service_url, address, operational_hour, social_media, created_at FROM operational_list 
WHERE service_list_id = $1 LIMIT 1
`

func (q *Queries) GetOperationalByServiceId(ctx context.Context, serviceListID pgtype.UUID) (OperationalList, error) {
	row := q.db.QueryRow(ctx, getOperationalByServiceId, serviceListID)
	var i OperationalList
	err := row.Scan(
		&i.OperationalListID,
		&i.ServiceListID,
		&i.ServiceUrl,
		&i.Address,
		&i.OperationalHour,
		&i.SocialMedia,
		&i.CreatedAt,
	)
	return i, err
}

const updateOperational = `-- name: UpdateOperational :one
UPDATE operational_list 
SET service_url = $2, address = $3, operational_hour = $4, social_media = $5 
WHERE service_list_id = $1 
RETURNING operational_list_id, service_list_id, service_url, address, operational_hour, social_media, created_at
`

type UpdateOperationalParams struct {
	ServiceListID   pgtype.UUID
	ServiceUrl      string
	Address         pgtype.Text
	OperationalHour []byte
	SocialMedia     []byte
}

func (q *Queries) UpdateOperational(ctx context.Context, arg UpdateOperationalParams) (OperationalList, error) {
	row := q.db.QueryRow(ctx, updateOperational,
		arg.ServiceListID,
		arg.ServiceUrl,
		arg.Address,
		arg.OperationalHour,
		arg.SocialMedia,
	)
	var i OperationalList
	err := row.Scan(
		&i.OperationalListID,
		&i.ServiceListID,
		&i.ServiceUrl,
		&i.Address,
		&i.OperationalHour,
		&i.SocialMedia,
		&i.CreatedAt,
	)
	return i, err
}
