// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: policy_list.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPolicy = `-- name: CreatePolicy :one
INSERT INTO policy_list (service_list_id, benefit, instruction) 
VALUES ($1, $2, $3) 
RETURNING policy_list_id, service_list_id, benefit, instruction, created_at
`

type CreatePolicyParams struct {
	ServiceListID pgtype.UUID
	Benefit       []byte
	Instruction   []byte
}

func (q *Queries) CreatePolicy(ctx context.Context, arg CreatePolicyParams) (PolicyList, error) {
	row := q.db.QueryRow(ctx, createPolicy, arg.ServiceListID, arg.Benefit, arg.Instruction)
	var i PolicyList
	err := row.Scan(
		&i.PolicyListID,
		&i.ServiceListID,
		&i.Benefit,
		&i.Instruction,
		&i.CreatedAt,
	)
	return i, err
}

const deletePolicy = `-- name: DeletePolicy :exec
DELETE FROM policy_list 
WHERE service_list_id = $1
`

func (q *Queries) DeletePolicy(ctx context.Context, serviceListID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deletePolicy, serviceListID)
	return err
}

const getPolicyByServiceId = `-- name: GetPolicyByServiceId :one
SELECT policy_list_id, service_list_id, benefit, instruction, created_at FROM policy_list 
WHERE service_list_id = $1 LIMIT 1
`

func (q *Queries) GetPolicyByServiceId(ctx context.Context, serviceListID pgtype.UUID) (PolicyList, error) {
	row := q.db.QueryRow(ctx, getPolicyByServiceId, serviceListID)
	var i PolicyList
	err := row.Scan(
		&i.PolicyListID,
		&i.ServiceListID,
		&i.Benefit,
		&i.Instruction,
		&i.CreatedAt,
	)
	return i, err
}

const updatePolicy = `-- name: UpdatePolicy :one
UPDATE policy_list 
SET benefit = $2, instruction = $3 
WHERE service_list_id = $1 
RETURNING policy_list_id, service_list_id, benefit, instruction, created_at
`

type UpdatePolicyParams struct {
	ServiceListID pgtype.UUID
	Benefit       []byte
	Instruction   []byte
}

func (q *Queries) UpdatePolicy(ctx context.Context, arg UpdatePolicyParams) (PolicyList, error) {
	row := q.db.QueryRow(ctx, updatePolicy, arg.ServiceListID, arg.Benefit, arg.Instruction)
	var i PolicyList
	err := row.Scan(
		&i.PolicyListID,
		&i.ServiceListID,
		&i.Benefit,
		&i.Instruction,
		&i.CreatedAt,
	)
	return i, err
}
