// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: service_list.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createService = `-- name: CreateService :one
INSERT INTO service_list (title, description, icon_url) 
VALUES ($1, $2, $3) 
RETURNING service_list_id, title, description, icon_url, created_at
`

type CreateServiceParams struct {
	Title       string
	Description pgtype.Text
	IconUrl     string
}

func (q *Queries) CreateService(ctx context.Context, arg CreateServiceParams) (ServiceList, error) {
	row := q.db.QueryRow(ctx, createService, arg.Title, arg.Description, arg.IconUrl)
	var i ServiceList
	err := row.Scan(
		&i.ServiceListID,
		&i.Title,
		&i.Description,
		&i.IconUrl,
		&i.CreatedAt,
	)
	return i, err
}

const deleteService = `-- name: DeleteService :exec
DELETE FROM service_list 
WHERE service_list_id = $1
`

func (q *Queries) DeleteService(ctx context.Context, serviceListID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteService, serviceListID)
	return err
}

const getServiceById = `-- name: GetServiceById :one
SELECT service_list_id, title, description, icon_url, created_at FROM service_list 
WHERE service_list_id = $1 LIMIT 1
`

func (q *Queries) GetServiceById(ctx context.Context, serviceListID pgtype.UUID) (ServiceList, error) {
	row := q.db.QueryRow(ctx, getServiceById, serviceListID)
	var i ServiceList
	err := row.Scan(
		&i.ServiceListID,
		&i.Title,
		&i.Description,
		&i.IconUrl,
		&i.CreatedAt,
	)
	return i, err
}

const getServiceByTitle = `-- name: GetServiceByTitle :one
SELECT service_list_id, title, description, icon_url, created_at FROM service_list 
WHERE title = $1 LIMIT 1
`

func (q *Queries) GetServiceByTitle(ctx context.Context, title string) (ServiceList, error) {
	row := q.db.QueryRow(ctx, getServiceByTitle, title)
	var i ServiceList
	err := row.Scan(
		&i.ServiceListID,
		&i.Title,
		&i.Description,
		&i.IconUrl,
		&i.CreatedAt,
	)
	return i, err
}

const listServices = `-- name: ListServices :many
SELECT service_list_id, title, description, icon_url, created_at FROM service_list 
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListServicesParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListServices(ctx context.Context, arg ListServicesParams) ([]ServiceList, error) {
	rows, err := q.db.Query(ctx, listServices, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ServiceList
	for rows.Next() {
		var i ServiceList
		if err := rows.Scan(
			&i.ServiceListID,
			&i.Title,
			&i.Description,
			&i.IconUrl,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateService = `-- name: UpdateService :one
UPDATE service_list 
SET title = $2, description = $3, icon_url = $4 
WHERE service_list_id = $1 
RETURNING service_list_id, title, description, icon_url, created_at
`

type UpdateServiceParams struct {
	ServiceListID pgtype.UUID
	Title         string
	Description   pgtype.Text
	IconUrl       string
}

func (q *Queries) UpdateService(ctx context.Context, arg UpdateServiceParams) (ServiceList, error) {
	row := q.db.QueryRow(ctx, updateService,
		arg.ServiceListID,
		arg.Title,
		arg.Description,
		arg.IconUrl,
	)
	var i ServiceList
	err := row.Scan(
		&i.ServiceListID,
		&i.Title,
		&i.Description,
		&i.IconUrl,
		&i.CreatedAt,
	)
	return i, err
}
