// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: services_has_categories.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addCategoryToService = `-- name: AddCategoryToService :exec
INSERT INTO services_has_categories (service_list_id, category_list_id)
VALUES ($1, $2)
`

type AddCategoryToServiceParams struct {
	ServiceListID  pgtype.UUID
	CategoryListID pgtype.UUID
}

func (q *Queries) AddCategoryToService(ctx context.Context, arg AddCategoryToServiceParams) error {
	_, err := q.db.Exec(ctx, addCategoryToService, arg.ServiceListID, arg.CategoryListID)
	return err
}

const getAllServicesHasCategories = `-- name: GetAllServicesHasCategories :many
SELECT service_list_id, category_list_id, created_at FROM services_has_categories
ORDER BY created_at DESC
`

func (q *Queries) GetAllServicesHasCategories(ctx context.Context) ([]ServicesHasCategory, error) {
	rows, err := q.db.Query(ctx, getAllServicesHasCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ServicesHasCategory
	for rows.Next() {
		var i ServicesHasCategory
		if err := rows.Scan(&i.ServiceListID, &i.CategoryListID, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCategoriesByServiceId = `-- name: ListCategoriesByServiceId :many
SELECT c.category_list_id, c.name, c.description, c.created_at FROM category_list c
JOIN services_has_categories sc ON c.category_list_id = sc.category_list_id
WHERE sc.service_list_id = $1
`

func (q *Queries) ListCategoriesByServiceId(ctx context.Context, serviceListID pgtype.UUID) ([]CategoryList, error) {
	rows, err := q.db.Query(ctx, listCategoriesByServiceId, serviceListID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CategoryList
	for rows.Next() {
		var i CategoryList
		if err := rows.Scan(
			&i.CategoryListID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServicesByCategoryId = `-- name: ListServicesByCategoryId :many
SELECT s.service_list_id, s.title, s.description, s.icon_url, s.created_at FROM service_list s
JOIN services_has_categories sc ON s.service_list_id = sc.service_list_id
WHERE sc.category_list_id = $1
`

func (q *Queries) ListServicesByCategoryId(ctx context.Context, categoryListID pgtype.UUID) ([]ServiceList, error) {
	rows, err := q.db.Query(ctx, listServicesByCategoryId, categoryListID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ServiceList
	for rows.Next() {
		var i ServiceList
		if err := rows.Scan(
			&i.ServiceListID,
			&i.Title,
			&i.Description,
			&i.IconUrl,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeCategoryFromService = `-- name: RemoveCategoryFromService :exec
DELETE FROM services_has_categories
WHERE service_list_id = $1 AND category_list_id = $2
`

type RemoveCategoryFromServiceParams struct {
	ServiceListID  pgtype.UUID
	CategoryListID pgtype.UUID
}

func (q *Queries) RemoveCategoryFromService(ctx context.Context, arg RemoveCategoryFromServiceParams) error {
	_, err := q.db.Exec(ctx, removeCategoryFromService, arg.ServiceListID, arg.CategoryListID)
	return err
}
