// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: service_list.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countServices = `-- name: CountServices :one
SELECT COUNT(*) FROM service_list
`

func (q *Queries) CountServices(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countServices)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createService = `-- name: CreateService :one
INSERT INTO service_list (title, long_title, description, icon_url)
VALUES ($1, $2, $3, $4)
RETURNING service_list_id, title, long_title, description, icon_url, created_at
`

type CreateServiceParams struct {
	Title       string
	LongTitle   pgtype.Text
	Description pgtype.Text
	IconUrl     string
}

func (q *Queries) CreateService(ctx context.Context, arg CreateServiceParams) (ServiceList, error) {
	row := q.db.QueryRow(ctx, createService,
		arg.Title,
		arg.LongTitle,
		arg.Description,
		arg.IconUrl,
	)
	var i ServiceList
	err := row.Scan(
		&i.ServiceListID,
		&i.Title,
		&i.LongTitle,
		&i.Description,
		&i.IconUrl,
		&i.CreatedAt,
	)
	return i, err
}

const deleteService = `-- name: DeleteService :exec
DELETE FROM service_list
WHERE service_list_id = $1
`

func (q *Queries) DeleteService(ctx context.Context, serviceListID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteService, serviceListID)
	return err
}

const getAllServices = `-- name: GetAllServices :many
SELECT service_list_id, title, long_title, description, icon_url, created_at FROM service_list
ORDER BY created_at DESC
`

func (q *Queries) GetAllServices(ctx context.Context) ([]ServiceList, error) {
	rows, err := q.db.Query(ctx, getAllServices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ServiceList
	for rows.Next() {
		var i ServiceList
		if err := rows.Scan(
			&i.ServiceListID,
			&i.Title,
			&i.LongTitle,
			&i.Description,
			&i.IconUrl,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getServiceById = `-- name: GetServiceById :one
SELECT service_list_id, title, long_title, description, icon_url, created_at FROM service_list
WHERE service_list_id = $1 LIMIT 1
`

func (q *Queries) GetServiceById(ctx context.Context, serviceListID pgtype.UUID) (ServiceList, error) {
	row := q.db.QueryRow(ctx, getServiceById, serviceListID)
	var i ServiceList
	err := row.Scan(
		&i.ServiceListID,
		&i.Title,
		&i.LongTitle,
		&i.Description,
		&i.IconUrl,
		&i.CreatedAt,
	)
	return i, err
}

const listServices = `-- name: ListServices :many
SELECT service_list_id, title, long_title, description, icon_url, created_at FROM service_list
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListServicesParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListServices(ctx context.Context, arg ListServicesParams) ([]ServiceList, error) {
	rows, err := q.db.Query(ctx, listServices, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ServiceList
	for rows.Next() {
		var i ServiceList
		if err := rows.Scan(
			&i.ServiceListID,
			&i.Title,
			&i.LongTitle,
			&i.Description,
			&i.IconUrl,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchServices = `-- name: SearchServices :many
SELECT service_list_id, title, long_title, description, icon_url, created_at FROM service_list
WHERE title ILIKE $1
ORDER BY title ASC
`

func (q *Queries) SearchServices(ctx context.Context, title string) ([]ServiceList, error) {
	rows, err := q.db.Query(ctx, searchServices, title)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ServiceList
	for rows.Next() {
		var i ServiceList
		if err := rows.Scan(
			&i.ServiceListID,
			&i.Title,
			&i.LongTitle,
			&i.Description,
			&i.IconUrl,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateService = `-- name: UpdateService :one
UPDATE service_list
SET title = $2, long_title = $3, description = $4, icon_url = $5
WHERE service_list_id = $1
RETURNING service_list_id, title, long_title, description, icon_url, created_at
`

type UpdateServiceParams struct {
	ServiceListID pgtype.UUID
	Title         string
	LongTitle     pgtype.Text
	Description   pgtype.Text
	IconUrl       string
}

func (q *Queries) UpdateService(ctx context.Context, arg UpdateServiceParams) (ServiceList, error) {
	row := q.db.QueryRow(ctx, updateService,
		arg.ServiceListID,
		arg.Title,
		arg.LongTitle,
		arg.Description,
		arg.IconUrl,
	)
	var i ServiceList
	err := row.Scan(
		&i.ServiceListID,
		&i.Title,
		&i.LongTitle,
		&i.Description,
		&i.IconUrl,
		&i.CreatedAt,
	)
	return i, err
}
