// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type ReportStatus string

const (
	ReportStatusPENDING   ReportStatus = "PENDING"
	ReportStatusPROCESSED ReportStatus = "PROCESSED"
	ReportStatusREJECTED  ReportStatus = "REJECTED"
)

func (e *ReportStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ReportStatus(s)
	case string:
		*e = ReportStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ReportStatus: %T", src)
	}
	return nil
}

type NullReportStatus struct {
	ReportStatus ReportStatus `json:"report_status"`
	Valid        bool         `json:"valid"` // Valid is true if ReportStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullReportStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ReportStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ReportStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullReportStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ReportStatus), nil
}

type HoaxCategory struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	Slug      string             `json:"slug"`
	IconUrl   pgtype.Text        `json:"icon_url"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type HoaxNews struct {
	ID            pgtype.UUID        `json:"id"`
	ReportID      pgtype.UUID        `json:"report_id"`
	CategoryID    pgtype.UUID        `json:"category_id"`
	Title         string             `json:"title"`
	Slug          string             `json:"slug"`
	Description   string             `json:"description"`
	ReferenceLink pgtype.Text        `json:"reference_link"`
	ImageUrl      string             `json:"image_url"`
	PublishedAt   pgtype.Timestamptz `json:"published_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	SearchVector  interface{}        `json:"search_vector"`
}

type HoaxReport struct {
	ID            pgtype.UUID        `json:"id"`
	TicketNumber  string             `json:"ticket_number"`
	ReporterName  string             `json:"reporter_name"`
	ReporterEmail string             `json:"reporter_email"`
	ReporterPhone string             `json:"reporter_phone"`
	Content       string             `json:"content"`
	ProofLink     pgtype.Text        `json:"proof_link"`
	ProofImageUrl pgtype.Text        `json:"proof_image_url"`
	Status        ReportStatus       `json:"status"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}
