// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAllNewsAdmin = `-- name: CountAllNewsAdmin :one
SELECT COUNT(id) FROM hoax_news
`

func (q *Queries) CountAllNewsAdmin(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAllNewsAdmin)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAllReportsAdmin = `-- name: CountAllReportsAdmin :one
SELECT COUNT(id)
FROM hoax_reports
WHERE 
    $1::report_status IS NULL 
    OR status = $1::report_status
`

func (q *Queries) CountAllReportsAdmin(ctx context.Context, statusFilter NullReportStatus) (int64, error) {
	row := q.db.QueryRow(ctx, countAllReportsAdmin, statusFilter)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPublicNews = `-- name: CountPublicNews :one
SELECT COUNT(id) FROM hoax_news
`

func (q *Queries) CountPublicNews(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countPublicNews)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSearchPublicNews = `-- name: CountSearchPublicNews :one
SELECT COUNT(n.id)
FROM hoax_news n
WHERE
    n.search_vector @@ plainto_tsquery('simple', $1::text)
    OR n.title ILIKE '%' || $1::text || '%'
`

func (q *Queries) CountSearchPublicNews(ctx context.Context, keyword string) (int64, error) {
	row := q.db.QueryRow(ctx, countSearchPublicNews, keyword)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCategory = `-- name: CreateCategory :one
INSERT INTO hoax_categories (name, slug, icon_url)
VALUES ($1, $2, $3)
RETURNING id
`

type CreateCategoryParams struct {
	Name    string      `json:"name"`
	Slug    string      `json:"slug"`
	IconUrl pgtype.Text `json:"icon_url"`
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createCategory, arg.Name, arg.Slug, arg.IconUrl)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const createNewsClarification = `-- name: CreateNewsClarification :one
INSERT INTO hoax_news (
    report_id, category_id, title, slug, 
    description, reference_link, image_url
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
) RETURNING id, title, slug, published_at
`

type CreateNewsClarificationParams struct {
	ReportID      pgtype.UUID `json:"report_id"`
	CategoryID    pgtype.UUID `json:"category_id"`
	Title         string      `json:"title"`
	Slug          string      `json:"slug"`
	Description   string      `json:"description"`
	ReferenceLink pgtype.Text `json:"reference_link"`
	ImageUrl      string      `json:"image_url"`
}

type CreateNewsClarificationRow struct {
	ID          pgtype.UUID        `json:"id"`
	Title       string             `json:"title"`
	Slug        string             `json:"slug"`
	PublishedAt pgtype.Timestamptz `json:"published_at"`
}

func (q *Queries) CreateNewsClarification(ctx context.Context, arg CreateNewsClarificationParams) (CreateNewsClarificationRow, error) {
	row := q.db.QueryRow(ctx, createNewsClarification,
		arg.ReportID,
		arg.CategoryID,
		arg.Title,
		arg.Slug,
		arg.Description,
		arg.ReferenceLink,
		arg.ImageUrl,
	)
	var i CreateNewsClarificationRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.PublishedAt,
	)
	return i, err
}

const createReport = `-- name: CreateReport :one
INSERT INTO hoax_reports (
    reporter_name, reporter_email, reporter_phone,
    content, proof_link, proof_image_url
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
) RETURNING id, ticket_number, created_at
`

type CreateReportParams struct {
	ReporterName  string      `json:"reporter_name"`
	ReporterEmail string      `json:"reporter_email"`
	ReporterPhone string      `json:"reporter_phone"`
	Content       string      `json:"content"`
	ProofLink     pgtype.Text `json:"proof_link"`
	ProofImageUrl pgtype.Text `json:"proof_image_url"`
}

type CreateReportRow struct {
	ID           pgtype.UUID        `json:"id"`
	TicketNumber string             `json:"ticket_number"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateReport(ctx context.Context, arg CreateReportParams) (CreateReportRow, error) {
	row := q.db.QueryRow(ctx, createReport,
		arg.ReporterName,
		arg.ReporterEmail,
		arg.ReporterPhone,
		arg.Content,
		arg.ProofLink,
		arg.ProofImageUrl,
	)
	var i CreateReportRow
	err := row.Scan(&i.ID, &i.TicketNumber, &i.CreatedAt)
	return i, err
}

const deleteNews = `-- name: DeleteNews :exec
DELETE FROM hoax_news WHERE id = $1
`

func (q *Queries) DeleteNews(ctx context.Context, newsID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteNews, newsID)
	return err
}

const getAllCategories = `-- name: GetAllCategories :many
SELECT id, name, slug, icon_url
FROM hoax_categories
ORDER BY name ASC
`

type GetAllCategoriesRow struct {
	ID      pgtype.UUID `json:"id"`
	Name    string      `json:"name"`
	Slug    string      `json:"slug"`
	IconUrl pgtype.Text `json:"icon_url"`
}

func (q *Queries) GetAllCategories(ctx context.Context) ([]GetAllCategoriesRow, error) {
	rows, err := q.db.Query(ctx, getAllCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllCategoriesRow
	for rows.Next() {
		var i GetAllCategoriesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.IconUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllNewsAdmin = `-- name: GetAllNewsAdmin :many
SELECT
    n.id, n.title, n.slug, n.published_at, n.created_at,
    c.name           AS category_name,
    r.ticket_number
FROM hoax_news n
JOIN hoax_categories c ON n.category_id = c.id
LEFT JOIN hoax_reports r ON n.report_id = r.id
ORDER BY n.created_at DESC
LIMIT $2 OFFSET $1
`

type GetAllNewsAdminParams struct {
	OffsetData int32 `json:"offset_data"`
	LimitData  int32 `json:"limit_data"`
}

type GetAllNewsAdminRow struct {
	ID           pgtype.UUID        `json:"id"`
	Title        string             `json:"title"`
	Slug         string             `json:"slug"`
	PublishedAt  pgtype.Timestamptz `json:"published_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	CategoryName string             `json:"category_name"`
	TicketNumber pgtype.Text        `json:"ticket_number"`
}

func (q *Queries) GetAllNewsAdmin(ctx context.Context, arg GetAllNewsAdminParams) ([]GetAllNewsAdminRow, error) {
	rows, err := q.db.Query(ctx, getAllNewsAdmin, arg.OffsetData, arg.LimitData)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllNewsAdminRow
	for rows.Next() {
		var i GetAllNewsAdminRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.CategoryName,
			&i.TicketNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllReportsAdmin = `-- name: GetAllReportsAdmin :many
SELECT
    id, ticket_number, reporter_name, reporter_email,
    content, proof_link, proof_image_url, status, created_at
FROM hoax_reports
WHERE 
    $1::report_status IS NULL 
    OR status = $1::report_status
ORDER BY created_at ASC
LIMIT $3 OFFSET $2
`

type GetAllReportsAdminParams struct {
	StatusFilter NullReportStatus `json:"status_filter"`
	OffsetData   int32            `json:"offset_data"`
	LimitData    int32            `json:"limit_data"`
}

type GetAllReportsAdminRow struct {
	ID            pgtype.UUID        `json:"id"`
	TicketNumber  string             `json:"ticket_number"`
	ReporterName  string             `json:"reporter_name"`
	ReporterEmail string             `json:"reporter_email"`
	Content       string             `json:"content"`
	ProofLink     pgtype.Text        `json:"proof_link"`
	ProofImageUrl pgtype.Text        `json:"proof_image_url"`
	Status        ReportStatus       `json:"status"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetAllReportsAdmin(ctx context.Context, arg GetAllReportsAdminParams) ([]GetAllReportsAdminRow, error) {
	rows, err := q.db.Query(ctx, getAllReportsAdmin, arg.StatusFilter, arg.OffsetData, arg.LimitData)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllReportsAdminRow
	for rows.Next() {
		var i GetAllReportsAdminRow
		if err := rows.Scan(
			&i.ID,
			&i.TicketNumber,
			&i.ReporterName,
			&i.ReporterEmail,
			&i.Content,
			&i.ProofLink,
			&i.ProofImageUrl,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDashboardStats = `-- name: GetDashboardStats :many
SELECT
    c.id            AS category_id,
    c.name          AS category_name,
    c.slug          AS category_slug,
    c.icon_url,
    COUNT(n.id)     AS total_news
FROM hoax_categories c
LEFT JOIN hoax_news n ON c.id = n.category_id
GROUP BY c.id, c.name, c.slug, c.icon_url
ORDER BY c.name ASC
`

type GetDashboardStatsRow struct {
	CategoryID   pgtype.UUID `json:"category_id"`
	CategoryName string      `json:"category_name"`
	CategorySlug string      `json:"category_slug"`
	IconUrl      pgtype.Text `json:"icon_url"`
	TotalNews    int64       `json:"total_news"`
}

func (q *Queries) GetDashboardStats(ctx context.Context) ([]GetDashboardStatsRow, error) {
	rows, err := q.db.Query(ctx, getDashboardStats)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDashboardStatsRow
	for rows.Next() {
		var i GetDashboardStatsRow
		if err := rows.Scan(
			&i.CategoryID,
			&i.CategoryName,
			&i.CategorySlug,
			&i.IconUrl,
			&i.TotalNews,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNewsDetail = `-- name: GetNewsDetail :one
SELECT
    n.id, n.title, n.slug, n.description, n.reference_link, 
    n.image_url, n.published_at,
    c.name AS category_name, c.slug AS category_slug
FROM hoax_news n
JOIN hoax_categories c ON n.category_id = c.id
WHERE n.id = $1
LIMIT 1
`

type GetNewsDetailRow struct {
	ID            pgtype.UUID        `json:"id"`
	Title         string             `json:"title"`
	Slug          string             `json:"slug"`
	Description   string             `json:"description"`
	ReferenceLink pgtype.Text        `json:"reference_link"`
	ImageUrl      string             `json:"image_url"`
	PublishedAt   pgtype.Timestamptz `json:"published_at"`
	CategoryName  string             `json:"category_name"`
	CategorySlug  string             `json:"category_slug"`
}

func (q *Queries) GetNewsDetail(ctx context.Context, newsID pgtype.UUID) (GetNewsDetailRow, error) {
	row := q.db.QueryRow(ctx, getNewsDetail, newsID)
	var i GetNewsDetailRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.ReferenceLink,
		&i.ImageUrl,
		&i.PublishedAt,
		&i.CategoryName,
		&i.CategorySlug,
	)
	return i, err
}

const getNewsDetailBySlug = `-- name: GetNewsDetailBySlug :one
SELECT
    n.id, n.title, n.slug, n.description, n.reference_link, 
    n.image_url, n.published_at,
    c.name AS category_name, c.slug AS category_slug
FROM hoax_news n
JOIN hoax_categories c ON n.category_id = c.id
WHERE n.slug = $1
LIMIT 1
`

type GetNewsDetailBySlugRow struct {
	ID            pgtype.UUID        `json:"id"`
	Title         string             `json:"title"`
	Slug          string             `json:"slug"`
	Description   string             `json:"description"`
	ReferenceLink pgtype.Text        `json:"reference_link"`
	ImageUrl      string             `json:"image_url"`
	PublishedAt   pgtype.Timestamptz `json:"published_at"`
	CategoryName  string             `json:"category_name"`
	CategorySlug  string             `json:"category_slug"`
}

func (q *Queries) GetNewsDetailBySlug(ctx context.Context, slug string) (GetNewsDetailBySlugRow, error) {
	row := q.db.QueryRow(ctx, getNewsDetailBySlug, slug)
	var i GetNewsDetailBySlugRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.ReferenceLink,
		&i.ImageUrl,
		&i.PublishedAt,
		&i.CategoryName,
		&i.CategorySlug,
	)
	return i, err
}

const getPublicNews = `-- name: GetPublicNews :many
SELECT
    n.id, n.title, n.slug, n.image_url, n.published_at,
    c.name AS category_name, c.slug AS category_slug
FROM hoax_news n
JOIN hoax_categories c ON n.category_id = c.id
ORDER BY n.published_at DESC
LIMIT $2 OFFSET $1
`

type GetPublicNewsParams struct {
	OffsetData int32 `json:"offset_data"`
	LimitData  int32 `json:"limit_data"`
}

type GetPublicNewsRow struct {
	ID           pgtype.UUID        `json:"id"`
	Title        string             `json:"title"`
	Slug         string             `json:"slug"`
	ImageUrl     string             `json:"image_url"`
	PublishedAt  pgtype.Timestamptz `json:"published_at"`
	CategoryName string             `json:"category_name"`
	CategorySlug string             `json:"category_slug"`
}

func (q *Queries) GetPublicNews(ctx context.Context, arg GetPublicNewsParams) ([]GetPublicNewsRow, error) {
	rows, err := q.db.Query(ctx, getPublicNews, arg.OffsetData, arg.LimitData)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPublicNewsRow
	for rows.Next() {
		var i GetPublicNewsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.ImageUrl,
			&i.PublishedAt,
			&i.CategoryName,
			&i.CategorySlug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getReportTrackingByTicket = `-- name: GetReportTrackingByTicket :one
SELECT
    r.id              AS report_id,
    r.ticket_number,
    r.reporter_name,
    r.status          AS report_status,
    r.created_at      AS reported_at,
    n.id              AS news_id,
    n.title           AS news_title,
    n.slug            AS news_slug,
    n.image_url       AS news_image,
    c.name            AS category_name
FROM hoax_reports r
LEFT JOIN hoax_news n       ON n.report_id   = r.id
LEFT JOIN hoax_categories c ON n.category_id = c.id
WHERE r.ticket_number = $1::text
LIMIT 1
`

type GetReportTrackingByTicketRow struct {
	ReportID     pgtype.UUID        `json:"report_id"`
	TicketNumber string             `json:"ticket_number"`
	ReporterName string             `json:"reporter_name"`
	ReportStatus ReportStatus       `json:"report_status"`
	ReportedAt   pgtype.Timestamptz `json:"reported_at"`
	NewsID       pgtype.UUID        `json:"news_id"`
	NewsTitle    pgtype.Text        `json:"news_title"`
	NewsSlug     pgtype.Text        `json:"news_slug"`
	NewsImage    pgtype.Text        `json:"news_image"`
	CategoryName pgtype.Text        `json:"category_name"`
}

func (q *Queries) GetReportTrackingByTicket(ctx context.Context, ticketNumber string) (GetReportTrackingByTicketRow, error) {
	row := q.db.QueryRow(ctx, getReportTrackingByTicket, ticketNumber)
	var i GetReportTrackingByTicketRow
	err := row.Scan(
		&i.ReportID,
		&i.TicketNumber,
		&i.ReporterName,
		&i.ReportStatus,
		&i.ReportedAt,
		&i.NewsID,
		&i.NewsTitle,
		&i.NewsSlug,
		&i.NewsImage,
		&i.CategoryName,
	)
	return i, err
}

const searchPublicNews = `-- name: SearchPublicNews :many
SELECT
    n.id, n.title, n.slug, n.image_url, n.published_at,
    c.name AS category_name, c.slug AS category_slug
FROM hoax_news n
JOIN hoax_categories c ON n.category_id = c.id
WHERE
    n.search_vector @@ plainto_tsquery('simple', $1::text)
    OR n.title ILIKE '%' || $1::text || '%'
ORDER BY
    ts_rank(n.search_vector, plainto_tsquery('simple', $1::text)) DESC,
    n.published_at DESC
LIMIT $3 OFFSET $2
`

type SearchPublicNewsParams struct {
	Keyword    string `json:"keyword"`
	OffsetData int32  `json:"offset_data"`
	LimitData  int32  `json:"limit_data"`
}

type SearchPublicNewsRow struct {
	ID           pgtype.UUID        `json:"id"`
	Title        string             `json:"title"`
	Slug         string             `json:"slug"`
	ImageUrl     string             `json:"image_url"`
	PublishedAt  pgtype.Timestamptz `json:"published_at"`
	CategoryName string             `json:"category_name"`
	CategorySlug string             `json:"category_slug"`
}

func (q *Queries) SearchPublicNews(ctx context.Context, arg SearchPublicNewsParams) ([]SearchPublicNewsRow, error) {
	rows, err := q.db.Query(ctx, searchPublicNews, arg.Keyword, arg.OffsetData, arg.LimitData)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchPublicNewsRow
	for rows.Next() {
		var i SearchPublicNewsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.ImageUrl,
			&i.PublishedAt,
			&i.CategoryName,
			&i.CategorySlug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateReportStatus = `-- name: UpdateReportStatus :exec
UPDATE hoax_reports
SET status = $1
WHERE id = $2
`

type UpdateReportStatusParams struct {
	Status   ReportStatus `json:"status"`
	ReportID pgtype.UUID  `json:"report_id"`
}

func (q *Queries) UpdateReportStatus(ctx context.Context, arg UpdateReportStatusParams) error {
	_, err := q.db.Exec(ctx, updateReportStatus, arg.Status, arg.ReportID)
	return err
}
