services:
  transjatim-redis:
    image: redis:8.6
    container_name: transjatim-redis
    ports:
      - "6384:6379"
    volumes:
      - transjatim-redis-data:/data
    command: redis-server --appendonly yes
    networks:
      - capstone-global-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  transjatim-db:
    image: postgres:18-alpine
    container_name: transjatim-db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5439:5432"
    volumes:
      - transjatim-postgres-data:/var/lib/postgresql
      - ./db/migrations:/docker-entrypoint-initdb.d
    networks:
      - capstone-global-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  transjatim-api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: transjatim-api
    ports:
      - "5006:8080"
    environment:
      - PORT=8080
      - ENVIRONMENT=${ENVIRONMENT}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
      - GATEWAY_DATABASE_URL=${GATEWAY_DATABASE_URL}
      - SERVICE_PUBLIC_URL=${SERVICE_PUBLIC_URL}
    volumes:
      - .:/app
      - go-mod-cache:/root/go/pkg/mod
      - go-build-cache:/root/.cache/go-build
    depends_on:
      transjatim-db:
        condition: service_healthy
      transjatim-redis:
        condition: service_healthy
    networks:
      - capstone-global-network
    restart: unless-stopped

volumes:
  transjatim-postgres-data:
  transjatim-redis-data:
  go-mod-cache:
  go-build-cache:
