// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Destinasi struct {
	ID            int32
	AreaID        int32
	Kategori      string
	Nama          string
	Slug          string
	GambarUrl     string
	Deskripsi     string
	Alamat        string
	HighlightText string
	Lat           pgtype.Numeric
	Lng           pgtype.Numeric
	CreatedAt     pgtype.Timestamptz
}

type DestinasiGambar struct {
	ID          int32
	DestinasiID int32
	GambarUrl   string
	Urutan      pgtype.Int4
}

type Event struct {
	ID             int32
	AreaID         int32
	Nama           string
	Slug           string
	GambarUrl      string
	Deskripsi      string
	TanggalMulai   pgtype.Date
	TanggalSelesai pgtype.Date
	Tahun          pgtype.Int2
	InfoTiket      pgtype.Text
	Lat            pgtype.Numeric
	Lng            pgtype.Numeric
	CreatedAt      pgtype.Timestamptz
}

type Hotel struct {
	ID            int32
	AreaID        int32
	Nama          string
	Slug          string
	HargaMulai    pgtype.Int4
	Bintang       pgtype.Int2
	GambarUrl     string
	Deskripsi     string
	Alamat        string
	HighlightText pgtype.Text
	Lat           pgtype.Numeric
	Lng           pgtype.Numeric
	CreatedAt     pgtype.Timestamptz
}

type MasterArea struct {
	ID   int32
	Nama string
	Slug string
}
