// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Destinasi struct {
	ID                 int32              `json:"id"`
	AreaID             int32              `json:"area_id"`
	Nama               string             `json:"nama"`
	Slug               string             `json:"slug"`
	Kategori           string             `json:"kategori"`
	Deskripsi          string             `json:"deskripsi"`
	Alamat             string             `json:"alamat"`
	HighlightText      pgtype.Text        `json:"highlight_text"`
	GambarUrlThumbnail string             `json:"gambar_url_thumbnail"`
	GambarUrlHero      string             `json:"gambar_url_hero"`
	Lat                pgtype.Numeric     `json:"lat"`
	Lng                pgtype.Numeric     `json:"lng"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type Event struct {
	ID                 int32              `json:"id"`
	AreaID             int32              `json:"area_id"`
	Nama               string             `json:"nama"`
	Slug               string             `json:"slug"`
	Deskripsi          string             `json:"deskripsi"`
	Alamat             string             `json:"alamat"`
	TanggalMulai       pgtype.Date        `json:"tanggal_mulai"`
	TanggalSelesai     pgtype.Date        `json:"tanggal_selesai"`
	InfoTiket          string             `json:"info_tiket"`
	HargaTiket         int32              `json:"harga_tiket"`
	GambarUrlThumbnail string             `json:"gambar_url_thumbnail"`
	GambarUrlHero      string             `json:"gambar_url_hero"`
	Lat                pgtype.Numeric     `json:"lat"`
	Lng                pgtype.Numeric     `json:"lng"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	Tahun              pgtype.Int2        `json:"tahun"`
	Bulan              pgtype.Int2        `json:"bulan"`
}

type Hotel struct {
	ID            int32              `json:"id"`
	AreaID        int32              `json:"area_id"`
	Nama          string             `json:"nama"`
	Slug          string             `json:"slug"`
	Bintang       int16              `json:"bintang"`
	HargaMulai    int32              `json:"harga_mulai"`
	Deskripsi     pgtype.Text        `json:"deskripsi"`
	Alamat        string             `json:"alamat"`
	HighlightText pgtype.Text        `json:"highlight_text"`
	GambarUrl     string             `json:"gambar_url"`
	Lat           pgtype.Numeric     `json:"lat"`
	Lng           pgtype.Numeric     `json:"lng"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type MasterArea struct {
	ID        int32              `json:"id"`
	Nama      string             `json:"nama"`
	Slug      string             `json:"slug"`
	Lat       pgtype.Numeric     `json:"lat"`
	Lng       pgtype.Numeric     `json:"lng"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}
