// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countDestinasi = `-- name: CountDestinasi :one
SELECT COUNT(id)
FROM destinasi d
WHERE
    ($1::int IS NULL OR d.area_id = $1::int)
    AND ($2::text IS NULL OR d.nama ILIKE '%' || $2::text || '%')
`

type CountDestinasiParams struct {
	AreaID  pgtype.Int4 `json:"area_id"`
	Keyword pgtype.Text `json:"keyword"`
}

func (q *Queries) CountDestinasi(ctx context.Context, arg CountDestinasiParams) (int64, error) {
	row := q.db.QueryRow(ctx, countDestinasi, arg.AreaID, arg.Keyword)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countEvent = `-- name: CountEvent :one
SELECT COUNT(id)
FROM event e
WHERE
    ($1::int IS NULL OR e.area_id = $1::int)
    AND ($2::int IS NULL OR e.tahun = $2::int)
    AND ($3::int IS NULL OR e.bulan = $3::int)
    AND ($4::text IS NULL OR e.nama ILIKE '%' || $4::text || '%')
`

type CountEventParams struct {
	AreaID  pgtype.Int4 `json:"area_id"`
	Tahun   pgtype.Int4 `json:"tahun"`
	Bulan   pgtype.Int4 `json:"bulan"`
	Keyword pgtype.Text `json:"keyword"`
}

func (q *Queries) CountEvent(ctx context.Context, arg CountEventParams) (int64, error) {
	row := q.db.QueryRow(ctx, countEvent,
		arg.AreaID,
		arg.Tahun,
		arg.Bulan,
		arg.Keyword,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countHotel = `-- name: CountHotel :one
SELECT COUNT(id)
FROM hotel h
WHERE
    ($1::int IS NULL OR h.area_id = $1::int)
    AND ($2::text IS NULL OR h.nama ILIKE '%' || $2::text || '%')
`

type CountHotelParams struct {
	AreaID  pgtype.Int4 `json:"area_id"`
	Keyword pgtype.Text `json:"keyword"`
}

func (q *Queries) CountHotel(ctx context.Context, arg CountHotelParams) (int64, error) {
	row := q.db.QueryRow(ctx, countHotel, arg.AreaID, arg.Keyword)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDestinasi = `-- name: CreateDestinasi :one
INSERT INTO destinasi (
    area_id, nama, slug, kategori, deskripsi, alamat, highlight_text,
    gambar_url_thumbnail, gambar_url_hero, lat, lng
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7,
    $8, $9,
    $10, $11
) RETURNING id, slug
`

type CreateDestinasiParams struct {
	AreaID             int32          `json:"area_id"`
	Nama               string         `json:"nama"`
	Slug               string         `json:"slug"`
	Kategori           string         `json:"kategori"`
	Deskripsi          string         `json:"deskripsi"`
	Alamat             string         `json:"alamat"`
	HighlightText      pgtype.Text    `json:"highlight_text"`
	GambarUrlThumbnail string         `json:"gambar_url_thumbnail"`
	GambarUrlHero      string         `json:"gambar_url_hero"`
	Lat                pgtype.Numeric `json:"lat"`
	Lng                pgtype.Numeric `json:"lng"`
}

type CreateDestinasiRow struct {
	ID   int32  `json:"id"`
	Slug string `json:"slug"`
}

func (q *Queries) CreateDestinasi(ctx context.Context, arg CreateDestinasiParams) (CreateDestinasiRow, error) {
	row := q.db.QueryRow(ctx, createDestinasi,
		arg.AreaID,
		arg.Nama,
		arg.Slug,
		arg.Kategori,
		arg.Deskripsi,
		arg.Alamat,
		arg.HighlightText,
		arg.GambarUrlThumbnail,
		arg.GambarUrlHero,
		arg.Lat,
		arg.Lng,
	)
	var i CreateDestinasiRow
	err := row.Scan(&i.ID, &i.Slug)
	return i, err
}

const createEvent = `-- name: CreateEvent :one
INSERT INTO event (
    area_id, nama, slug, deskripsi, alamat,
    tanggal_mulai, tanggal_selesai, info_tiket, harga_tiket,
    gambar_url_thumbnail, gambar_url_hero, lat, lng
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7,
    $8, $9,
    $10, $11,
    $12, $13
) RETURNING id, slug
`

type CreateEventParams struct {
	AreaID             int32          `json:"area_id"`
	Nama               string         `json:"nama"`
	Slug               string         `json:"slug"`
	Deskripsi          string         `json:"deskripsi"`
	Alamat             string         `json:"alamat"`
	TanggalMulai       pgtype.Date    `json:"tanggal_mulai"`
	TanggalSelesai     pgtype.Date    `json:"tanggal_selesai"`
	InfoTiket          string         `json:"info_tiket"`
	HargaTiket         int32          `json:"harga_tiket"`
	GambarUrlThumbnail string         `json:"gambar_url_thumbnail"`
	GambarUrlHero      string         `json:"gambar_url_hero"`
	Lat                pgtype.Numeric `json:"lat"`
	Lng                pgtype.Numeric `json:"lng"`
}

type CreateEventRow struct {
	ID   int32  `json:"id"`
	Slug string `json:"slug"`
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (CreateEventRow, error) {
	row := q.db.QueryRow(ctx, createEvent,
		arg.AreaID,
		arg.Nama,
		arg.Slug,
		arg.Deskripsi,
		arg.Alamat,
		arg.TanggalMulai,
		arg.TanggalSelesai,
		arg.InfoTiket,
		arg.HargaTiket,
		arg.GambarUrlThumbnail,
		arg.GambarUrlHero,
		arg.Lat,
		arg.Lng,
	)
	var i CreateEventRow
	err := row.Scan(&i.ID, &i.Slug)
	return i, err
}

const createHotel = `-- name: CreateHotel :one
INSERT INTO hotel (
    area_id, nama, slug, bintang, harga_mulai, deskripsi, alamat,
    highlight_text, gambar_url, lat, lng
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7,
    $8, $9,
    $10, $11
) RETURNING id, slug
`

type CreateHotelParams struct {
	AreaID        int32          `json:"area_id"`
	Nama          string         `json:"nama"`
	Slug          string         `json:"slug"`
	Bintang       int16          `json:"bintang"`
	HargaMulai    int32          `json:"harga_mulai"`
	Deskripsi     pgtype.Text    `json:"deskripsi"`
	Alamat        string         `json:"alamat"`
	HighlightText pgtype.Text    `json:"highlight_text"`
	GambarUrl     string         `json:"gambar_url"`
	Lat           pgtype.Numeric `json:"lat"`
	Lng           pgtype.Numeric `json:"lng"`
}

type CreateHotelRow struct {
	ID   int32  `json:"id"`
	Slug string `json:"slug"`
}

func (q *Queries) CreateHotel(ctx context.Context, arg CreateHotelParams) (CreateHotelRow, error) {
	row := q.db.QueryRow(ctx, createHotel,
		arg.AreaID,
		arg.Nama,
		arg.Slug,
		arg.Bintang,
		arg.HargaMulai,
		arg.Deskripsi,
		arg.Alamat,
		arg.HighlightText,
		arg.GambarUrl,
		arg.Lat,
		arg.Lng,
	)
	var i CreateHotelRow
	err := row.Scan(&i.ID, &i.Slug)
	return i, err
}

const deleteDestinasi = `-- name: DeleteDestinasi :exec
DELETE FROM destinasi WHERE slug = $1
`

func (q *Queries) DeleteDestinasi(ctx context.Context, slug string) error {
	_, err := q.db.Exec(ctx, deleteDestinasi, slug)
	return err
}

const deleteEvent = `-- name: DeleteEvent :exec
DELETE FROM event WHERE slug = $1
`

func (q *Queries) DeleteEvent(ctx context.Context, slug string) error {
	_, err := q.db.Exec(ctx, deleteEvent, slug)
	return err
}

const deleteHotel = `-- name: DeleteHotel :exec
DELETE FROM hotel WHERE slug = $1
`

func (q *Queries) DeleteHotel(ctx context.Context, slug string) error {
	_, err := q.db.Exec(ctx, deleteHotel, slug)
	return err
}

const getAllArea = `-- name: GetAllArea :many
SELECT id, nama, slug, lat, lng
FROM master_area
ORDER BY nama ASC
`

type GetAllAreaRow struct {
	ID   int32          `json:"id"`
	Nama string         `json:"nama"`
	Slug string         `json:"slug"`
	Lat  pgtype.Numeric `json:"lat"`
	Lng  pgtype.Numeric `json:"lng"`
}

func (q *Queries) GetAllArea(ctx context.Context) ([]GetAllAreaRow, error) {
	rows, err := q.db.Query(ctx, getAllArea)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllAreaRow
	for rows.Next() {
		var i GetAllAreaRow
		if err := rows.Scan(
			&i.ID,
			&i.Nama,
			&i.Slug,
			&i.Lat,
			&i.Lng,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAreaByID = `-- name: GetAreaByID :one
SELECT id, nama, slug, lat, lng
FROM master_area
WHERE id = $1
LIMIT 1
`

type GetAreaByIDRow struct {
	ID   int32          `json:"id"`
	Nama string         `json:"nama"`
	Slug string         `json:"slug"`
	Lat  pgtype.Numeric `json:"lat"`
	Lng  pgtype.Numeric `json:"lng"`
}

func (q *Queries) GetAreaByID(ctx context.Context, id int32) (GetAreaByIDRow, error) {
	row := q.db.QueryRow(ctx, getAreaByID, id)
	var i GetAreaByIDRow
	err := row.Scan(
		&i.ID,
		&i.Nama,
		&i.Slug,
		&i.Lat,
		&i.Lng,
	)
	return i, err
}

const getAreaByName = `-- name: GetAreaByName :one
SELECT id, nama, slug, lat, lng
FROM master_area
WHERE nama = $1
LIMIT 1
`

type GetAreaByNameRow struct {
	ID   int32          `json:"id"`
	Nama string         `json:"nama"`
	Slug string         `json:"slug"`
	Lat  pgtype.Numeric `json:"lat"`
	Lng  pgtype.Numeric `json:"lng"`
}

func (q *Queries) GetAreaByName(ctx context.Context, nama string) (GetAreaByNameRow, error) {
	row := q.db.QueryRow(ctx, getAreaByName, nama)
	var i GetAreaByNameRow
	err := row.Scan(
		&i.ID,
		&i.Nama,
		&i.Slug,
		&i.Lat,
		&i.Lng,
	)
	return i, err
}

const getAreaBySlug = `-- name: GetAreaBySlug :one
SELECT id, nama, slug, lat, lng
FROM master_area
WHERE slug = $1
LIMIT 1
`

type GetAreaBySlugRow struct {
	ID   int32          `json:"id"`
	Nama string         `json:"nama"`
	Slug string         `json:"slug"`
	Lat  pgtype.Numeric `json:"lat"`
	Lng  pgtype.Numeric `json:"lng"`
}

func (q *Queries) GetAreaBySlug(ctx context.Context, slug string) (GetAreaBySlugRow, error) {
	row := q.db.QueryRow(ctx, getAreaBySlug, slug)
	var i GetAreaBySlugRow
	err := row.Scan(
		&i.ID,
		&i.Nama,
		&i.Slug,
		&i.Lat,
		&i.Lng,
	)
	return i, err
}

const getAvailableTahunEvent = `-- name: GetAvailableTahunEvent :many
SELECT DISTINCT tahun FROM event ORDER BY tahun DESC
`

func (q *Queries) GetAvailableTahunEvent(ctx context.Context) ([]pgtype.Int2, error) {
	rows, err := q.db.Query(ctx, getAvailableTahunEvent)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.Int2
	for rows.Next() {
		var tahun pgtype.Int2
		if err := rows.Scan(&tahun); err != nil {
			return nil, err
		}
		items = append(items, tahun)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDestinasiByIDPublic = `-- name: GetDestinasiByIDPublic :one
SELECT
    d.id, d.nama, d.slug, d.kategori, d.deskripsi, d.alamat, d.highlight_text,
    d.gambar_url_hero, d.lat, d.lng, d.created_at,
    a.id AS area_id, a.nama AS area_nama, a.slug AS area_slug
FROM destinasi d
JOIN master_area a ON d.area_id = a.id
WHERE d.id = $1
LIMIT 1
`

type GetDestinasiByIDPublicRow struct {
	ID            int32              `json:"id"`
	Nama          string             `json:"nama"`
	Slug          string             `json:"slug"`
	Kategori      string             `json:"kategori"`
	Deskripsi     string             `json:"deskripsi"`
	Alamat        string             `json:"alamat"`
	HighlightText pgtype.Text        `json:"highlight_text"`
	GambarUrlHero string             `json:"gambar_url_hero"`
	Lat           pgtype.Numeric     `json:"lat"`
	Lng           pgtype.Numeric     `json:"lng"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	AreaID        int32              `json:"area_id"`
	AreaNama      string             `json:"area_nama"`
	AreaSlug      string             `json:"area_slug"`
}

func (q *Queries) GetDestinasiByIDPublic(ctx context.Context, id int32) (GetDestinasiByIDPublicRow, error) {
	row := q.db.QueryRow(ctx, getDestinasiByIDPublic, id)
	var i GetDestinasiByIDPublicRow
	err := row.Scan(
		&i.ID,
		&i.Nama,
		&i.Slug,
		&i.Kategori,
		&i.Deskripsi,
		&i.Alamat,
		&i.HighlightText,
		&i.GambarUrlHero,
		&i.Lat,
		&i.Lng,
		&i.CreatedAt,
		&i.AreaID,
		&i.AreaNama,
		&i.AreaSlug,
	)
	return i, err
}

const getDestinasiBySlugAdmin = `-- name: GetDestinasiBySlugAdmin :one

SELECT
    d.id, d.area_id, d.nama, d.slug, d.kategori, d.deskripsi, d.alamat,
    d.highlight_text, d.gambar_url_thumbnail, d.gambar_url_hero,
    d.lat, d.lng, d.created_at, d.updated_at
FROM destinasi d
WHERE d.slug = $1
LIMIT 1
`

// =============================================================================
// ADMIN: DESTINASI
// =============================================================================
func (q *Queries) GetDestinasiBySlugAdmin(ctx context.Context, slug string) (Destinasi, error) {
	row := q.db.QueryRow(ctx, getDestinasiBySlugAdmin, slug)
	var i Destinasi
	err := row.Scan(
		&i.ID,
		&i.AreaID,
		&i.Nama,
		&i.Slug,
		&i.Kategori,
		&i.Deskripsi,
		&i.Alamat,
		&i.HighlightText,
		&i.GambarUrlThumbnail,
		&i.GambarUrlHero,
		&i.Lat,
		&i.Lng,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEventByIDPublic = `-- name: GetEventByIDPublic :one
SELECT
    e.id, e.nama, e.slug, e.deskripsi, e.alamat,
    e.tanggal_mulai, e.tanggal_selesai, e.info_tiket, e.harga_tiket,
    e.gambar_url_hero, e.lat, e.lng, e.created_at,
    a.id AS area_id, a.nama AS area_nama, a.slug AS area_slug
FROM event e
JOIN master_area a ON e.area_id = a.id
WHERE e.id = $1
LIMIT 1
`

type GetEventByIDPublicRow struct {
	ID             int32              `json:"id"`
	Nama           string             `json:"nama"`
	Slug           string             `json:"slug"`
	Deskripsi      string             `json:"deskripsi"`
	Alamat         string             `json:"alamat"`
	TanggalMulai   pgtype.Date        `json:"tanggal_mulai"`
	TanggalSelesai pgtype.Date        `json:"tanggal_selesai"`
	InfoTiket      string             `json:"info_tiket"`
	HargaTiket     int32              `json:"harga_tiket"`
	GambarUrlHero  string             `json:"gambar_url_hero"`
	Lat            pgtype.Numeric     `json:"lat"`
	Lng            pgtype.Numeric     `json:"lng"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	AreaID         int32              `json:"area_id"`
	AreaNama       string             `json:"area_nama"`
	AreaSlug       string             `json:"area_slug"`
}

func (q *Queries) GetEventByIDPublic(ctx context.Context, id int32) (GetEventByIDPublicRow, error) {
	row := q.db.QueryRow(ctx, getEventByIDPublic, id)
	var i GetEventByIDPublicRow
	err := row.Scan(
		&i.ID,
		&i.Nama,
		&i.Slug,
		&i.Deskripsi,
		&i.Alamat,
		&i.TanggalMulai,
		&i.TanggalSelesai,
		&i.InfoTiket,
		&i.HargaTiket,
		&i.GambarUrlHero,
		&i.Lat,
		&i.Lng,
		&i.CreatedAt,
		&i.AreaID,
		&i.AreaNama,
		&i.AreaSlug,
	)
	return i, err
}

const getEventBySlugAdmin = `-- name: GetEventBySlugAdmin :one

SELECT
    e.id, e.area_id, e.nama, e.slug, e.deskripsi, e.alamat,
    e.tanggal_mulai, e.tanggal_selesai, e.info_tiket, e.harga_tiket,
    e.gambar_url_thumbnail, e.gambar_url_hero,
    e.lat, e.lng, e.tahun, e.bulan, e.created_at, e.updated_at
FROM event e
WHERE e.slug = $1
LIMIT 1
`

type GetEventBySlugAdminRow struct {
	ID                 int32              `json:"id"`
	AreaID             int32              `json:"area_id"`
	Nama               string             `json:"nama"`
	Slug               string             `json:"slug"`
	Deskripsi          string             `json:"deskripsi"`
	Alamat             string             `json:"alamat"`
	TanggalMulai       pgtype.Date        `json:"tanggal_mulai"`
	TanggalSelesai     pgtype.Date        `json:"tanggal_selesai"`
	InfoTiket          string             `json:"info_tiket"`
	HargaTiket         int32              `json:"harga_tiket"`
	GambarUrlThumbnail string             `json:"gambar_url_thumbnail"`
	GambarUrlHero      string             `json:"gambar_url_hero"`
	Lat                pgtype.Numeric     `json:"lat"`
	Lng                pgtype.Numeric     `json:"lng"`
	Tahun              pgtype.Int2        `json:"tahun"`
	Bulan              pgtype.Int2        `json:"bulan"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

// =============================================================================
// ADMIN: EVENT
// =============================================================================
func (q *Queries) GetEventBySlugAdmin(ctx context.Context, slug string) (GetEventBySlugAdminRow, error) {
	row := q.db.QueryRow(ctx, getEventBySlugAdmin, slug)
	var i GetEventBySlugAdminRow
	err := row.Scan(
		&i.ID,
		&i.AreaID,
		&i.Nama,
		&i.Slug,
		&i.Deskripsi,
		&i.Alamat,
		&i.TanggalMulai,
		&i.TanggalSelesai,
		&i.InfoTiket,
		&i.HargaTiket,
		&i.GambarUrlThumbnail,
		&i.GambarUrlHero,
		&i.Lat,
		&i.Lng,
		&i.Tahun,
		&i.Bulan,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getHotelByIDPublic = `-- name: GetHotelByIDPublic :one
SELECT
    h.id, h.area_id, h.nama, h.slug, h.bintang, h.harga_mulai,
    h.deskripsi, h.alamat, h.highlight_text, h.gambar_url,
    h.lat, h.lng, h.created_at, h.updated_at
FROM hotel h
WHERE h.id = $1
LIMIT 1
`

func (q *Queries) GetHotelByIDPublic(ctx context.Context, id int32) (Hotel, error) {
	row := q.db.QueryRow(ctx, getHotelByIDPublic, id)
	var i Hotel
	err := row.Scan(
		&i.ID,
		&i.AreaID,
		&i.Nama,
		&i.Slug,
		&i.Bintang,
		&i.HargaMulai,
		&i.Deskripsi,
		&i.Alamat,
		&i.HighlightText,
		&i.GambarUrl,
		&i.Lat,
		&i.Lng,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getHotelBySlugAdmin = `-- name: GetHotelBySlugAdmin :one

SELECT
    h.id, h.area_id, h.nama, h.slug, h.bintang, h.harga_mulai,
    h.deskripsi, h.alamat, h.highlight_text, h.gambar_url,
    h.lat, h.lng, h.created_at, h.updated_at
FROM hotel h
WHERE h.slug = $1
LIMIT 1
`

// =============================================================================
// ADMIN: HOTEL
// =============================================================================
func (q *Queries) GetHotelBySlugAdmin(ctx context.Context, slug string) (Hotel, error) {
	row := q.db.QueryRow(ctx, getHotelBySlugAdmin, slug)
	var i Hotel
	err := row.Scan(
		&i.ID,
		&i.AreaID,
		&i.Nama,
		&i.Slug,
		&i.Bintang,
		&i.HargaMulai,
		&i.Deskripsi,
		&i.Alamat,
		&i.HighlightText,
		&i.GambarUrl,
		&i.Lat,
		&i.Lng,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRecommendationDestinasi = `-- name: GetRecommendationDestinasi :many
SELECT
    d.id, 
    d.nama, 
    d.gambar_url_thumbnail,
    d.alamat, 
    a.nama AS area_nama
FROM destinasi d
JOIN master_area a ON d.area_id = a.id
ORDER BY RANDOM()
LIMIT 6
`

type GetRecommendationDestinasiRow struct {
	ID                 int32  `json:"id"`
	Nama               string `json:"nama"`
	GambarUrlThumbnail string `json:"gambar_url_thumbnail"`
	Alamat             string `json:"alamat"`
	AreaNama           string `json:"area_nama"`
}

func (q *Queries) GetRecommendationDestinasi(ctx context.Context) ([]GetRecommendationDestinasiRow, error) {
	rows, err := q.db.Query(ctx, getRecommendationDestinasi)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRecommendationDestinasiRow
	for rows.Next() {
		var i GetRecommendationDestinasiRow
		if err := rows.Scan(
			&i.ID,
			&i.Nama,
			&i.GambarUrlThumbnail,
			&i.Alamat,
			&i.AreaNama,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecommendationEvent = `-- name: GetRecommendationEvent :many
SELECT
    id,
    nama,
    alamat,
    gambar_url_thumbnail,
    EXTRACT(DAY FROM tanggal_mulai)::int AS tanggal,
    EXTRACT(MONTH FROM tanggal_mulai)::int AS bulan
FROM event
ORDER BY RANDOM()
LIMIT 6
`

type GetRecommendationEventRow struct {
	ID                 int32  `json:"id"`
	Nama               string `json:"nama"`
	Alamat             string `json:"alamat"`
	GambarUrlThumbnail string `json:"gambar_url_thumbnail"`
	Tanggal            int32  `json:"tanggal"`
	Bulan              int32  `json:"bulan"`
}

func (q *Queries) GetRecommendationEvent(ctx context.Context) ([]GetRecommendationEventRow, error) {
	rows, err := q.db.Query(ctx, getRecommendationEvent)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRecommendationEventRow
	for rows.Next() {
		var i GetRecommendationEventRow
		if err := rows.Scan(
			&i.ID,
			&i.Nama,
			&i.Alamat,
			&i.GambarUrlThumbnail,
			&i.Tanggal,
			&i.Bulan,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecommendationHotel = `-- name: GetRecommendationHotel :many
SELECT
    h.id, h.nama, h.bintang, h.alamat, h.gambar_url,
    a.nama AS area_nama
FROM hotel h
JOIN master_area a ON h.area_id = a.id
ORDER BY RANDOM()
LIMIT 6
`

type GetRecommendationHotelRow struct {
	ID        int32  `json:"id"`
	Nama      string `json:"nama"`
	Bintang   int16  `json:"bintang"`
	Alamat    string `json:"alamat"`
	GambarUrl string `json:"gambar_url"`
	AreaNama  string `json:"area_nama"`
}

func (q *Queries) GetRecommendationHotel(ctx context.Context) ([]GetRecommendationHotelRow, error) {
	rows, err := q.db.Query(ctx, getRecommendationHotel)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRecommendationHotelRow
	for rows.Next() {
		var i GetRecommendationHotelRow
		if err := rows.Scan(
			&i.ID,
			&i.Nama,
			&i.Bintang,
			&i.Alamat,
			&i.GambarUrl,
			&i.AreaNama,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDestinasi = `-- name: ListDestinasi :many

SELECT
    d.id, d.nama, d.slug, d.kategori, d.alamat, d.highlight_text,
    d.gambar_url_thumbnail, d.lat, d.lng,
    a.nama AS area_nama, a.slug AS area_slug
FROM destinasi d
JOIN master_area a ON d.area_id = a.id
WHERE
    ($1::int IS NULL OR d.area_id = $1::int)
    AND ($2::text IS NULL OR d.nama ILIKE '%' || $2::text || '%')
ORDER BY d.created_at DESC
LIMIT $4 OFFSET $3
`

type ListDestinasiParams struct {
	AreaID     pgtype.Int4 `json:"area_id"`
	Keyword    pgtype.Text `json:"keyword"`
	OffsetData int32       `json:"offset_data"`
	LimitData  int32       `json:"limit_data"`
}

type ListDestinasiRow struct {
	ID                 int32          `json:"id"`
	Nama               string         `json:"nama"`
	Slug               string         `json:"slug"`
	Kategori           string         `json:"kategori"`
	Alamat             string         `json:"alamat"`
	HighlightText      pgtype.Text    `json:"highlight_text"`
	GambarUrlThumbnail string         `json:"gambar_url_thumbnail"`
	Lat                pgtype.Numeric `json:"lat"`
	Lng                pgtype.Numeric `json:"lng"`
	AreaNama           string         `json:"area_nama"`
	AreaSlug           string         `json:"area_slug"`
}

// =============================================================================
// PUBLIC / MOBILE: DESTINASI
// =============================================================================
func (q *Queries) ListDestinasi(ctx context.Context, arg ListDestinasiParams) ([]ListDestinasiRow, error) {
	rows, err := q.db.Query(ctx, listDestinasi,
		arg.AreaID,
		arg.Keyword,
		arg.OffsetData,
		arg.LimitData,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDestinasiRow
	for rows.Next() {
		var i ListDestinasiRow
		if err := rows.Scan(
			&i.ID,
			&i.Nama,
			&i.Slug,
			&i.Kategori,
			&i.Alamat,
			&i.HighlightText,
			&i.GambarUrlThumbnail,
			&i.Lat,
			&i.Lng,
			&i.AreaNama,
			&i.AreaSlug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDestinasiMaps = `-- name: ListDestinasiMaps :many
SELECT id, nama, slug, kategori, gambar_url_thumbnail, lat, lng
FROM destinasi
WHERE
    ($1::int IS NULL OR area_id = $1::int)
    AND ($2::text IS NULL OR nama ILIKE '%' || $2::text || '%')
`

type ListDestinasiMapsParams struct {
	AreaID  pgtype.Int4 `json:"area_id"`
	Keyword pgtype.Text `json:"keyword"`
}

type ListDestinasiMapsRow struct {
	ID                 int32          `json:"id"`
	Nama               string         `json:"nama"`
	Slug               string         `json:"slug"`
	Kategori           string         `json:"kategori"`
	GambarUrlThumbnail string         `json:"gambar_url_thumbnail"`
	Lat                pgtype.Numeric `json:"lat"`
	Lng                pgtype.Numeric `json:"lng"`
}

func (q *Queries) ListDestinasiMaps(ctx context.Context, arg ListDestinasiMapsParams) ([]ListDestinasiMapsRow, error) {
	rows, err := q.db.Query(ctx, listDestinasiMaps, arg.AreaID, arg.Keyword)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDestinasiMapsRow
	for rows.Next() {
		var i ListDestinasiMapsRow
		if err := rows.Scan(
			&i.ID,
			&i.Nama,
			&i.Slug,
			&i.Kategori,
			&i.GambarUrlThumbnail,
			&i.Lat,
			&i.Lng,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEvent = `-- name: ListEvent :many

SELECT
    e.id, e.nama, e.slug, e.alamat, e.tanggal_mulai, e.tanggal_selesai,
    e.harga_tiket, e.gambar_url_thumbnail, e.tahun, e.bulan,
    a.nama AS area_nama, a.slug AS area_slug
FROM event e
JOIN master_area a ON e.area_id = a.id
WHERE
    ($1::int IS NULL OR e.area_id = $1::int)
    AND ($2::int IS NULL OR e.tahun = $2::int)
    AND ($3::int IS NULL OR e.bulan = $3::int)
    AND ($4::text IS NULL OR e.nama ILIKE '%' || $4::text || '%')
ORDER BY e.tanggal_mulai DESC
LIMIT $6 OFFSET $5
`

type ListEventParams struct {
	AreaID     pgtype.Int4 `json:"area_id"`
	Tahun      pgtype.Int4 `json:"tahun"`
	Bulan      pgtype.Int4 `json:"bulan"`
	Keyword    pgtype.Text `json:"keyword"`
	OffsetData int32       `json:"offset_data"`
	LimitData  int32       `json:"limit_data"`
}

type ListEventRow struct {
	ID                 int32       `json:"id"`
	Nama               string      `json:"nama"`
	Slug               string      `json:"slug"`
	Alamat             string      `json:"alamat"`
	TanggalMulai       pgtype.Date `json:"tanggal_mulai"`
	TanggalSelesai     pgtype.Date `json:"tanggal_selesai"`
	HargaTiket         int32       `json:"harga_tiket"`
	GambarUrlThumbnail string      `json:"gambar_url_thumbnail"`
	Tahun              pgtype.Int2 `json:"tahun"`
	Bulan              pgtype.Int2 `json:"bulan"`
	AreaNama           string      `json:"area_nama"`
	AreaSlug           string      `json:"area_slug"`
}

// =============================================================================
// PUBLIC / MOBILE: EVENT
// =============================================================================
func (q *Queries) ListEvent(ctx context.Context, arg ListEventParams) ([]ListEventRow, error) {
	rows, err := q.db.Query(ctx, listEvent,
		arg.AreaID,
		arg.Tahun,
		arg.Bulan,
		arg.Keyword,
		arg.OffsetData,
		arg.LimitData,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEventRow
	for rows.Next() {
		var i ListEventRow
		if err := rows.Scan(
			&i.ID,
			&i.Nama,
			&i.Slug,
			&i.Alamat,
			&i.TanggalMulai,
			&i.TanggalSelesai,
			&i.HargaTiket,
			&i.GambarUrlThumbnail,
			&i.Tahun,
			&i.Bulan,
			&i.AreaNama,
			&i.AreaSlug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventMaps = `-- name: ListEventMaps :many
SELECT id, nama, slug, gambar_url_thumbnail, lat, lng
FROM event
WHERE
    ($1::int IS NULL OR area_id = $1::int)
    AND ($2::int IS NULL OR EXTRACT(YEAR FROM tanggal_mulai) = $2::int)
    AND ($3::text IS NULL OR nama ILIKE '%' || $3::text || '%')
`

type ListEventMapsParams struct {
	AreaID  pgtype.Int4 `json:"area_id"`
	Tahun   pgtype.Int4 `json:"tahun"`
	Keyword pgtype.Text `json:"keyword"`
}

type ListEventMapsRow struct {
	ID                 int32          `json:"id"`
	Nama               string         `json:"nama"`
	Slug               string         `json:"slug"`
	GambarUrlThumbnail string         `json:"gambar_url_thumbnail"`
	Lat                pgtype.Numeric `json:"lat"`
	Lng                pgtype.Numeric `json:"lng"`
}

func (q *Queries) ListEventMaps(ctx context.Context, arg ListEventMapsParams) ([]ListEventMapsRow, error) {
	rows, err := q.db.Query(ctx, listEventMaps, arg.AreaID, arg.Tahun, arg.Keyword)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEventMapsRow
	for rows.Next() {
		var i ListEventMapsRow
		if err := rows.Scan(
			&i.ID,
			&i.Nama,
			&i.Slug,
			&i.GambarUrlThumbnail,
			&i.Lat,
			&i.Lng,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHotel = `-- name: ListHotel :many

SELECT
    h.id, h.nama, h.slug, h.bintang, h.harga_mulai, h.alamat, h.highlight_text,
    h.gambar_url, h.lat, h.lng,
    a.nama AS area_nama, a.slug AS area_slug
FROM hotel h
JOIN master_area a ON h.area_id = a.id
WHERE
    ($1::int IS NULL OR h.area_id = $1::int)
    AND ($2::text IS NULL OR h.nama ILIKE '%' || $2::text || '%')
ORDER BY h.bintang DESC, h.created_at DESC
LIMIT $4 OFFSET $3
`

type ListHotelParams struct {
	AreaID     pgtype.Int4 `json:"area_id"`
	Keyword    pgtype.Text `json:"keyword"`
	OffsetData int32       `json:"offset_data"`
	LimitData  int32       `json:"limit_data"`
}

type ListHotelRow struct {
	ID            int32          `json:"id"`
	Nama          string         `json:"nama"`
	Slug          string         `json:"slug"`
	Bintang       int16          `json:"bintang"`
	HargaMulai    int32          `json:"harga_mulai"`
	Alamat        string         `json:"alamat"`
	HighlightText pgtype.Text    `json:"highlight_text"`
	GambarUrl     string         `json:"gambar_url"`
	Lat           pgtype.Numeric `json:"lat"`
	Lng           pgtype.Numeric `json:"lng"`
	AreaNama      string         `json:"area_nama"`
	AreaSlug      string         `json:"area_slug"`
}

// =============================================================================
// PUBLIC: HOTEL
// =============================================================================
func (q *Queries) ListHotel(ctx context.Context, arg ListHotelParams) ([]ListHotelRow, error) {
	rows, err := q.db.Query(ctx, listHotel,
		arg.AreaID,
		arg.Keyword,
		arg.OffsetData,
		arg.LimitData,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListHotelRow
	for rows.Next() {
		var i ListHotelRow
		if err := rows.Scan(
			&i.ID,
			&i.Nama,
			&i.Slug,
			&i.Bintang,
			&i.HargaMulai,
			&i.Alamat,
			&i.HighlightText,
			&i.GambarUrl,
			&i.Lat,
			&i.Lng,
			&i.AreaNama,
			&i.AreaSlug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHotelMaps = `-- name: ListHotelMaps :many
SELECT id, nama, slug, bintang, gambar_url, lat, lng
FROM hotel
WHERE
    ($1::int IS NULL OR area_id = $1::int)
    AND ($2::text IS NULL OR nama ILIKE '%' || $2::text || '%')
`

type ListHotelMapsParams struct {
	AreaID  pgtype.Int4 `json:"area_id"`
	Keyword pgtype.Text `json:"keyword"`
}

type ListHotelMapsRow struct {
	ID        int32          `json:"id"`
	Nama      string         `json:"nama"`
	Slug      string         `json:"slug"`
	Bintang   int16          `json:"bintang"`
	GambarUrl string         `json:"gambar_url"`
	Lat       pgtype.Numeric `json:"lat"`
	Lng       pgtype.Numeric `json:"lng"`
}

func (q *Queries) ListHotelMaps(ctx context.Context, arg ListHotelMapsParams) ([]ListHotelMapsRow, error) {
	rows, err := q.db.Query(ctx, listHotelMaps, arg.AreaID, arg.Keyword)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListHotelMapsRow
	for rows.Next() {
		var i ListHotelMapsRow
		if err := rows.Scan(
			&i.ID,
			&i.Nama,
			&i.Slug,
			&i.Bintang,
			&i.GambarUrl,
			&i.Lat,
			&i.Lng,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDestinasi = `-- name: UpdateDestinasi :exec
UPDATE destinasi SET
    area_id              = $1,
    nama                 = $2,
    slug                 = $3,
    kategori             = $4,
    deskripsi            = $5,
    alamat               = $6,
    highlight_text       = $7,
    gambar_url_thumbnail = $8,
    gambar_url_hero      = $9,
    lat                  = $10,
    lng                  = $11
WHERE slug = $12
`

type UpdateDestinasiParams struct {
	AreaID             int32          `json:"area_id"`
	Nama               string         `json:"nama"`
	SlugBaru           string         `json:"slug_baru"`
	Kategori           string         `json:"kategori"`
	Deskripsi          string         `json:"deskripsi"`
	Alamat             string         `json:"alamat"`
	HighlightText      pgtype.Text    `json:"highlight_text"`
	GambarUrlThumbnail string         `json:"gambar_url_thumbnail"`
	GambarUrlHero      string         `json:"gambar_url_hero"`
	Lat                pgtype.Numeric `json:"lat"`
	Lng                pgtype.Numeric `json:"lng"`
	SlugLama           string         `json:"slug_lama"`
}

func (q *Queries) UpdateDestinasi(ctx context.Context, arg UpdateDestinasiParams) error {
	_, err := q.db.Exec(ctx, updateDestinasi,
		arg.AreaID,
		arg.Nama,
		arg.SlugBaru,
		arg.Kategori,
		arg.Deskripsi,
		arg.Alamat,
		arg.HighlightText,
		arg.GambarUrlThumbnail,
		arg.GambarUrlHero,
		arg.Lat,
		arg.Lng,
		arg.SlugLama,
	)
	return err
}

const updateEvent = `-- name: UpdateEvent :exec
UPDATE event SET
    area_id              = $1,
    nama                 = $2,
    slug                 = $3, 
    deskripsi            = $4,
    alamat               = $5,
    tanggal_mulai        = $6,
    tanggal_selesai      = $7,
    info_tiket           = $8,
    harga_tiket          = $9,
    gambar_url_thumbnail = $10,
    gambar_url_hero      = $11,
    lat                  = $12,
    lng                  = $13
WHERE slug = $14
`

type UpdateEventParams struct {
	AreaID             int32          `json:"area_id"`
	Nama               string         `json:"nama"`
	SlugBaru           string         `json:"slug_baru"`
	Deskripsi          string         `json:"deskripsi"`
	Alamat             string         `json:"alamat"`
	TanggalMulai       pgtype.Date    `json:"tanggal_mulai"`
	TanggalSelesai     pgtype.Date    `json:"tanggal_selesai"`
	InfoTiket          string         `json:"info_tiket"`
	HargaTiket         int32          `json:"harga_tiket"`
	GambarUrlThumbnail string         `json:"gambar_url_thumbnail"`
	GambarUrlHero      string         `json:"gambar_url_hero"`
	Lat                pgtype.Numeric `json:"lat"`
	Lng                pgtype.Numeric `json:"lng"`
	SlugLama           string         `json:"slug_lama"`
}

func (q *Queries) UpdateEvent(ctx context.Context, arg UpdateEventParams) error {
	_, err := q.db.Exec(ctx, updateEvent,
		arg.AreaID,
		arg.Nama,
		arg.SlugBaru,
		arg.Deskripsi,
		arg.Alamat,
		arg.TanggalMulai,
		arg.TanggalSelesai,
		arg.InfoTiket,
		arg.HargaTiket,
		arg.GambarUrlThumbnail,
		arg.GambarUrlHero,
		arg.Lat,
		arg.Lng,
		arg.SlugLama,
	)
	return err
}

const updateHotel = `-- name: UpdateHotel :exec
UPDATE hotel SET
    area_id        = $1,
    nama           = $2,
    slug           = $3, 
    bintang        = $4,
    harga_mulai    = $5,
    deskripsi      = $6,
    alamat         = $7,
    highlight_text = $8,
    gambar_url     = $9,
    lat            = $10,
    lng            = $11
WHERE slug = $12
`

type UpdateHotelParams struct {
	AreaID        int32          `json:"area_id"`
	Nama          string         `json:"nama"`
	SlugBaru      string         `json:"slug_baru"`
	Bintang       int16          `json:"bintang"`
	HargaMulai    int32          `json:"harga_mulai"`
	Deskripsi     pgtype.Text    `json:"deskripsi"`
	Alamat        string         `json:"alamat"`
	HighlightText pgtype.Text    `json:"highlight_text"`
	GambarUrl     string         `json:"gambar_url"`
	Lat           pgtype.Numeric `json:"lat"`
	Lng           pgtype.Numeric `json:"lng"`
	SlugLama      string         `json:"slug_lama"`
}

func (q *Queries) UpdateHotel(ctx context.Context, arg UpdateHotelParams) error {
	_, err := q.db.Exec(ctx, updateHotel,
		arg.AreaID,
		arg.Nama,
		arg.SlugBaru,
		arg.Bintang,
		arg.HargaMulai,
		arg.Deskripsi,
		arg.Alamat,
		arg.HighlightText,
		arg.GambarUrl,
		arg.Lat,
		arg.Lng,
		arg.SlugLama,
	)
	return err
}

const checkDestinasiNamaExists = `-- name: CheckDestinasiNamaExists :one
SELECT EXISTS(SELECT 1 FROM destinasi WHERE LOWER(nama) = LOWER($1)) AS "exists"`

func (q *Queries) CheckDestinasiNamaExists(ctx context.Context, nama string) (bool, error) {
	row := q.db.QueryRow(ctx, checkDestinasiNamaExists, nama)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

type CheckDestinasiNamaExistsExcludingParams struct {
	Nama    string `json:"nama"`
	OldSlug string `json:"old_slug"`
}

const checkDestinasiNamaExistsExcluding = `-- name: CheckDestinasiNamaExistsExcluding :one
SELECT EXISTS(SELECT 1 FROM destinasi WHERE LOWER(nama) = LOWER($1) AND slug != $2) AS "exists"`

func (q *Queries) CheckDestinasiNamaExistsExcluding(ctx context.Context, arg CheckDestinasiNamaExistsExcludingParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkDestinasiNamaExistsExcluding, arg.Nama, arg.OldSlug)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const checkHotelNamaExists = `-- name: CheckHotelNamaExists :one
SELECT EXISTS(SELECT 1 FROM hotel WHERE LOWER(nama) = LOWER($1)) AS "exists"`

func (q *Queries) CheckHotelNamaExists(ctx context.Context, nama string) (bool, error) {
	row := q.db.QueryRow(ctx, checkHotelNamaExists, nama)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

type CheckHotelNamaExistsExcludingParams struct {
	Nama    string `json:"nama"`
	OldSlug string `json:"old_slug"`
}

const checkHotelNamaExistsExcluding = `-- name: CheckHotelNamaExistsExcluding :one
SELECT EXISTS(SELECT 1 FROM hotel WHERE LOWER(nama) = LOWER($1) AND slug != $2) AS "exists"`

func (q *Queries) CheckHotelNamaExistsExcluding(ctx context.Context, arg CheckHotelNamaExistsExcludingParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkHotelNamaExistsExcluding, arg.Nama, arg.OldSlug)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const checkEventNamaExists = `-- name: CheckEventNamaExists :one
SELECT EXISTS(SELECT 1 FROM event WHERE LOWER(nama) = LOWER($1)) AS "exists"`

func (q *Queries) CheckEventNamaExists(ctx context.Context, nama string) (bool, error) {
	row := q.db.QueryRow(ctx, checkEventNamaExists, nama)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

type CheckEventNamaExistsExcludingParams struct {
	Nama    string `json:"nama"`
	OldSlug string `json:"old_slug"`
}

const checkEventNamaExistsExcluding = `-- name: CheckEventNamaExistsExcluding :one
SELECT EXISTS(SELECT 1 FROM event WHERE LOWER(nama) = LOWER($1) AND slug != $2) AS "exists"`

func (q *Queries) CheckEventNamaExistsExcluding(ctx context.Context, arg CheckEventNamaExistsExcludingParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkEventNamaExistsExcluding, arg.Nama, arg.OldSlug)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
