// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countDestinasi = `-- name: CountDestinasi :one
SELECT COUNT(*) 
FROM destinasi d
WHERE 
    ($1::text IS NULL OR 
     d.nama ILIKE '%' || $1::text || '%' OR 
     d.alamat ILIKE '%' || $1::text || '%') 
    AND ($2::text IS NULL OR d.kategori = $2::text)
    AND ($3::int IS NULL OR d.area_id = $3::int)
`

type CountDestinasiParams struct {
	Search   pgtype.Text `json:"search"`
	Kategori pgtype.Text `json:"kategori"`
	AreaID   pgtype.Int4 `json:"area_id"`
}

func (q *Queries) CountDestinasi(ctx context.Context, arg CountDestinasiParams) (int64, error) {
	row := q.db.QueryRow(ctx, countDestinasi, arg.Search, arg.Kategori, arg.AreaID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countEvent = `-- name: CountEvent :one
SELECT COUNT(*) 
FROM event e
WHERE 
    ($1::text IS NULL OR e.nama ILIKE '%' || $1::text || '%')
    AND ($2::int IS NULL OR e.area_id = $2::int)
    AND ($3::smallint IS NULL OR e.tahun = $3::smallint)
`

type CountEventParams struct {
	Search pgtype.Text `json:"search"`
	AreaID pgtype.Int4 `json:"area_id"`
	Tahun  pgtype.Int2 `json:"tahun"`
}

func (q *Queries) CountEvent(ctx context.Context, arg CountEventParams) (int64, error) {
	row := q.db.QueryRow(ctx, countEvent, arg.Search, arg.AreaID, arg.Tahun)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countHotel = `-- name: CountHotel :one
SELECT COUNT(*) 
FROM hotel h
WHERE 
    ($1::text IS NULL OR h.nama ILIKE '%' || $1::text || '%')
    AND ($2::int IS NULL OR h.area_id = $2::int)
    AND ($3::smallint IS NULL OR h.bintang >= $3::smallint)
`

type CountHotelParams struct {
	Search     pgtype.Text `json:"search"`
	AreaID     pgtype.Int4 `json:"area_id"`
	MinBintang pgtype.Int2 `json:"min_bintang"`
}

func (q *Queries) CountHotel(ctx context.Context, arg CountHotelParams) (int64, error) {
	row := q.db.QueryRow(ctx, countHotel, arg.Search, arg.AreaID, arg.MinBintang)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDestinasi = `-- name: CreateDestinasi :one
INSERT INTO destinasi (
    area_id, kategori, nama, slug, gambar_url, deskripsi, alamat, highlight_text, lat, lng
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
) RETURNING id, created_at
`

type CreateDestinasiParams struct {
	AreaID        int32          `json:"area_id"`
	Kategori      string         `json:"kategori"`
	Nama          string         `json:"nama"`
	Slug          string         `json:"slug"`
	GambarUrl     string         `json:"gambar_url"`
	Deskripsi     string         `json:"deskripsi"`
	Alamat        string         `json:"alamat"`
	HighlightText string         `json:"highlight_text"`
	Lat           pgtype.Numeric `json:"lat"`
	Lng           pgtype.Numeric `json:"lng"`
}

type CreateDestinasiRow struct {
	ID        int32              `json:"id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateDestinasi(ctx context.Context, arg CreateDestinasiParams) (CreateDestinasiRow, error) {
	row := q.db.QueryRow(ctx, createDestinasi,
		arg.AreaID,
		arg.Kategori,
		arg.Nama,
		arg.Slug,
		arg.GambarUrl,
		arg.Deskripsi,
		arg.Alamat,
		arg.HighlightText,
		arg.Lat,
		arg.Lng,
	)
	var i CreateDestinasiRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const createDestinasiGambar = `-- name: CreateDestinasiGambar :one
INSERT INTO destinasi_gambar (destinasi_id, gambar_url, urutan)
VALUES ($1, $2, $3)
RETURNING id
`

type CreateDestinasiGambarParams struct {
	DestinasiID int32       `json:"destinasi_id"`
	GambarUrl   string      `json:"gambar_url"`
	Urutan      pgtype.Int4 `json:"urutan"`
}

func (q *Queries) CreateDestinasiGambar(ctx context.Context, arg CreateDestinasiGambarParams) (int32, error) {
	row := q.db.QueryRow(ctx, createDestinasiGambar, arg.DestinasiID, arg.GambarUrl, arg.Urutan)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const createEvent = `-- name: CreateEvent :one
INSERT INTO event (
    area_id, nama, slug, gambar_url, deskripsi, tanggal_mulai, tanggal_selesai, info_tiket, lat, lng
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
) RETURNING id, created_at
`

type CreateEventParams struct {
	AreaID         int32          `json:"area_id"`
	Nama           string         `json:"nama"`
	Slug           string         `json:"slug"`
	GambarUrl      string         `json:"gambar_url"`
	Deskripsi      string         `json:"deskripsi"`
	TanggalMulai   pgtype.Date    `json:"tanggal_mulai"`
	TanggalSelesai pgtype.Date    `json:"tanggal_selesai"`
	InfoTiket      pgtype.Text    `json:"info_tiket"`
	Lat            pgtype.Numeric `json:"lat"`
	Lng            pgtype.Numeric `json:"lng"`
}

type CreateEventRow struct {
	ID        int32              `json:"id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (CreateEventRow, error) {
	row := q.db.QueryRow(ctx, createEvent,
		arg.AreaID,
		arg.Nama,
		arg.Slug,
		arg.GambarUrl,
		arg.Deskripsi,
		arg.TanggalMulai,
		arg.TanggalSelesai,
		arg.InfoTiket,
		arg.Lat,
		arg.Lng,
	)
	var i CreateEventRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const createHotel = `-- name: CreateHotel :one
INSERT INTO hotel (
    area_id, nama, slug, harga_mulai, bintang, gambar_url, deskripsi, alamat, highlight_text, lat, lng
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
) RETURNING id, created_at
`

type CreateHotelParams struct {
	AreaID        int32          `json:"area_id"`
	Nama          string         `json:"nama"`
	Slug          string         `json:"slug"`
	HargaMulai    pgtype.Int4    `json:"harga_mulai"`
	Bintang       pgtype.Int2    `json:"bintang"`
	GambarUrl     string         `json:"gambar_url"`
	Deskripsi     string         `json:"deskripsi"`
	Alamat        string         `json:"alamat"`
	HighlightText pgtype.Text    `json:"highlight_text"`
	Lat           pgtype.Numeric `json:"lat"`
	Lng           pgtype.Numeric `json:"lng"`
}

type CreateHotelRow struct {
	ID        int32              `json:"id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateHotel(ctx context.Context, arg CreateHotelParams) (CreateHotelRow, error) {
	row := q.db.QueryRow(ctx, createHotel,
		arg.AreaID,
		arg.Nama,
		arg.Slug,
		arg.HargaMulai,
		arg.Bintang,
		arg.GambarUrl,
		arg.Deskripsi,
		arg.Alamat,
		arg.HighlightText,
		arg.Lat,
		arg.Lng,
	)
	var i CreateHotelRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const deleteDestinasi = `-- name: DeleteDestinasi :exec
DELETE FROM destinasi WHERE id = $1
`

func (q *Queries) DeleteDestinasi(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteDestinasi, id)
	return err
}

const getAllArea = `-- name: GetAllArea :many
SELECT id, nama, slug, lat, lng 
FROM master_area 
ORDER BY nama ASC
`

func (q *Queries) GetAllArea(ctx context.Context) ([]MasterArea, error) {
	rows, err := q.db.Query(ctx, getAllArea)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MasterArea
	for rows.Next() {
		var i MasterArea
		if err := rows.Scan(
			&i.ID,
			&i.Nama,
			&i.Slug,
			&i.Lat,
			&i.Lng,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAreaByID = `-- name: GetAreaByID :one
SELECT id, nama, slug, lat, lng FROM master_area WHERE id = $1 LIMIT 1
`

func (q *Queries) GetAreaByID(ctx context.Context, id int32) (MasterArea, error) {
	row := q.db.QueryRow(ctx, getAreaByID, id)
	var i MasterArea
	err := row.Scan(
		&i.ID,
		&i.Nama,
		&i.Slug,
		&i.Lat,
		&i.Lng,
	)
	return i, err
}

const getAreaByName = `-- name: GetAreaByName :one
SELECT id, nama, slug, lat, lng 
FROM master_area 
WHERE nama ILIKE $1 LIMIT 1
`

func (q *Queries) GetAreaByName(ctx context.Context, nama string) (MasterArea, error) {
	row := q.db.QueryRow(ctx, getAreaByName, nama)
	var i MasterArea
	err := row.Scan(
		&i.ID,
		&i.Nama,
		&i.Slug,
		&i.Lat,
		&i.Lng,
	)
	return i, err
}

const getAreaBySlug = `-- name: GetAreaBySlug :one
SELECT id, nama, slug, lat, lng 
FROM master_area 
WHERE slug = $1 LIMIT 1
`

func (q *Queries) GetAreaBySlug(ctx context.Context, slug string) (MasterArea, error) {
	row := q.db.QueryRow(ctx, getAreaBySlug, slug)
	var i MasterArea
	err := row.Scan(
		&i.ID,
		&i.Nama,
		&i.Slug,
		&i.Lat,
		&i.Lng,
	)
	return i, err
}

const getDestinasiByID = `-- name: GetDestinasiByID :one
SELECT id, area_id, kategori, nama, slug, gambar_url, deskripsi, alamat, highlight_text, lat, lng, created_at FROM destinasi WHERE id = $1 LIMIT 1
`

func (q *Queries) GetDestinasiByID(ctx context.Context, id int32) (Destinasi, error) {
	row := q.db.QueryRow(ctx, getDestinasiByID, id)
	var i Destinasi
	err := row.Scan(
		&i.ID,
		&i.AreaID,
		&i.Kategori,
		&i.Nama,
		&i.Slug,
		&i.GambarUrl,
		&i.Deskripsi,
		&i.Alamat,
		&i.HighlightText,
		&i.Lat,
		&i.Lng,
		&i.CreatedAt,
	)
	return i, err
}

const getDestinasiBySlug = `-- name: GetDestinasiBySlug :one
SELECT 
    d.id, d.kategori, d.nama, d.slug, d.gambar_url, d.deskripsi, 
    d.alamat, d.highlight_text, d.lat, d.lng, a.nama AS kota
FROM destinasi d
JOIN master_area a ON d.area_id = a.id
WHERE d.slug = $1 LIMIT 1
`

type GetDestinasiBySlugRow struct {
	ID            int32          `json:"id"`
	Kategori      string         `json:"kategori"`
	Nama          string         `json:"nama"`
	Slug          string         `json:"slug"`
	GambarUrl     string         `json:"gambar_url"`
	Deskripsi     string         `json:"deskripsi"`
	Alamat        string         `json:"alamat"`
	HighlightText string         `json:"highlight_text"`
	Lat           pgtype.Numeric `json:"lat"`
	Lng           pgtype.Numeric `json:"lng"`
	Kota          string         `json:"kota"`
}

func (q *Queries) GetDestinasiBySlug(ctx context.Context, slug string) (GetDestinasiBySlugRow, error) {
	row := q.db.QueryRow(ctx, getDestinasiBySlug, slug)
	var i GetDestinasiBySlugRow
	err := row.Scan(
		&i.ID,
		&i.Kategori,
		&i.Nama,
		&i.Slug,
		&i.GambarUrl,
		&i.Deskripsi,
		&i.Alamat,
		&i.HighlightText,
		&i.Lat,
		&i.Lng,
		&i.Kota,
	)
	return i, err
}

const getEventBySlug = `-- name: GetEventBySlug :one
SELECT 
    e.id, e.nama, e.slug, e.gambar_url, e.deskripsi, e.tanggal_mulai, 
    e.tanggal_selesai, e.tahun, e.info_tiket, e.lat, e.lng, a.nama AS kota
FROM event e
JOIN master_area a ON e.area_id = a.id
WHERE e.slug = $1 LIMIT 1
`

type GetEventBySlugRow struct {
	ID             int32          `json:"id"`
	Nama           string         `json:"nama"`
	Slug           string         `json:"slug"`
	GambarUrl      string         `json:"gambar_url"`
	Deskripsi      string         `json:"deskripsi"`
	TanggalMulai   pgtype.Date    `json:"tanggal_mulai"`
	TanggalSelesai pgtype.Date    `json:"tanggal_selesai"`
	Tahun          pgtype.Int2    `json:"tahun"`
	InfoTiket      pgtype.Text    `json:"info_tiket"`
	Lat            pgtype.Numeric `json:"lat"`
	Lng            pgtype.Numeric `json:"lng"`
	Kota           string         `json:"kota"`
}

func (q *Queries) GetEventBySlug(ctx context.Context, slug string) (GetEventBySlugRow, error) {
	row := q.db.QueryRow(ctx, getEventBySlug, slug)
	var i GetEventBySlugRow
	err := row.Scan(
		&i.ID,
		&i.Nama,
		&i.Slug,
		&i.GambarUrl,
		&i.Deskripsi,
		&i.TanggalMulai,
		&i.TanggalSelesai,
		&i.Tahun,
		&i.InfoTiket,
		&i.Lat,
		&i.Lng,
		&i.Kota,
	)
	return i, err
}

const getHotelBySlug = `-- name: GetHotelBySlug :one
SELECT 
    h.id, h.nama, h.slug, h.harga_mulai, h.bintang, h.gambar_url, 
    h.deskripsi, h.alamat, h.highlight_text, h.lat, h.lng, a.nama AS kota
FROM hotel h
JOIN master_area a ON h.area_id = a.id
WHERE h.slug = $1 LIMIT 1
`

type GetHotelBySlugRow struct {
	ID            int32          `json:"id"`
	Nama          string         `json:"nama"`
	Slug          string         `json:"slug"`
	HargaMulai    pgtype.Int4    `json:"harga_mulai"`
	Bintang       pgtype.Int2    `json:"bintang"`
	GambarUrl     string         `json:"gambar_url"`
	Deskripsi     string         `json:"deskripsi"`
	Alamat        string         `json:"alamat"`
	HighlightText pgtype.Text    `json:"highlight_text"`
	Lat           pgtype.Numeric `json:"lat"`
	Lng           pgtype.Numeric `json:"lng"`
	Kota          string         `json:"kota"`
}

func (q *Queries) GetHotelBySlug(ctx context.Context, slug string) (GetHotelBySlugRow, error) {
	row := q.db.QueryRow(ctx, getHotelBySlug, slug)
	var i GetHotelBySlugRow
	err := row.Scan(
		&i.ID,
		&i.Nama,
		&i.Slug,
		&i.HargaMulai,
		&i.Bintang,
		&i.GambarUrl,
		&i.Deskripsi,
		&i.Alamat,
		&i.HighlightText,
		&i.Lat,
		&i.Lng,
		&i.Kota,
	)
	return i, err
}

const listDestinasi = `-- name: ListDestinasi :many
SELECT 
    d.id, d.kategori, d.nama, d.slug, d.gambar_url, d.alamat, a.nama AS kota
FROM destinasi d
JOIN master_area a ON d.area_id = a.id
WHERE 
    ($1::text IS NULL OR 
     d.nama ILIKE '%' || $1::text || '%' OR 
     d.alamat ILIKE '%' || $1::text || '%') 
    AND ($2::text IS NULL OR d.kategori = $2::text)
    AND ($3::int IS NULL OR d.area_id = $3::int)
ORDER BY d.created_at DESC
LIMIT $5::int OFFSET $4::int
`

type ListDestinasiParams struct {
	Search     pgtype.Text `json:"search"`
	Kategori   pgtype.Text `json:"kategori"`
	AreaID     pgtype.Int4 `json:"area_id"`
	OffsetData int32       `json:"offset_data"`
	LimitData  int32       `json:"limit_data"`
}

type ListDestinasiRow struct {
	ID        int32  `json:"id"`
	Kategori  string `json:"kategori"`
	Nama      string `json:"nama"`
	Slug      string `json:"slug"`
	GambarUrl string `json:"gambar_url"`
	Alamat    string `json:"alamat"`
	Kota      string `json:"kota"`
}

func (q *Queries) ListDestinasi(ctx context.Context, arg ListDestinasiParams) ([]ListDestinasiRow, error) {
	rows, err := q.db.Query(ctx, listDestinasi,
		arg.Search,
		arg.Kategori,
		arg.AreaID,
		arg.OffsetData,
		arg.LimitData,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDestinasiRow
	for rows.Next() {
		var i ListDestinasiRow
		if err := rows.Scan(
			&i.ID,
			&i.Kategori,
			&i.Nama,
			&i.Slug,
			&i.GambarUrl,
			&i.Alamat,
			&i.Kota,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDestinasiGambar = `-- name: ListDestinasiGambar :many
SELECT id, gambar_url, urutan 
FROM destinasi_gambar 
WHERE destinasi_id = $1 
ORDER BY urutan ASC
`

type ListDestinasiGambarRow struct {
	ID        int32       `json:"id"`
	GambarUrl string      `json:"gambar_url"`
	Urutan    pgtype.Int4 `json:"urutan"`
}

func (q *Queries) ListDestinasiGambar(ctx context.Context, destinasiID int32) ([]ListDestinasiGambarRow, error) {
	rows, err := q.db.Query(ctx, listDestinasiGambar, destinasiID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDestinasiGambarRow
	for rows.Next() {
		var i ListDestinasiGambarRow
		if err := rows.Scan(&i.ID, &i.GambarUrl, &i.Urutan); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDestinasiMaps = `-- name: ListDestinasiMaps :many
SELECT id, nama, slug, kategori, lat, lng 
FROM destinasi
WHERE ($1::int IS NULL OR area_id = $1::int)
`

type ListDestinasiMapsRow struct {
	ID       int32          `json:"id"`
	Nama     string         `json:"nama"`
	Slug     string         `json:"slug"`
	Kategori string         `json:"kategori"`
	Lat      pgtype.Numeric `json:"lat"`
	Lng      pgtype.Numeric `json:"lng"`
}

func (q *Queries) ListDestinasiMaps(ctx context.Context, areaID pgtype.Int4) ([]ListDestinasiMapsRow, error) {
	rows, err := q.db.Query(ctx, listDestinasiMaps, areaID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDestinasiMapsRow
	for rows.Next() {
		var i ListDestinasiMapsRow
		if err := rows.Scan(
			&i.ID,
			&i.Nama,
			&i.Slug,
			&i.Kategori,
			&i.Lat,
			&i.Lng,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEvent = `-- name: ListEvent :many
SELECT 
    e.id, e.nama, e.slug, e.gambar_url, e.tanggal_mulai, e.tanggal_selesai, 
    e.tahun, e.info_tiket, a.nama AS kota
FROM event e
JOIN master_area a ON e.area_id = a.id
WHERE 
    ($1::text IS NULL OR e.nama ILIKE '%' || $1::text || '%')
    AND ($2::int IS NULL OR e.area_id = $2::int)
    AND ($3::smallint IS NULL OR e.tahun = $3::smallint)
ORDER BY e.tanggal_mulai ASC
LIMIT $5::int OFFSET $4::int
`

type ListEventParams struct {
	Search     pgtype.Text `json:"search"`
	AreaID     pgtype.Int4 `json:"area_id"`
	Tahun      pgtype.Int2 `json:"tahun"`
	OffsetData int32       `json:"offset_data"`
	LimitData  int32       `json:"limit_data"`
}

type ListEventRow struct {
	ID             int32       `json:"id"`
	Nama           string      `json:"nama"`
	Slug           string      `json:"slug"`
	GambarUrl      string      `json:"gambar_url"`
	TanggalMulai   pgtype.Date `json:"tanggal_mulai"`
	TanggalSelesai pgtype.Date `json:"tanggal_selesai"`
	Tahun          pgtype.Int2 `json:"tahun"`
	InfoTiket      pgtype.Text `json:"info_tiket"`
	Kota           string      `json:"kota"`
}

func (q *Queries) ListEvent(ctx context.Context, arg ListEventParams) ([]ListEventRow, error) {
	rows, err := q.db.Query(ctx, listEvent,
		arg.Search,
		arg.AreaID,
		arg.Tahun,
		arg.OffsetData,
		arg.LimitData,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEventRow
	for rows.Next() {
		var i ListEventRow
		if err := rows.Scan(
			&i.ID,
			&i.Nama,
			&i.Slug,
			&i.GambarUrl,
			&i.TanggalMulai,
			&i.TanggalSelesai,
			&i.Tahun,
			&i.InfoTiket,
			&i.Kota,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHotel = `-- name: ListHotel :many
SELECT 
    h.id, h.nama, h.slug, h.harga_mulai, h.bintang, h.gambar_url, a.nama AS kota
FROM hotel h
JOIN master_area a ON h.area_id = a.id
WHERE 
    ($1::text IS NULL OR h.nama ILIKE '%' || $1::text || '%')
    AND ($2::int IS NULL OR h.area_id = $2::int)
    AND ($3::smallint IS NULL OR h.bintang >= $3::smallint)
ORDER BY h.bintang DESC, h.harga_mulai ASC
LIMIT $5::int OFFSET $4::int
`

type ListHotelParams struct {
	Search     pgtype.Text `json:"search"`
	AreaID     pgtype.Int4 `json:"area_id"`
	MinBintang pgtype.Int2 `json:"min_bintang"`
	OffsetData int32       `json:"offset_data"`
	LimitData  int32       `json:"limit_data"`
}

type ListHotelRow struct {
	ID         int32       `json:"id"`
	Nama       string      `json:"nama"`
	Slug       string      `json:"slug"`
	HargaMulai pgtype.Int4 `json:"harga_mulai"`
	Bintang    pgtype.Int2 `json:"bintang"`
	GambarUrl  string      `json:"gambar_url"`
	Kota       string      `json:"kota"`
}

func (q *Queries) ListHotel(ctx context.Context, arg ListHotelParams) ([]ListHotelRow, error) {
	rows, err := q.db.Query(ctx, listHotel,
		arg.Search,
		arg.AreaID,
		arg.MinBintang,
		arg.OffsetData,
		arg.LimitData,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListHotelRow
	for rows.Next() {
		var i ListHotelRow
		if err := rows.Scan(
			&i.ID,
			&i.Nama,
			&i.Slug,
			&i.HargaMulai,
			&i.Bintang,
			&i.GambarUrl,
			&i.Kota,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDestinasi = `-- name: UpdateDestinasi :one
UPDATE destinasi
SET 
    area_id = $2, kategori = $3, nama = $4, slug = $5, gambar_url = $6, 
    deskripsi = $7, alamat = $8, highlight_text = $9, lat = $10, lng = $11
WHERE id = $1
RETURNING id, nama, slug
`

type UpdateDestinasiParams struct {
	ID            int32          `json:"id"`
	AreaID        int32          `json:"area_id"`
	Kategori      string         `json:"kategori"`
	Nama          string         `json:"nama"`
	Slug          string         `json:"slug"`
	GambarUrl     string         `json:"gambar_url"`
	Deskripsi     string         `json:"deskripsi"`
	Alamat        string         `json:"alamat"`
	HighlightText string         `json:"highlight_text"`
	Lat           pgtype.Numeric `json:"lat"`
	Lng           pgtype.Numeric `json:"lng"`
}

type UpdateDestinasiRow struct {
	ID   int32  `json:"id"`
	Nama string `json:"nama"`
	Slug string `json:"slug"`
}

func (q *Queries) UpdateDestinasi(ctx context.Context, arg UpdateDestinasiParams) (UpdateDestinasiRow, error) {
	row := q.db.QueryRow(ctx, updateDestinasi,
		arg.ID,
		arg.AreaID,
		arg.Kategori,
		arg.Nama,
		arg.Slug,
		arg.GambarUrl,
		arg.Deskripsi,
		arg.Alamat,
		arg.HighlightText,
		arg.Lat,
		arg.Lng,
	)
	var i UpdateDestinasiRow
	err := row.Scan(&i.ID, &i.Nama, &i.Slug)
	return i, err
}
