// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type JenisKelaminType string

const (
	JenisKelaminTypeLakiLaki  JenisKelaminType = "laki_laki"
	JenisKelaminTypePerempuan JenisKelaminType = "perempuan"
)

func (e *JenisKelaminType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = JenisKelaminType(s)
	case string:
		*e = JenisKelaminType(s)
	default:
		return fmt.Errorf("unsupported scan type for JenisKelaminType: %T", src)
	}
	return nil
}

type NullJenisKelaminType struct {
	JenisKelaminType JenisKelaminType `json:"jenis_kelamin_type"`
	Valid            bool             `json:"valid"` // Valid is true if JenisKelaminType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullJenisKelaminType) Scan(value interface{}) error {
	if value == nil {
		ns.JenisKelaminType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.JenisKelaminType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullJenisKelaminType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.JenisKelaminType), nil
}

type PendidikanType string

const (
	PendidikanTypeTidakSekolah PendidikanType = "tidak_sekolah"
	PendidikanTypeSd           PendidikanType = "sd"
	PendidikanTypeSmp          PendidikanType = "smp"
	PendidikanTypeSmaSmk       PendidikanType = "sma_smk"
	PendidikanTypeD3           PendidikanType = "d3"
	PendidikanTypeS1           PendidikanType = "s1"
	PendidikanTypeS2           PendidikanType = "s2"
	PendidikanTypeS3           PendidikanType = "s3"
)

func (e *PendidikanType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PendidikanType(s)
	case string:
		*e = PendidikanType(s)
	default:
		return fmt.Errorf("unsupported scan type for PendidikanType: %T", src)
	}
	return nil
}

type NullPendidikanType struct {
	PendidikanType PendidikanType `json:"pendidikan_type"`
	Valid          bool           `json:"valid"` // Valid is true if PendidikanType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPendidikanType) Scan(value interface{}) error {
	if value == nil {
		ns.PendidikanType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PendidikanType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPendidikanType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PendidikanType), nil
}

type StatusDaftarType string

const (
	StatusDaftarTypePending  StatusDaftarType = "pending"
	StatusDaftarTypeDiterima StatusDaftarType = "diterima"
	StatusDaftarTypeDitolak  StatusDaftarType = "ditolak"
)

func (e *StatusDaftarType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = StatusDaftarType(s)
	case string:
		*e = StatusDaftarType(s)
	default:
		return fmt.Errorf("unsupported scan type for StatusDaftarType: %T", src)
	}
	return nil
}

type NullStatusDaftarType struct {
	StatusDaftarType StatusDaftarType `json:"status_daftar_type"`
	Valid            bool             `json:"valid"` // Valid is true if StatusDaftarType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullStatusDaftarType) Scan(value interface{}) error {
	if value == nil {
		ns.StatusDaftarType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.StatusDaftarType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullStatusDaftarType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.StatusDaftarType), nil
}

type Blk struct {
	ID        int32              `json:"id"`
	Nama      string             `json:"nama"`
	Alamat    string             `json:"alamat"`
	KabKota   string             `json:"kab_kota"`
	Kecamatan pgtype.Text        `json:"kecamatan"`
	Slug      string             `json:"slug"`
	Lat       pgtype.Float8      `json:"lat"`
	Lng       pgtype.Float8      `json:"lng"`
	Aktif     bool               `json:"aktif"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Kejuruan struct {
	ID        int32              `json:"id"`
	BlkID     int32              `json:"blk_id"`
	Nama      string             `json:"nama"`
	Aktif     bool               `json:"aktif"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Pendaftaran struct {
	ID                    int32              `json:"id"`
	BlkID                 int32              `json:"blk_id"`
	KejuruanID            int32              `json:"kejuruan_id"`
	Nik                   string             `json:"nik"`
	NamaLengkap           string             `json:"nama_lengkap"`
	TempatLahir           string             `json:"tempat_lahir"`
	TanggalLahir          pgtype.Date        `json:"tanggal_lahir"`
	Email                 string             `json:"email"`
	JenisKelamin          JenisKelaminType   `json:"jenis_kelamin"`
	Provinsi              string             `json:"provinsi"`
	KabKota               string             `json:"kab_kota"`
	Kecamatan             string             `json:"kecamatan"`
	Kelurahan             string             `json:"kelurahan"`
	Rt                    string             `json:"rt"`
	Rw                    string             `json:"rw"`
	AlamatLengkap         string             `json:"alamat_lengkap"`
	PenyandangDisabilitas bool               `json:"penyandang_disabilitas"`
	NoWa                  string             `json:"no_wa"`
	NoWaDarurat           string             `json:"no_wa_darurat"`
	PendidikanTerakhir    PendidikanType     `json:"pendidikan_terakhir"`
	PendidikanSekarang    PendidikanType     `json:"pendidikan_sekarang"`
	AsalSekolah           pgtype.Text        `json:"asal_sekolah"`
	Jurusan               pgtype.Text        `json:"jurusan"`
	FotoUrl               string             `json:"foto_url"`
	Status                StatusDaftarType   `json:"status"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
}
