// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cekStatusPendaftaran = `-- name: CekStatusPendaftaran :many
SELECT
    p.id, p.status, p.created_at,
    b.nama  AS blk_nama,
    b.slug  AS blk_slug,
    k.nama  AS kejuruan_nama
FROM pendaftaran p
JOIN blk      b ON b.id = p.blk_id
JOIN kejuruan k ON k.id = p.kejuruan_id
WHERE p.nik   = $1
  AND p.no_wa = $2
ORDER BY p.created_at DESC
`

type CekStatusPendaftaranParams struct {
	Nik  string `json:"nik"`
	NoWa string `json:"no_wa"`
}

type CekStatusPendaftaranRow struct {
	ID           int32              `json:"id"`
	Status       StatusDaftarType   `json:"status"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	BlkNama      string             `json:"blk_nama"`
	BlkSlug      string             `json:"blk_slug"`
	KejuruanNama string             `json:"kejuruan_nama"`
}

func (q *Queries) CekStatusPendaftaran(ctx context.Context, arg CekStatusPendaftaranParams) ([]CekStatusPendaftaranRow, error) {
	rows, err := q.db.Query(ctx, cekStatusPendaftaran, arg.Nik, arg.NoWa)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CekStatusPendaftaranRow
	for rows.Next() {
		var i CekStatusPendaftaranRow
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.CreatedAt,
			&i.BlkNama,
			&i.BlkSlug,
			&i.KejuruanNama,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countAktifBLK = `-- name: CountAktifBLK :one
SELECT COUNT(id)
FROM blk
WHERE aktif = true
  AND ($1::text IS NULL OR kab_kota = $1::text)
`

func (q *Queries) CountAktifBLK(ctx context.Context, kabKotaFilter pgtype.Text) (int64, error) {
	row := q.db.QueryRow(ctx, countAktifBLK, kabKotaFilter)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAllBLK = `-- name: CountAllBLK :one
SELECT COUNT(id) FROM blk
`

func (q *Queries) CountAllBLK(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAllBLK)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPendaftaran = `-- name: CountPendaftaran :one
SELECT COUNT(p.id)
FROM pendaftaran p
WHERE ($1::int IS NULL OR p.blk_id = $1::int)
  AND ($2::status_daftar_type IS NULL OR p.status = $2::status_daftar_type)
`

type CountPendaftaranParams struct {
	BlkIDFilter  pgtype.Int4          `json:"blk_id_filter"`
	StatusFilter NullStatusDaftarType `json:"status_filter"`
}

func (q *Queries) CountPendaftaran(ctx context.Context, arg CountPendaftaranParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPendaftaran, arg.BlkIDFilter, arg.StatusFilter)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createBLK = `-- name: CreateBLK :one
INSERT INTO blk (nama, alamat, kab_kota, kecamatan, slug, lat, lng)
VALUES (
    $1, $2, $3,
    $4, $5,
    $6, $7
)
RETURNING id, slug
`

type CreateBLKParams struct {
	Nama      string        `json:"nama"`
	Alamat    string        `json:"alamat"`
	KabKota   string        `json:"kab_kota"`
	Kecamatan pgtype.Text   `json:"kecamatan"`
	Slug      string        `json:"slug"`
	Lat       pgtype.Float8 `json:"lat"`
	Lng       pgtype.Float8 `json:"lng"`
}

type CreateBLKRow struct {
	ID   int32  `json:"id"`
	Slug string `json:"slug"`
}

func (q *Queries) CreateBLK(ctx context.Context, arg CreateBLKParams) (CreateBLKRow, error) {
	row := q.db.QueryRow(ctx, createBLK,
		arg.Nama,
		arg.Alamat,
		arg.KabKota,
		arg.Kecamatan,
		arg.Slug,
		arg.Lat,
		arg.Lng,
	)
	var i CreateBLKRow
	err := row.Scan(&i.ID, &i.Slug)
	return i, err
}

const createKejuruan = `-- name: CreateKejuruan :one
INSERT INTO kejuruan (blk_id, nama)
VALUES ($1, $2)
RETURNING id
`

type CreateKejuruanParams struct {
	BlkID int32  `json:"blk_id"`
	Nama  string `json:"nama"`
}

func (q *Queries) CreateKejuruan(ctx context.Context, arg CreateKejuruanParams) (int32, error) {
	row := q.db.QueryRow(ctx, createKejuruan, arg.BlkID, arg.Nama)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const createPendaftaran = `-- name: CreatePendaftaran :one

INSERT INTO pendaftaran (
    blk_id, kejuruan_id, nik, nama_lengkap, tempat_lahir, tanggal_lahir,
    email, jenis_kelamin, provinsi, kab_kota, kecamatan, kelurahan,
    rt, rw, alamat_lengkap, penyandang_disabilitas,
    no_wa, no_wa_darurat, pendidikan_terakhir, pendidikan_sekarang,
    asal_sekolah, jurusan, foto_url
)
VALUES (
    $1, $2, $3,
    $4, $5, $6,
    $7, $8, $9,
    $10, $11, $12,
    $13, $14, $15,
    $16, $17, $18,
    $19, $20,
    $21, $22, $23
)
RETURNING id, status, created_at
`

type CreatePendaftaranParams struct {
	BlkID                 int32            `json:"blk_id"`
	KejuruanID            int32            `json:"kejuruan_id"`
	Nik                   string           `json:"nik"`
	NamaLengkap           string           `json:"nama_lengkap"`
	TempatLahir           string           `json:"tempat_lahir"`
	TanggalLahir          pgtype.Date      `json:"tanggal_lahir"`
	Email                 string           `json:"email"`
	JenisKelamin          JenisKelaminType `json:"jenis_kelamin"`
	Provinsi              string           `json:"provinsi"`
	KabKota               string           `json:"kab_kota"`
	Kecamatan             string           `json:"kecamatan"`
	Kelurahan             string           `json:"kelurahan"`
	Rt                    string           `json:"rt"`
	Rw                    string           `json:"rw"`
	AlamatLengkap         string           `json:"alamat_lengkap"`
	PenyandangDisabilitas bool             `json:"penyandang_disabilitas"`
	NoWa                  string           `json:"no_wa"`
	NoWaDarurat           string           `json:"no_wa_darurat"`
	PendidikanTerakhir    PendidikanType   `json:"pendidikan_terakhir"`
	PendidikanSekarang    PendidikanType   `json:"pendidikan_sekarang"`
	AsalSekolah           pgtype.Text      `json:"asal_sekolah"`
	Jurusan               pgtype.Text      `json:"jurusan"`
	FotoUrl               string           `json:"foto_url"`
}

type CreatePendaftaranRow struct {
	ID        int32              `json:"id"`
	Status    StatusDaftarType   `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

// =====================================================================
// PENDAFTARAN
// =====================================================================
func (q *Queries) CreatePendaftaran(ctx context.Context, arg CreatePendaftaranParams) (CreatePendaftaranRow, error) {
	row := q.db.QueryRow(ctx, createPendaftaran,
		arg.BlkID,
		arg.KejuruanID,
		arg.Nik,
		arg.NamaLengkap,
		arg.TempatLahir,
		arg.TanggalLahir,
		arg.Email,
		arg.JenisKelamin,
		arg.Provinsi,
		arg.KabKota,
		arg.Kecamatan,
		arg.Kelurahan,
		arg.Rt,
		arg.Rw,
		arg.AlamatLengkap,
		arg.PenyandangDisabilitas,
		arg.NoWa,
		arg.NoWaDarurat,
		arg.PendidikanTerakhir,
		arg.PendidikanSekarang,
		arg.AsalSekolah,
		arg.Jurusan,
		arg.FotoUrl,
	)
	var i CreatePendaftaranRow
	err := row.Scan(&i.ID, &i.Status, &i.CreatedAt)
	return i, err
}

const deactivateBLK = `-- name: DeactivateBLK :exec
UPDATE blk
SET aktif = false, updated_at = CURRENT_TIMESTAMP
WHERE slug = $1
`

func (q *Queries) DeactivateBLK(ctx context.Context, slug string) error {
	_, err := q.db.Exec(ctx, deactivateBLK, slug)
	return err
}

const deactivateKejuruan = `-- name: DeactivateKejuruan :exec
UPDATE kejuruan
SET aktif = false, updated_at = CURRENT_TIMESTAMP
WHERE id = $1
`

func (q *Queries) DeactivateKejuruan(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deactivateKejuruan, id)
	return err
}

const getBLKByID = `-- name: GetBLKByID :one
SELECT id, nama, alamat, kab_kota, kecamatan, slug, lat, lng, aktif
FROM blk
WHERE id = $1
LIMIT 1
`

type GetBLKByIDRow struct {
	ID        int32         `json:"id"`
	Nama      string        `json:"nama"`
	Alamat    string        `json:"alamat"`
	KabKota   string        `json:"kab_kota"`
	Kecamatan pgtype.Text   `json:"kecamatan"`
	Slug      string        `json:"slug"`
	Lat       pgtype.Float8 `json:"lat"`
	Lng       pgtype.Float8 `json:"lng"`
	Aktif     bool          `json:"aktif"`
}

func (q *Queries) GetBLKByID(ctx context.Context, id int32) (GetBLKByIDRow, error) {
	row := q.db.QueryRow(ctx, getBLKByID, id)
	var i GetBLKByIDRow
	err := row.Scan(
		&i.ID,
		&i.Nama,
		&i.Alamat,
		&i.KabKota,
		&i.Kecamatan,
		&i.Slug,
		&i.Lat,
		&i.Lng,
		&i.Aktif,
	)
	return i, err
}

const getBLKBySlug = `-- name: GetBLKBySlug :one
SELECT id, nama, alamat, kab_kota, kecamatan, slug, lat, lng, aktif
FROM blk
WHERE slug = $1
LIMIT 1
`

type GetBLKBySlugRow struct {
	ID        int32         `json:"id"`
	Nama      string        `json:"nama"`
	Alamat    string        `json:"alamat"`
	KabKota   string        `json:"kab_kota"`
	Kecamatan pgtype.Text   `json:"kecamatan"`
	Slug      string        `json:"slug"`
	Lat       pgtype.Float8 `json:"lat"`
	Lng       pgtype.Float8 `json:"lng"`
	Aktif     bool          `json:"aktif"`
}

func (q *Queries) GetBLKBySlug(ctx context.Context, slug string) (GetBLKBySlugRow, error) {
	row := q.db.QueryRow(ctx, getBLKBySlug, slug)
	var i GetBLKBySlugRow
	err := row.Scan(
		&i.ID,
		&i.Nama,
		&i.Alamat,
		&i.KabKota,
		&i.Kecamatan,
		&i.Slug,
		&i.Lat,
		&i.Lng,
		&i.Aktif,
	)
	return i, err
}

const getDistinctKabKotaBLK = `-- name: GetDistinctKabKotaBLK :many
SELECT DISTINCT kab_kota FROM blk WHERE aktif = true ORDER BY kab_kota ASC
`

func (q *Queries) GetDistinctKabKotaBLK(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, getDistinctKabKotaBLK)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var kab_kota string
		if err := rows.Scan(&kab_kota); err != nil {
			return nil, err
		}
		items = append(items, kab_kota)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getKejuruanByID = `-- name: GetKejuruanByID :one
SELECT id, blk_id, nama, aktif
FROM kejuruan
WHERE id = $1
LIMIT 1
`

type GetKejuruanByIDRow struct {
	ID    int32  `json:"id"`
	BlkID int32  `json:"blk_id"`
	Nama  string `json:"nama"`
	Aktif bool   `json:"aktif"`
}

func (q *Queries) GetKejuruanByID(ctx context.Context, id int32) (GetKejuruanByIDRow, error) {
	row := q.db.QueryRow(ctx, getKejuruanByID, id)
	var i GetKejuruanByIDRow
	err := row.Scan(
		&i.ID,
		&i.BlkID,
		&i.Nama,
		&i.Aktif,
	)
	return i, err
}

const getPendaftaranByID = `-- name: GetPendaftaranByID :one
SELECT
    p.id, p.nik, p.nama_lengkap, p.tempat_lahir, p.tanggal_lahir,
    p.email, p.jenis_kelamin, p.provinsi, p.kab_kota, p.kecamatan,
    p.kelurahan, p.rt, p.rw, p.alamat_lengkap, p.penyandang_disabilitas,
    p.no_wa, p.no_wa_darurat, p.pendidikan_terakhir, p.pendidikan_sekarang,
    p.asal_sekolah, p.jurusan, p.foto_url, p.status, p.created_at,
    b.nama AS blk_nama,
    k.nama AS kejuruan_nama
FROM pendaftaran p
JOIN blk      b ON b.id = p.blk_id
JOIN kejuruan k ON k.id = p.kejuruan_id
WHERE p.id = $1
LIMIT 1
`

type GetPendaftaranByIDRow struct {
	ID                    int32              `json:"id"`
	Nik                   string             `json:"nik"`
	NamaLengkap           string             `json:"nama_lengkap"`
	TempatLahir           string             `json:"tempat_lahir"`
	TanggalLahir          pgtype.Date        `json:"tanggal_lahir"`
	Email                 string             `json:"email"`
	JenisKelamin          JenisKelaminType   `json:"jenis_kelamin"`
	Provinsi              string             `json:"provinsi"`
	KabKota               string             `json:"kab_kota"`
	Kecamatan             string             `json:"kecamatan"`
	Kelurahan             string             `json:"kelurahan"`
	Rt                    string             `json:"rt"`
	Rw                    string             `json:"rw"`
	AlamatLengkap         string             `json:"alamat_lengkap"`
	PenyandangDisabilitas bool               `json:"penyandang_disabilitas"`
	NoWa                  string             `json:"no_wa"`
	NoWaDarurat           string             `json:"no_wa_darurat"`
	PendidikanTerakhir    PendidikanType     `json:"pendidikan_terakhir"`
	PendidikanSekarang    PendidikanType     `json:"pendidikan_sekarang"`
	AsalSekolah           pgtype.Text        `json:"asal_sekolah"`
	Jurusan               pgtype.Text        `json:"jurusan"`
	FotoUrl               string             `json:"foto_url"`
	Status                StatusDaftarType   `json:"status"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	BlkNama               string             `json:"blk_nama"`
	KejuruanNama          string             `json:"kejuruan_nama"`
}

func (q *Queries) GetPendaftaranByID(ctx context.Context, id int32) (GetPendaftaranByIDRow, error) {
	row := q.db.QueryRow(ctx, getPendaftaranByID, id)
	var i GetPendaftaranByIDRow
	err := row.Scan(
		&i.ID,
		&i.Nik,
		&i.NamaLengkap,
		&i.TempatLahir,
		&i.TanggalLahir,
		&i.Email,
		&i.JenisKelamin,
		&i.Provinsi,
		&i.KabKota,
		&i.Kecamatan,
		&i.Kelurahan,
		&i.Rt,
		&i.Rw,
		&i.AlamatLengkap,
		&i.PenyandangDisabilitas,
		&i.NoWa,
		&i.NoWaDarurat,
		&i.PendidikanTerakhir,
		&i.PendidikanSekarang,
		&i.AsalSekolah,
		&i.Jurusan,
		&i.FotoUrl,
		&i.Status,
		&i.CreatedAt,
		&i.BlkNama,
		&i.KejuruanNama,
	)
	return i, err
}

const listAktifBLK = `-- name: ListAktifBLK :many

SELECT id, nama, alamat, kab_kota, kecamatan, slug, lat, lng
FROM blk
WHERE aktif = true
  AND ($1::text IS NULL OR kab_kota = $1::text)
ORDER BY kab_kota, nama
`

type ListAktifBLKRow struct {
	ID        int32         `json:"id"`
	Nama      string        `json:"nama"`
	Alamat    string        `json:"alamat"`
	KabKota   string        `json:"kab_kota"`
	Kecamatan pgtype.Text   `json:"kecamatan"`
	Slug      string        `json:"slug"`
	Lat       pgtype.Float8 `json:"lat"`
	Lng       pgtype.Float8 `json:"lng"`
}

// =====================================================================
// BLK
// =====================================================================
func (q *Queries) ListAktifBLK(ctx context.Context, kabKotaFilter pgtype.Text) ([]ListAktifBLKRow, error) {
	rows, err := q.db.Query(ctx, listAktifBLK, kabKotaFilter)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAktifBLKRow
	for rows.Next() {
		var i ListAktifBLKRow
		if err := rows.Scan(
			&i.ID,
			&i.Nama,
			&i.Alamat,
			&i.KabKota,
			&i.Kecamatan,
			&i.Slug,
			&i.Lat,
			&i.Lng,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAktifKejuruanByBLK = `-- name: ListAktifKejuruanByBLK :many

SELECT id, nama
FROM kejuruan
WHERE blk_id = $1
  AND aktif = true
ORDER BY nama
`

type ListAktifKejuruanByBLKRow struct {
	ID   int32  `json:"id"`
	Nama string `json:"nama"`
}

// =====================================================================
// KEJURUAN
// =====================================================================
func (q *Queries) ListAktifKejuruanByBLK(ctx context.Context, blkID int32) ([]ListAktifKejuruanByBLKRow, error) {
	rows, err := q.db.Query(ctx, listAktifKejuruanByBLK, blkID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAktifKejuruanByBLKRow
	for rows.Next() {
		var i ListAktifKejuruanByBLKRow
		if err := rows.Scan(&i.ID, &i.Nama); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllBLKAdmin = `-- name: ListAllBLKAdmin :many
SELECT id, nama, alamat, kab_kota, kecamatan, slug, lat, lng, aktif
FROM blk
ORDER BY kab_kota, nama
LIMIT $2 OFFSET $1
`

type ListAllBLKAdminParams struct {
	OffsetData int32 `json:"offset_data"`
	LimitData  int32 `json:"limit_data"`
}

type ListAllBLKAdminRow struct {
	ID        int32         `json:"id"`
	Nama      string        `json:"nama"`
	Alamat    string        `json:"alamat"`
	KabKota   string        `json:"kab_kota"`
	Kecamatan pgtype.Text   `json:"kecamatan"`
	Slug      string        `json:"slug"`
	Lat       pgtype.Float8 `json:"lat"`
	Lng       pgtype.Float8 `json:"lng"`
	Aktif     bool          `json:"aktif"`
}

func (q *Queries) ListAllBLKAdmin(ctx context.Context, arg ListAllBLKAdminParams) ([]ListAllBLKAdminRow, error) {
	rows, err := q.db.Query(ctx, listAllBLKAdmin, arg.OffsetData, arg.LimitData)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllBLKAdminRow
	for rows.Next() {
		var i ListAllBLKAdminRow
		if err := rows.Scan(
			&i.ID,
			&i.Nama,
			&i.Alamat,
			&i.KabKota,
			&i.Kecamatan,
			&i.Slug,
			&i.Lat,
			&i.Lng,
			&i.Aktif,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllKejuruanByBLKAdmin = `-- name: ListAllKejuruanByBLKAdmin :many
SELECT id, nama, aktif
FROM kejuruan
WHERE blk_id = $1
ORDER BY nama
`

type ListAllKejuruanByBLKAdminRow struct {
	ID    int32  `json:"id"`
	Nama  string `json:"nama"`
	Aktif bool   `json:"aktif"`
}

func (q *Queries) ListAllKejuruanByBLKAdmin(ctx context.Context, blkID int32) ([]ListAllKejuruanByBLKAdminRow, error) {
	rows, err := q.db.Query(ctx, listAllKejuruanByBLKAdmin, blkID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllKejuruanByBLKAdminRow
	for rows.Next() {
		var i ListAllKejuruanByBLKAdminRow
		if err := rows.Scan(&i.ID, &i.Nama, &i.Aktif); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendaftaranAdmin = `-- name: ListPendaftaranAdmin :many
SELECT
    p.id, p.nik, p.nama_lengkap, p.no_wa, p.status, p.created_at,
    b.nama AS blk_nama,
    k.nama AS kejuruan_nama
FROM pendaftaran p
JOIN blk      b ON b.id = p.blk_id
JOIN kejuruan k ON k.id = p.kejuruan_id
WHERE ($1::int IS NULL OR p.blk_id = $1::int)
  AND ($2::status_daftar_type IS NULL OR p.status = $2::status_daftar_type)
ORDER BY p.created_at DESC
LIMIT $4 OFFSET $3
`

type ListPendaftaranAdminParams struct {
	BlkIDFilter  pgtype.Int4          `json:"blk_id_filter"`
	StatusFilter NullStatusDaftarType `json:"status_filter"`
	OffsetData   int32                `json:"offset_data"`
	LimitData    int32                `json:"limit_data"`
}

type ListPendaftaranAdminRow struct {
	ID           int32              `json:"id"`
	Nik          string             `json:"nik"`
	NamaLengkap  string             `json:"nama_lengkap"`
	NoWa         string             `json:"no_wa"`
	Status       StatusDaftarType   `json:"status"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	BlkNama      string             `json:"blk_nama"`
	KejuruanNama string             `json:"kejuruan_nama"`
}

func (q *Queries) ListPendaftaranAdmin(ctx context.Context, arg ListPendaftaranAdminParams) ([]ListPendaftaranAdminRow, error) {
	rows, err := q.db.Query(ctx, listPendaftaranAdmin,
		arg.BlkIDFilter,
		arg.StatusFilter,
		arg.OffsetData,
		arg.LimitData,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPendaftaranAdminRow
	for rows.Next() {
		var i ListPendaftaranAdminRow
		if err := rows.Scan(
			&i.ID,
			&i.Nik,
			&i.NamaLengkap,
			&i.NoWa,
			&i.Status,
			&i.CreatedAt,
			&i.BlkNama,
			&i.KejuruanNama,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBLK = `-- name: UpdateBLK :exec
UPDATE blk
SET
    nama      = $1,
    alamat    = $2,
    kab_kota  = $3,
    kecamatan = $4,
    slug      = $5,
    lat       = $6,
    lng       = $7,
    aktif     = $8,
    updated_at = CURRENT_TIMESTAMP
WHERE slug = $9
`

type UpdateBLKParams struct {
	Nama      string        `json:"nama"`
	Alamat    string        `json:"alamat"`
	KabKota   string        `json:"kab_kota"`
	Kecamatan pgtype.Text   `json:"kecamatan"`
	SlugBaru  string        `json:"slug_baru"`
	Lat       pgtype.Float8 `json:"lat"`
	Lng       pgtype.Float8 `json:"lng"`
	Aktif     bool          `json:"aktif"`
	SlugLama  string        `json:"slug_lama"`
}

func (q *Queries) UpdateBLK(ctx context.Context, arg UpdateBLKParams) error {
	_, err := q.db.Exec(ctx, updateBLK,
		arg.Nama,
		arg.Alamat,
		arg.KabKota,
		arg.Kecamatan,
		arg.SlugBaru,
		arg.Lat,
		arg.Lng,
		arg.Aktif,
		arg.SlugLama,
	)
	return err
}

const updateKejuruan = `-- name: UpdateKejuruan :exec
UPDATE kejuruan
SET nama = $1, aktif = $2, updated_at = CURRENT_TIMESTAMP
WHERE id = $3
`

type UpdateKejuruanParams struct {
	Nama  string `json:"nama"`
	Aktif bool   `json:"aktif"`
	ID    int32  `json:"id"`
}

func (q *Queries) UpdateKejuruan(ctx context.Context, arg UpdateKejuruanParams) error {
	_, err := q.db.Exec(ctx, updateKejuruan, arg.Nama, arg.Aktif, arg.ID)
	return err
}

const updateStatusPendaftaran = `-- name: UpdateStatusPendaftaran :exec
UPDATE pendaftaran
SET status = $1, updated_at = CURRENT_TIMESTAMP
WHERE id = $2
`

type UpdateStatusPendaftaranParams struct {
	Status StatusDaftarType `json:"status"`
	ID     int32            `json:"id"`
}

func (q *Queries) UpdateStatusPendaftaran(ctx context.Context, arg UpdateStatusPendaftaranParams) error {
	_, err := q.db.Exec(ctx, updateStatusPendaftaran, arg.Status, arg.ID)
	return err
}
