// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type KendaraanPajak struct {
	ID                 pgtype.UUID        `json:"id"`
	PlatNomor          string             `json:"plat_nomor"`
	PlatNomorDisplay   string             `json:"plat_nomor_display"`
	NomorRangka        string             `json:"nomor_rangka"`
	StatusAktif        bool               `json:"status_aktif"`
	Merk               string             `json:"merk"`
	Tipe               string             `json:"tipe"`
	Warna              string             `json:"warna"`
	TahunBuat          int16              `json:"tahun_buat"`
	Model              string             `json:"model"`
	MasaPajak          pgtype.Date        `json:"masa_pajak"`
	PkbPokok           int32              `json:"pkb_pokok"`
	OpsenPkb           int32              `json:"opsen_pkb"`
	Swdkllj            int32              `json:"swdkllj"`
	ParkirBerlangganan int32              `json:"parkir_berlangganan"`
	CetakStnk          int32              `json:"cetak_stnk"`
	CetakTnkb          int32              `json:"cetak_tnkb"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	TotalPajakTahunan  pgtype.Int4        `json:"total_pajak_tahunan"`
}

type MasterNjkb struct {
	ID             int32              `json:"id"`
	JenisKendaraan string             `json:"jenis_kendaraan"`
	Merk           string             `json:"merk"`
	Model          string             `json:"model"`
	Tipe           string             `json:"tipe"`
	Tahun          int16              `json:"tahun"`
	NilaiJual      int64              `json:"nilai_jual"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type TarifPkb struct {
	ID              int32          `json:"id"`
	JenisPlat       string         `json:"jenis_plat"`
	Label           string         `json:"label"`
	TarifPkbPersen  pgtype.Numeric `json:"tarif_pkb_persen"`
	OpsenPkbPersen  pgtype.Numeric `json:"opsen_pkb_persen"`
	Bbn1Persen      pgtype.Numeric `json:"bbn1_persen"`
	OpsenBbn1Persen pgtype.Numeric `json:"opsen_bbn1_persen"`
	Bbn2Persen      pgtype.Numeric `json:"bbn2_persen"`
}
