// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countKendaraanPajak = `-- name: CountKendaraanPajak :one
SELECT COUNT(*) FROM kendaraan_pajak
`

func (q *Queries) CountKendaraanPajak(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countKendaraanPajak)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countMasterNjkb = `-- name: CountMasterNjkb :one
SELECT COUNT(*) FROM master_njkb
`

func (q *Queries) CountMasterNjkb(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countMasterNjkb)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createKendaraanPajak = `-- name: CreateKendaraanPajak :one
INSERT INTO kendaraan_pajak (
    plat_nomor, plat_nomor_display, nomor_rangka, status_aktif,
    merk, tipe, warna, tahun_buat, model, masa_pajak,
    pkb_pokok, opsen_pkb, swdkllj, parkir_berlangganan,
    cetak_stnk, cetak_tnkb
) VALUES (
    UPPER(REPLACE($1::text, ' ', '')),
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13,
    $14,
    $15,
    $16
) RETURNING plat_nomor
`

type CreateKendaraanPajakParams struct {
	PlatNomor          string      `json:"plat_nomor"`
	PlatNomorDisplay   string      `json:"plat_nomor_display"`
	NomorRangka        string      `json:"nomor_rangka"`
	StatusAktif        bool        `json:"status_aktif"`
	Merk               string      `json:"merk"`
	Tipe               string      `json:"tipe"`
	Warna              string      `json:"warna"`
	TahunBuat          int16       `json:"tahun_buat"`
	Model              string      `json:"model"`
	MasaPajak          pgtype.Date `json:"masa_pajak"`
	PkbPokok           int32       `json:"pkb_pokok"`
	OpsenPkb           int32       `json:"opsen_pkb"`
	Swdkllj            int32       `json:"swdkllj"`
	ParkirBerlangganan int32       `json:"parkir_berlangganan"`
	CetakStnk          int32       `json:"cetak_stnk"`
	CetakTnkb          int32       `json:"cetak_tnkb"`
}

func (q *Queries) CreateKendaraanPajak(ctx context.Context, arg CreateKendaraanPajakParams) (string, error) {
	row := q.db.QueryRow(ctx, createKendaraanPajak,
		arg.PlatNomor,
		arg.PlatNomorDisplay,
		arg.NomorRangka,
		arg.StatusAktif,
		arg.Merk,
		arg.Tipe,
		arg.Warna,
		arg.TahunBuat,
		arg.Model,
		arg.MasaPajak,
		arg.PkbPokok,
		arg.OpsenPkb,
		arg.Swdkllj,
		arg.ParkirBerlangganan,
		arg.CetakStnk,
		arg.CetakTnkb,
	)
	var plat_nomor string
	err := row.Scan(&plat_nomor)
	return plat_nomor, err
}

const createMasterNjkb = `-- name: CreateMasterNjkb :one
INSERT INTO master_njkb (
    jenis_kendaraan, merk, model, tipe, tahun, nilai_jual
) VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id
`

type CreateMasterNjkbParams struct {
	JenisKendaraan string `json:"jenis_kendaraan"`
	Merk           string `json:"merk"`
	Model          string `json:"model"`
	Tipe           string `json:"tipe"`
	Tahun          int16  `json:"tahun"`
	NilaiJual      int64  `json:"nilai_jual"`
}

func (q *Queries) CreateMasterNjkb(ctx context.Context, arg CreateMasterNjkbParams) (int32, error) {
	row := q.db.QueryRow(ctx, createMasterNjkb,
		arg.JenisKendaraan,
		arg.Merk,
		arg.Model,
		arg.Tipe,
		arg.Tahun,
		arg.NilaiJual,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const deleteKendaraanPajak = `-- name: DeleteKendaraanPajak :exec
DELETE FROM kendaraan_pajak WHERE plat_nomor = $1
`

func (q *Queries) DeleteKendaraanPajak(ctx context.Context, platNomor string) error {
	_, err := q.db.Exec(ctx, deleteKendaraanPajak, platNomor)
	return err
}

const deleteMasterNjkb = `-- name: DeleteMasterNjkb :exec
DELETE FROM master_njkb WHERE id = $1
`

func (q *Queries) DeleteMasterNjkb(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteMasterNjkb, id)
	return err
}

const getAllKendaraanPajakAdmin = `-- name: GetAllKendaraanPajakAdmin :many
SELECT plat_nomor, plat_nomor_display, nomor_rangka, merk, tipe, tahun_buat, status_aktif, masa_pajak 
FROM kendaraan_pajak 
ORDER BY created_at DESC 
LIMIT $2 OFFSET $1
`

type GetAllKendaraanPajakAdminParams struct {
	OffsetData int32 `json:"offset_data"`
	LimitData  int32 `json:"limit_data"`
}

type GetAllKendaraanPajakAdminRow struct {
	PlatNomor        string      `json:"plat_nomor"`
	PlatNomorDisplay string      `json:"plat_nomor_display"`
	NomorRangka      string      `json:"nomor_rangka"`
	Merk             string      `json:"merk"`
	Tipe             string      `json:"tipe"`
	TahunBuat        int16       `json:"tahun_buat"`
	StatusAktif      bool        `json:"status_aktif"`
	MasaPajak        pgtype.Date `json:"masa_pajak"`
}

func (q *Queries) GetAllKendaraanPajakAdmin(ctx context.Context, arg GetAllKendaraanPajakAdminParams) ([]GetAllKendaraanPajakAdminRow, error) {
	rows, err := q.db.Query(ctx, getAllKendaraanPajakAdmin, arg.OffsetData, arg.LimitData)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllKendaraanPajakAdminRow
	for rows.Next() {
		var i GetAllKendaraanPajakAdminRow
		if err := rows.Scan(
			&i.PlatNomor,
			&i.PlatNomorDisplay,
			&i.NomorRangka,
			&i.Merk,
			&i.Tipe,
			&i.TahunBuat,
			&i.StatusAktif,
			&i.MasaPajak,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllMasterNjkbAdmin = `-- name: GetAllMasterNjkbAdmin :many
SELECT id, jenis_kendaraan, merk, model, tipe, tahun, nilai_jual, created_at FROM master_njkb 
ORDER BY merk, tahun DESC 
LIMIT $2 OFFSET $1
`

type GetAllMasterNjkbAdminParams struct {
	OffsetData int32 `json:"offset_data"`
	LimitData  int32 `json:"limit_data"`
}

func (q *Queries) GetAllMasterNjkbAdmin(ctx context.Context, arg GetAllMasterNjkbAdminParams) ([]MasterNjkb, error) {
	rows, err := q.db.Query(ctx, getAllMasterNjkbAdmin, arg.OffsetData, arg.LimitData)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MasterNjkb
	for rows.Next() {
		var i MasterNjkb
		if err := rows.Scan(
			&i.ID,
			&i.JenisKendaraan,
			&i.Merk,
			&i.Model,
			&i.Tipe,
			&i.Tahun,
			&i.NilaiJual,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllTarifPKB = `-- name: GetAllTarifPKB :many
SELECT jenis_plat, label, tarif_pkb_persen, opsen_pkb_persen,
       bbn1_persen, opsen_bbn1_persen, bbn2_persen
FROM tarif_pkb
ORDER BY id
`

type GetAllTarifPKBRow struct {
	JenisPlat       string         `json:"jenis_plat"`
	Label           string         `json:"label"`
	TarifPkbPersen  pgtype.Numeric `json:"tarif_pkb_persen"`
	OpsenPkbPersen  pgtype.Numeric `json:"opsen_pkb_persen"`
	Bbn1Persen      pgtype.Numeric `json:"bbn1_persen"`
	OpsenBbn1Persen pgtype.Numeric `json:"opsen_bbn1_persen"`
	Bbn2Persen      pgtype.Numeric `json:"bbn2_persen"`
}

func (q *Queries) GetAllTarifPKB(ctx context.Context) ([]GetAllTarifPKBRow, error) {
	rows, err := q.db.Query(ctx, getAllTarifPKB)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllTarifPKBRow
	for rows.Next() {
		var i GetAllTarifPKBRow
		if err := rows.Scan(
			&i.JenisPlat,
			&i.Label,
			&i.TarifPkbPersen,
			&i.OpsenPkbPersen,
			&i.Bbn1Persen,
			&i.OpsenBbn1Persen,
			&i.Bbn2Persen,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDistinctJenis = `-- name: GetDistinctJenis :many
SELECT DISTINCT jenis_kendaraan FROM master_njkb ORDER BY jenis_kendaraan ASC
`

func (q *Queries) GetDistinctJenis(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, getDistinctJenis)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var jenis_kendaraan string
		if err := rows.Scan(&jenis_kendaraan); err != nil {
			return nil, err
		}
		items = append(items, jenis_kendaraan)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDistinctMerk = `-- name: GetDistinctMerk :many
SELECT DISTINCT merk FROM master_njkb WHERE jenis_kendaraan = $1 ORDER BY merk ASC
`

func (q *Queries) GetDistinctMerk(ctx context.Context, jenisKendaraan string) ([]string, error) {
	rows, err := q.db.Query(ctx, getDistinctMerk, jenisKendaraan)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var merk string
		if err := rows.Scan(&merk); err != nil {
			return nil, err
		}
		items = append(items, merk)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDistinctModel = `-- name: GetDistinctModel :many
SELECT DISTINCT model FROM master_njkb WHERE jenis_kendaraan = $1 AND merk = $2 ORDER BY model ASC
`

type GetDistinctModelParams struct {
	JenisKendaraan string `json:"jenis_kendaraan"`
	Merk           string `json:"merk"`
}

func (q *Queries) GetDistinctModel(ctx context.Context, arg GetDistinctModelParams) ([]string, error) {
	rows, err := q.db.Query(ctx, getDistinctModel, arg.JenisKendaraan, arg.Merk)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var model string
		if err := rows.Scan(&model); err != nil {
			return nil, err
		}
		items = append(items, model)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDistinctTahun = `-- name: GetDistinctTahun :many
SELECT DISTINCT tahun FROM master_njkb WHERE jenis_kendaraan = $1 AND merk = $2 AND model = $3 AND tipe = $4 ORDER BY tahun DESC
`

type GetDistinctTahunParams struct {
	JenisKendaraan string `json:"jenis_kendaraan"`
	Merk           string `json:"merk"`
	Model          string `json:"model"`
	Tipe           string `json:"tipe"`
}

func (q *Queries) GetDistinctTahun(ctx context.Context, arg GetDistinctTahunParams) ([]int16, error) {
	rows, err := q.db.Query(ctx, getDistinctTahun,
		arg.JenisKendaraan,
		arg.Merk,
		arg.Model,
		arg.Tipe,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int16
	for rows.Next() {
		var tahun int16
		if err := rows.Scan(&tahun); err != nil {
			return nil, err
		}
		items = append(items, tahun)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDistinctTipe = `-- name: GetDistinctTipe :many
SELECT DISTINCT tipe FROM master_njkb WHERE jenis_kendaraan = $1 AND merk = $2 AND model = $3 ORDER BY tipe ASC
`

type GetDistinctTipeParams struct {
	JenisKendaraan string `json:"jenis_kendaraan"`
	Merk           string `json:"merk"`
	Model          string `json:"model"`
}

func (q *Queries) GetDistinctTipe(ctx context.Context, arg GetDistinctTipeParams) ([]string, error) {
	rows, err := q.db.Query(ctx, getDistinctTipe, arg.JenisKendaraan, arg.Merk, arg.Model)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var tipe string
		if err := rows.Scan(&tipe); err != nil {
			return nil, err
		}
		items = append(items, tipe)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getKendaraanByPlatDanRangka = `-- name: GetKendaraanByPlatDanRangka :one
SELECT
    plat_nomor_display, status_aktif, merk, tipe, warna, tahun_buat, model, masa_pajak,
    pkb_pokok, opsen_pkb, swdkllj, parkir_berlangganan, total_pajak_tahunan, cetak_stnk, cetak_tnkb
FROM kendaraan_pajak
WHERE plat_nomor = UPPER(REPLACE($1::text, ' ', ''))
AND RIGHT(nomor_rangka, 5) = UPPER($2::text)
`

type GetKendaraanByPlatDanRangkaParams struct {
	PlatNomor       string `json:"plat_nomor"`
	LimaDigitRangka string `json:"lima_digit_rangka"`
}

type GetKendaraanByPlatDanRangkaRow struct {
	PlatNomorDisplay   string      `json:"plat_nomor_display"`
	StatusAktif        bool        `json:"status_aktif"`
	Merk               string      `json:"merk"`
	Tipe               string      `json:"tipe"`
	Warna              string      `json:"warna"`
	TahunBuat          int16       `json:"tahun_buat"`
	Model              string      `json:"model"`
	MasaPajak          pgtype.Date `json:"masa_pajak"`
	PkbPokok           int32       `json:"pkb_pokok"`
	OpsenPkb           int32       `json:"opsen_pkb"`
	Swdkllj            int32       `json:"swdkllj"`
	ParkirBerlangganan int32       `json:"parkir_berlangganan"`
	TotalPajakTahunan  pgtype.Int4 `json:"total_pajak_tahunan"`
	CetakStnk          int32       `json:"cetak_stnk"`
	CetakTnkb          int32       `json:"cetak_tnkb"`
}

func (q *Queries) GetKendaraanByPlatDanRangka(ctx context.Context, arg GetKendaraanByPlatDanRangkaParams) (GetKendaraanByPlatDanRangkaRow, error) {
	row := q.db.QueryRow(ctx, getKendaraanByPlatDanRangka, arg.PlatNomor, arg.LimaDigitRangka)
	var i GetKendaraanByPlatDanRangkaRow
	err := row.Scan(
		&i.PlatNomorDisplay,
		&i.StatusAktif,
		&i.Merk,
		&i.Tipe,
		&i.Warna,
		&i.TahunBuat,
		&i.Model,
		&i.MasaPajak,
		&i.PkbPokok,
		&i.OpsenPkb,
		&i.Swdkllj,
		&i.ParkirBerlangganan,
		&i.TotalPajakTahunan,
		&i.CetakStnk,
		&i.CetakTnkb,
	)
	return i, err
}

const getKendaraanPajakByPlatAdmin = `-- name: GetKendaraanPajakByPlatAdmin :one
SELECT plat_nomor, plat_nomor_display, nomor_rangka, status_aktif, merk, tipe, warna, tahun_buat, model, masa_pajak, pkb_pokok, opsen_pkb, swdkllj, parkir_berlangganan, cetak_stnk, cetak_tnkb, created_at, updated_at, total_pajak_tahunan FROM kendaraan_pajak 
WHERE plat_nomor = UPPER(REPLACE($1::text, ' ', ''))
`

func (q *Queries) GetKendaraanPajakByPlatAdmin(ctx context.Context, platNomor string) (KendaraanPajak, error) {
	row := q.db.QueryRow(ctx, getKendaraanPajakByPlatAdmin, platNomor)
	var i KendaraanPajak
	err := row.Scan(
		&i.PlatNomor,
		&i.PlatNomorDisplay,
		&i.NomorRangka,
		&i.StatusAktif,
		&i.Merk,
		&i.Tipe,
		&i.Warna,
		&i.TahunBuat,
		&i.Model,
		&i.MasaPajak,
		&i.PkbPokok,
		&i.OpsenPkb,
		&i.Swdkllj,
		&i.ParkirBerlangganan,
		&i.CetakStnk,
		&i.CetakTnkb,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TotalPajakTahunan,
	)
	return i, err
}

const getMasterNjkbById = `-- name: GetMasterNjkbById :one
SELECT id, jenis_kendaraan, merk, model, tipe, tahun, nilai_jual, created_at FROM master_njkb 
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetMasterNjkbById(ctx context.Context, id int32) (MasterNjkb, error) {
	row := q.db.QueryRow(ctx, getMasterNjkbById, id)
	var i MasterNjkb
	err := row.Scan(
		&i.ID,
		&i.JenisKendaraan,
		&i.Merk,
		&i.Model,
		&i.Tipe,
		&i.Tahun,
		&i.NilaiJual,
		&i.CreatedAt,
	)
	return i, err
}

const getNilaiJual = `-- name: GetNilaiJual :one
SELECT id, nilai_jual
FROM master_njkb
WHERE jenis_kendaraan = $1 
  AND merk = $2 
  AND model = $3 
  AND tipe = $4 
  AND tahun = $5
LIMIT 1
`

type GetNilaiJualParams struct {
	Jenis string `json:"jenis"`
	Merk  string `json:"merk"`
	Model string `json:"model"`
	Tipe  string `json:"tipe"`
	Tahun int16  `json:"tahun"`
}

type GetNilaiJualRow struct {
	ID        int32 `json:"id"`
	NilaiJual int64 `json:"nilai_jual"`
}

func (q *Queries) GetNilaiJual(ctx context.Context, arg GetNilaiJualParams) (GetNilaiJualRow, error) {
	row := q.db.QueryRow(ctx, getNilaiJual,
		arg.Jenis,
		arg.Merk,
		arg.Model,
		arg.Tipe,
		arg.Tahun,
	)
	var i GetNilaiJualRow
	err := row.Scan(&i.ID, &i.NilaiJual)
	return i, err
}

const updateKendaraanPajak = `-- name: UpdateKendaraanPajak :exec
UPDATE kendaraan_pajak SET
    nomor_rangka        = $1,
    status_aktif        = $2,
    merk                = $3,
    tipe                = $4,
    warna               = $5,
    tahun_buat          = $6,
    model               = $7,
    masa_pajak          = $8,
    pkb_pokok           = $9,
    opsen_pkb           = $10,
    swdkllj             = $11,
    parkir_berlangganan = $12,
    cetak_stnk          = $13,
    cetak_tnkb          = $14,
    updated_at          = CURRENT_TIMESTAMP
WHERE plat_nomor = UPPER(REPLACE($15::text, ' ', ''))
`

type UpdateKendaraanPajakParams struct {
	NomorRangka        string      `json:"nomor_rangka"`
	StatusAktif        bool        `json:"status_aktif"`
	Merk               string      `json:"merk"`
	Tipe               string      `json:"tipe"`
	Warna              string      `json:"warna"`
	TahunBuat          int16       `json:"tahun_buat"`
	Model              string      `json:"model"`
	MasaPajak          pgtype.Date `json:"masa_pajak"`
	PkbPokok           int32       `json:"pkb_pokok"`
	OpsenPkb           int32       `json:"opsen_pkb"`
	Swdkllj            int32       `json:"swdkllj"`
	ParkirBerlangganan int32       `json:"parkir_berlangganan"`
	CetakStnk          int32       `json:"cetak_stnk"`
	CetakTnkb          int32       `json:"cetak_tnkb"`
	PlatNomorKey       string      `json:"plat_nomor_key"`
}

func (q *Queries) UpdateKendaraanPajak(ctx context.Context, arg UpdateKendaraanPajakParams) error {
	_, err := q.db.Exec(ctx, updateKendaraanPajak,
		arg.NomorRangka,
		arg.StatusAktif,
		arg.Merk,
		arg.Tipe,
		arg.Warna,
		arg.TahunBuat,
		arg.Model,
		arg.MasaPajak,
		arg.PkbPokok,
		arg.OpsenPkb,
		arg.Swdkllj,
		arg.ParkirBerlangganan,
		arg.CetakStnk,
		arg.CetakTnkb,
		arg.PlatNomorKey,
	)
	return err
}

const updateMasterNjkb = `-- name: UpdateMasterNjkb :exec
UPDATE master_njkb SET
    jenis_kendaraan = $2,
    merk            = $3,
    model           = $4,
    tipe            = $5,
    tahun           = $6,
    nilai_jual      = $7
WHERE id = $1
`

type UpdateMasterNjkbParams struct {
	ID             int32  `json:"id"`
	JenisKendaraan string `json:"jenis_kendaraan"`
	Merk           string `json:"merk"`
	Model          string `json:"model"`
	Tipe           string `json:"tipe"`
	Tahun          int16  `json:"tahun"`
	NilaiJual      int64  `json:"nilai_jual"`
}

func (q *Queries) UpdateMasterNjkb(ctx context.Context, arg UpdateMasterNjkbParams) error {
	_, err := q.db.Exec(ctx, updateMasterNjkb,
		arg.ID,
		arg.JenisKendaraan,
		arg.Merk,
		arg.Model,
		arg.Tipe,
		arg.Tahun,
		arg.NilaiJual,
	)
	return err
}
