// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type LayananType string

const (
	LayananTypeReguler LayananType = "reguler"
	LayananTypeLuxury  LayananType = "luxury"
)

func (e *LayananType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = LayananType(s)
	case string:
		*e = LayananType(s)
	default:
		return fmt.Errorf("unsupported scan type for LayananType: %T", src)
	}
	return nil
}

type NullLayananType struct {
	LayananType LayananType `json:"layanan_type"`
	Valid       bool        `json:"valid"` // Valid is true if LayananType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullLayananType) Scan(value interface{}) error {
	if value == nil {
		ns.LayananType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.LayananType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullLayananType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.LayananType), nil
}

type TipePenumpangType string

const (
	TipePenumpangTypeUmum          TipePenumpangType = "umum"
	TipePenumpangTypePelajarSantri TipePenumpangType = "pelajar_santri"
	TipePenumpangTypeMahasiswa     TipePenumpangType = "mahasiswa"
)

func (e *TipePenumpangType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TipePenumpangType(s)
	case string:
		*e = TipePenumpangType(s)
	default:
		return fmt.Errorf("unsupported scan type for TipePenumpangType: %T", src)
	}
	return nil
}

type NullTipePenumpangType struct {
	TipePenumpangType TipePenumpangType `json:"tipe_penumpang_type"`
	Valid             bool              `json:"valid"` // Valid is true if TipePenumpangType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTipePenumpangType) Scan(value interface{}) error {
	if value == nil {
		ns.TipePenumpangType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TipePenumpangType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTipePenumpangType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TipePenumpangType), nil
}

type Bus struct {
	ID        int32              `json:"id"`
	Kode      string             `json:"kode"`
	Layanan   LayananType        `json:"layanan"`
	Fasilitas pgtype.Text        `json:"fasilitas"`
	Kapasitas pgtype.Int4        `json:"kapasitas"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Harga struct {
	ID            int32                 `json:"id"`
	RuteID        int32                 `json:"rute_id"`
	Layanan       LayananType           `json:"layanan"`
	TipePenumpang NullTipePenumpangType `json:"tipe_penumpang"`
	Harga         int32                 `json:"harga"`
	CreatedAt     pgtype.Timestamptz    `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz    `json:"updated_at"`
}

type Jadwal struct {
	ID           int32              `json:"id"`
	RuteID       int32              `json:"rute_id"`
	BusID        int32              `json:"bus_id"`
	JamBerangkat pgtype.Time        `json:"jam_berangkat"`
	JamTiba      pgtype.Time        `json:"jam_tiba"`
	HariOperasi  int16              `json:"hari_operasi"`
	Aktif        bool               `json:"aktif"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type JadwalLibur struct {
	ID         int32              `json:"id"`
	JadwalID   pgtype.Int4        `json:"jadwal_id"`
	Tanggal    pgtype.Date        `json:"tanggal"`
	Keterangan pgtype.Text        `json:"keterangan"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Rute struct {
	ID               int32              `json:"id"`
	TerminalAsalID   int32              `json:"terminal_asal_id"`
	TerminalTujuanID int32              `json:"terminal_tujuan_id"`
	Slug             string             `json:"slug"`
	DurasiMenit      int32              `json:"durasi_menit"`
	Aktif            bool               `json:"aktif"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type RuteStop struct {
	ID         int32 `json:"id"`
	RuteID     int32 `json:"rute_id"`
	TerminalID int32 `json:"terminal_id"`
	Urutan     int32 `json:"urutan"`
}

type Terminal struct {
	ID        int32              `json:"id"`
	Nama      string             `json:"nama"`
	Kota      string             `json:"kota"`
	Slug      string             `json:"slug"`
	Lat       pgtype.Float8      `json:"lat"`
	Lng       pgtype.Float8      `json:"lng"`
	Aktif     bool               `json:"aktif"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}
