// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAllTerminals = `-- name: CountAllTerminals :one
SELECT COUNT(id) 
FROM terminal
WHERE ($1::text IS NULL OR kota = $1::text)
`

func (q *Queries) CountAllTerminals(ctx context.Context, kotaFilter pgtype.Text) (int64, error) {
	row := q.db.QueryRow(ctx, countAllTerminals, kotaFilter)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countBuses = `-- name: CountBuses :one
SELECT COUNT(id) FROM bus
`

func (q *Queries) CountBuses(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countBuses)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countHarga = `-- name: CountHarga :one
SELECT COUNT(id) FROM harga
`

func (q *Queries) CountHarga(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countHarga)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countJadwal = `-- name: CountJadwal :one
SELECT COUNT(id) FROM jadwal
`

func (q *Queries) CountJadwal(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countJadwal)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRutes = `-- name: CountRutes :one
SELECT COUNT(id) FROM rute
`

func (q *Queries) CountRutes(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countRutes)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createBus = `-- name: CreateBus :one
INSERT INTO bus (kode, layanan, fasilitas, kapasitas)
VALUES (
    $1, $2, $3, $4
)
RETURNING id
`

type CreateBusParams struct {
	Kode      string      `json:"kode"`
	Layanan   LayananType `json:"layanan"`
	Fasilitas pgtype.Text `json:"fasilitas"`
	Kapasitas pgtype.Int4 `json:"kapasitas"`
}

func (q *Queries) CreateBus(ctx context.Context, arg CreateBusParams) (int32, error) {
	row := q.db.QueryRow(ctx, createBus,
		arg.Kode,
		arg.Layanan,
		arg.Fasilitas,
		arg.Kapasitas,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const createHarga = `-- name: CreateHarga :one
INSERT INTO harga (rute_id, layanan, tipe_penumpang, harga)
VALUES (
    $1, $2, 
    $3::tipe_penumpang_type, $4
)
RETURNING id
`

type CreateHargaParams struct {
	RuteID        int32                 `json:"rute_id"`
	Layanan       LayananType           `json:"layanan"`
	TipePenumpang NullTipePenumpangType `json:"tipe_penumpang"`
	Harga         int32                 `json:"harga"`
}

func (q *Queries) CreateHarga(ctx context.Context, arg CreateHargaParams) (int32, error) {
	row := q.db.QueryRow(ctx, createHarga,
		arg.RuteID,
		arg.Layanan,
		arg.TipePenumpang,
		arg.Harga,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const createJadwal = `-- name: CreateJadwal :one
INSERT INTO jadwal (rute_id, bus_id, jam_berangkat, jam_tiba, hari_operasi)
VALUES (
    $1, $2, 
    $3, $4, $5
)
RETURNING id
`

type CreateJadwalParams struct {
	RuteID       int32       `json:"rute_id"`
	BusID        int32       `json:"bus_id"`
	JamBerangkat pgtype.Time `json:"jam_berangkat"`
	JamTiba      pgtype.Time `json:"jam_tiba"`
	HariOperasi  int16       `json:"hari_operasi"`
}

func (q *Queries) CreateJadwal(ctx context.Context, arg CreateJadwalParams) (int32, error) {
	row := q.db.QueryRow(ctx, createJadwal,
		arg.RuteID,
		arg.BusID,
		arg.JamBerangkat,
		arg.JamTiba,
		arg.HariOperasi,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const createJadwalLibur = `-- name: CreateJadwalLibur :one
INSERT INTO jadwal_libur (jadwal_id, tanggal, keterangan)
VALUES ($1, $2, $3)
RETURNING id
`

type CreateJadwalLiburParams struct {
	JadwalID   pgtype.Int4 `json:"jadwal_id"`
	Tanggal    pgtype.Date `json:"tanggal"`
	Keterangan pgtype.Text `json:"keterangan"`
}

func (q *Queries) CreateJadwalLibur(ctx context.Context, arg CreateJadwalLiburParams) (int32, error) {
	row := q.db.QueryRow(ctx, createJadwalLibur, arg.JadwalID, arg.Tanggal, arg.Keterangan)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const createRute = `-- name: CreateRute :one
INSERT INTO rute (terminal_asal_id, terminal_tujuan_id, slug, durasi_menit)
VALUES (
    $1, $2, 
    $3, $4
)
RETURNING id, slug
`

type CreateRuteParams struct {
	TerminalAsalID   int32  `json:"terminal_asal_id"`
	TerminalTujuanID int32  `json:"terminal_tujuan_id"`
	Slug             string `json:"slug"`
	DurasiMenit      int32  `json:"durasi_menit"`
}

type CreateRuteRow struct {
	ID   int32  `json:"id"`
	Slug string `json:"slug"`
}

func (q *Queries) CreateRute(ctx context.Context, arg CreateRuteParams) (CreateRuteRow, error) {
	row := q.db.QueryRow(ctx, createRute,
		arg.TerminalAsalID,
		arg.TerminalTujuanID,
		arg.Slug,
		arg.DurasiMenit,
	)
	var i CreateRuteRow
	err := row.Scan(&i.ID, &i.Slug)
	return i, err
}

const createTerminal = `-- name: CreateTerminal :one
INSERT INTO terminal (nama, kota, slug, lat, lng)
VALUES (
    $1, $2, $3, 
    $4, $5
)
RETURNING id, slug
`

type CreateTerminalParams struct {
	Nama string        `json:"nama"`
	Kota string        `json:"kota"`
	Slug string        `json:"slug"`
	Lat  pgtype.Float8 `json:"lat"`
	Lng  pgtype.Float8 `json:"lng"`
}

type CreateTerminalRow struct {
	ID   int32  `json:"id"`
	Slug string `json:"slug"`
}

func (q *Queries) CreateTerminal(ctx context.Context, arg CreateTerminalParams) (CreateTerminalRow, error) {
	row := q.db.QueryRow(ctx, createTerminal,
		arg.Nama,
		arg.Kota,
		arg.Slug,
		arg.Lat,
		arg.Lng,
	)
	var i CreateTerminalRow
	err := row.Scan(&i.ID, &i.Slug)
	return i, err
}

const deactivateRute = `-- name: DeactivateRute :exec
UPDATE rute 
SET aktif = false, updated_at = CURRENT_TIMESTAMP 
WHERE slug = $1
`

func (q *Queries) DeactivateRute(ctx context.Context, slug string) error {
	_, err := q.db.Exec(ctx, deactivateRute, slug)
	return err
}

const deactivateTerminal = `-- name: DeactivateTerminal :exec
UPDATE terminal 
SET aktif = false, updated_at = CURRENT_TIMESTAMP 
WHERE slug = $1
`

func (q *Queries) DeactivateTerminal(ctx context.Context, slug string) error {
	_, err := q.db.Exec(ctx, deactivateTerminal, slug)
	return err
}

const deleteBus = `-- name: DeleteBus :exec
DELETE FROM bus WHERE id = $1
`

func (q *Queries) DeleteBus(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteBus, id)
	return err
}

const deleteHarga = `-- name: DeleteHarga :exec
DELETE FROM harga WHERE id = $1
`

func (q *Queries) DeleteHarga(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteHarga, id)
	return err
}

const deleteJadwal = `-- name: DeleteJadwal :exec
DELETE FROM jadwal WHERE id = $1
`

func (q *Queries) DeleteJadwal(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteJadwal, id)
	return err
}

const deleteJadwalLibur = `-- name: DeleteJadwalLibur :exec
DELETE FROM jadwal_libur WHERE id = $1
`

func (q *Queries) DeleteJadwalLibur(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteJadwalLibur, id)
	return err
}

const deleteRuteStops = `-- name: DeleteRuteStops :exec
DELETE FROM rute_stop WHERE rute_id = $1
`

func (q *Queries) DeleteRuteStops(ctx context.Context, ruteID int32) error {
	_, err := q.db.Exec(ctx, deleteRuteStops, ruteID)
	return err
}

const getAllHargaInfo = `-- name: GetAllHargaInfo :many
SELECT h.id, h.rute_id, h.layanan, h.tipe_penumpang, h.harga,
       ta.nama AS terminal_asal_nama,  ta.kota AS kota_asal,
       tt.nama AS terminal_tujuan_nama, tt.kota AS kota_tujuan
FROM harga h
JOIN rute r      ON r.id  = h.rute_id
JOIN terminal ta ON ta.id = r.terminal_asal_id
JOIN terminal tt ON tt.id = r.terminal_tujuan_id
WHERE r.aktif = true
ORDER BY h.layanan, r.id, h.tipe_penumpang
`

type GetAllHargaInfoRow struct {
	ID                 int32                 `json:"id"`
	RuteID             int32                 `json:"rute_id"`
	Layanan            LayananType           `json:"layanan"`
	TipePenumpang      NullTipePenumpangType `json:"tipe_penumpang"`
	Harga              int32                 `json:"harga"`
	TerminalAsalNama   string                `json:"terminal_asal_nama"`
	KotaAsal           string                `json:"kota_asal"`
	TerminalTujuanNama string                `json:"terminal_tujuan_nama"`
	KotaTujuan         string                `json:"kota_tujuan"`
}

func (q *Queries) GetAllHargaInfo(ctx context.Context) ([]GetAllHargaInfoRow, error) {
	rows, err := q.db.Query(ctx, getAllHargaInfo)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllHargaInfoRow
	for rows.Next() {
		var i GetAllHargaInfoRow
		if err := rows.Scan(
			&i.ID,
			&i.RuteID,
			&i.Layanan,
			&i.TipePenumpang,
			&i.Harga,
			&i.TerminalAsalNama,
			&i.KotaAsal,
			&i.TerminalTujuanNama,
			&i.KotaTujuan,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBusByID = `-- name: GetBusByID :one
SELECT id, kode, layanan, fasilitas, kapasitas
FROM bus
WHERE id = $1
LIMIT 1
`

type GetBusByIDRow struct {
	ID        int32       `json:"id"`
	Kode      string      `json:"kode"`
	Layanan   LayananType `json:"layanan"`
	Fasilitas pgtype.Text `json:"fasilitas"`
	Kapasitas pgtype.Int4 `json:"kapasitas"`
}

func (q *Queries) GetBusByID(ctx context.Context, id int32) (GetBusByIDRow, error) {
	row := q.db.QueryRow(ctx, getBusByID, id)
	var i GetBusByIDRow
	err := row.Scan(
		&i.ID,
		&i.Kode,
		&i.Layanan,
		&i.Fasilitas,
		&i.Kapasitas,
	)
	return i, err
}

const getDistinctKotaTerminal = `-- name: GetDistinctKotaTerminal :many
SELECT DISTINCT kota FROM terminal ORDER BY kota ASC
`

func (q *Queries) GetDistinctKotaTerminal(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, getDistinctKotaTerminal)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var kota string
		if err := rows.Scan(&kota); err != nil {
			return nil, err
		}
		items = append(items, kota)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDistinctLayananBus = `-- name: GetDistinctLayananBus :many
SELECT DISTINCT layanan FROM bus ORDER BY layanan ASC
`

func (q *Queries) GetDistinctLayananBus(ctx context.Context) ([]LayananType, error) {
	rows, err := q.db.Query(ctx, getDistinctLayananBus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LayananType
	for rows.Next() {
		var layanan LayananType
		if err := rows.Scan(&layanan); err != nil {
			return nil, err
		}
		items = append(items, layanan)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getHargaByRute = `-- name: GetHargaByRute :many

SELECT id, layanan, tipe_penumpang, harga
FROM harga
WHERE rute_id = $1
ORDER BY layanan, tipe_penumpang
`

type GetHargaByRuteRow struct {
	ID            int32                 `json:"id"`
	Layanan       LayananType           `json:"layanan"`
	TipePenumpang NullTipePenumpangType `json:"tipe_penumpang"`
	Harga         int32                 `json:"harga"`
}

// =====================================================================
// HARGA
// =====================================================================
func (q *Queries) GetHargaByRute(ctx context.Context, ruteID int32) ([]GetHargaByRuteRow, error) {
	rows, err := q.db.Query(ctx, getHargaByRute, ruteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetHargaByRuteRow
	for rows.Next() {
		var i GetHargaByRuteRow
		if err := rows.Scan(
			&i.ID,
			&i.Layanan,
			&i.TipePenumpang,
			&i.Harga,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getJadwalByID = `-- name: GetJadwalByID :one
SELECT
    j.id, j.jam_berangkat, j.jam_tiba, j.hari_operasi, j.aktif,
    b.kode      AS bus_kode,
    b.layanan   AS bus_layanan,
    b.fasilitas AS bus_fasilitas,
    r.id   AS rute_id,
    r.slug AS rute_slug,
    r.durasi_menit,
    ta.nama AS terminal_asal_nama,
    tt.nama AS terminal_tujuan_nama
FROM jadwal j
JOIN bus b       ON b.id  = j.bus_id
JOIN rute r      ON r.id  = j.rute_id
JOIN terminal ta ON ta.id = r.terminal_asal_id
JOIN terminal tt ON tt.id = r.terminal_tujuan_id
WHERE j.id = $1
LIMIT 1
`

type GetJadwalByIDRow struct {
	ID                 int32       `json:"id"`
	JamBerangkat       pgtype.Time `json:"jam_berangkat"`
	JamTiba            pgtype.Time `json:"jam_tiba"`
	HariOperasi        int16       `json:"hari_operasi"`
	Aktif              bool        `json:"aktif"`
	BusKode            string      `json:"bus_kode"`
	BusLayanan         LayananType `json:"bus_layanan"`
	BusFasilitas       pgtype.Text `json:"bus_fasilitas"`
	RuteID             int32       `json:"rute_id"`
	RuteSlug           string      `json:"rute_slug"`
	DurasiMenit        int32       `json:"durasi_menit"`
	TerminalAsalNama   string      `json:"terminal_asal_nama"`
	TerminalTujuanNama string      `json:"terminal_tujuan_nama"`
}

func (q *Queries) GetJadwalByID(ctx context.Context, id int32) (GetJadwalByIDRow, error) {
	row := q.db.QueryRow(ctx, getJadwalByID, id)
	var i GetJadwalByIDRow
	err := row.Scan(
		&i.ID,
		&i.JamBerangkat,
		&i.JamTiba,
		&i.HariOperasi,
		&i.Aktif,
		&i.BusKode,
		&i.BusLayanan,
		&i.BusFasilitas,
		&i.RuteID,
		&i.RuteSlug,
		&i.DurasiMenit,
		&i.TerminalAsalNama,
		&i.TerminalTujuanNama,
	)
	return i, err
}

const getRuteByID = `-- name: GetRuteByID :one
SELECT r.id, r.slug, r.terminal_asal_id, r.terminal_tujuan_id, r.durasi_menit, r.aktif,
       ta.nama AS terminal_asal_nama,  ta.kota AS kota_asal,
       tt.nama AS terminal_tujuan_nama, tt.kota AS kota_tujuan
FROM rute r
JOIN terminal ta ON ta.id = r.terminal_asal_id
JOIN terminal tt ON tt.id = r.terminal_tujuan_id
WHERE r.id = $1
LIMIT 1
`

type GetRuteByIDRow struct {
	ID                 int32  `json:"id"`
	Slug               string `json:"slug"`
	TerminalAsalID     int32  `json:"terminal_asal_id"`
	TerminalTujuanID   int32  `json:"terminal_tujuan_id"`
	DurasiMenit        int32  `json:"durasi_menit"`
	Aktif              bool   `json:"aktif"`
	TerminalAsalNama   string `json:"terminal_asal_nama"`
	KotaAsal           string `json:"kota_asal"`
	TerminalTujuanNama string `json:"terminal_tujuan_nama"`
	KotaTujuan         string `json:"kota_tujuan"`
}

func (q *Queries) GetRuteByID(ctx context.Context, id int32) (GetRuteByIDRow, error) {
	row := q.db.QueryRow(ctx, getRuteByID, id)
	var i GetRuteByIDRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.TerminalAsalID,
		&i.TerminalTujuanID,
		&i.DurasiMenit,
		&i.Aktif,
		&i.TerminalAsalNama,
		&i.KotaAsal,
		&i.TerminalTujuanNama,
		&i.KotaTujuan,
	)
	return i, err
}

const getRuteBySlug = `-- name: GetRuteBySlug :one
SELECT r.id, r.slug, r.terminal_asal_id, r.terminal_tujuan_id, r.durasi_menit, r.aktif,
       ta.nama AS terminal_asal_nama,  ta.kota AS kota_asal,  ta.slug AS terminal_asal_slug,
       tt.nama AS terminal_tujuan_nama, tt.kota AS kota_tujuan, tt.slug AS terminal_tujuan_slug
FROM rute r
JOIN terminal ta ON ta.id = r.terminal_asal_id
JOIN terminal tt ON tt.id = r.terminal_tujuan_id
WHERE r.slug = $1
LIMIT 1
`

type GetRuteBySlugRow struct {
	ID                 int32  `json:"id"`
	Slug               string `json:"slug"`
	TerminalAsalID     int32  `json:"terminal_asal_id"`
	TerminalTujuanID   int32  `json:"terminal_tujuan_id"`
	DurasiMenit        int32  `json:"durasi_menit"`
	Aktif              bool   `json:"aktif"`
	TerminalAsalNama   string `json:"terminal_asal_nama"`
	KotaAsal           string `json:"kota_asal"`
	TerminalAsalSlug   string `json:"terminal_asal_slug"`
	TerminalTujuanNama string `json:"terminal_tujuan_nama"`
	KotaTujuan         string `json:"kota_tujuan"`
	TerminalTujuanSlug string `json:"terminal_tujuan_slug"`
}

func (q *Queries) GetRuteBySlug(ctx context.Context, slug string) (GetRuteBySlugRow, error) {
	row := q.db.QueryRow(ctx, getRuteBySlug, slug)
	var i GetRuteBySlugRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.TerminalAsalID,
		&i.TerminalTujuanID,
		&i.DurasiMenit,
		&i.Aktif,
		&i.TerminalAsalNama,
		&i.KotaAsal,
		&i.TerminalAsalSlug,
		&i.TerminalTujuanNama,
		&i.KotaTujuan,
		&i.TerminalTujuanSlug,
	)
	return i, err
}

const getRuteStops = `-- name: GetRuteStops :many

SELECT rs.urutan, t.id AS terminal_id, t.nama, t.kota
FROM rute_stop rs
JOIN terminal t ON t.id = rs.terminal_id
WHERE rs.rute_id = $1
ORDER BY rs.urutan
`

type GetRuteStopsRow struct {
	Urutan     int32  `json:"urutan"`
	TerminalID int32  `json:"terminal_id"`
	Nama       string `json:"nama"`
	Kota       string `json:"kota"`
}

// =====================================================================
// RUTE STOP
// =====================================================================
func (q *Queries) GetRuteStops(ctx context.Context, ruteID int32) ([]GetRuteStopsRow, error) {
	rows, err := q.db.Query(ctx, getRuteStops, ruteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRuteStopsRow
	for rows.Next() {
		var i GetRuteStopsRow
		if err := rows.Scan(
			&i.Urutan,
			&i.TerminalID,
			&i.Nama,
			&i.Kota,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTerminalByID = `-- name: GetTerminalByID :one
SELECT id, nama, kota, slug, lat, lng, aktif
FROM terminal
WHERE id = $1
LIMIT 1
`

type GetTerminalByIDRow struct {
	ID    int32         `json:"id"`
	Nama  string        `json:"nama"`
	Kota  string        `json:"kota"`
	Slug  string        `json:"slug"`
	Lat   pgtype.Float8 `json:"lat"`
	Lng   pgtype.Float8 `json:"lng"`
	Aktif bool          `json:"aktif"`
}

func (q *Queries) GetTerminalByID(ctx context.Context, id int32) (GetTerminalByIDRow, error) {
	row := q.db.QueryRow(ctx, getTerminalByID, id)
	var i GetTerminalByIDRow
	err := row.Scan(
		&i.ID,
		&i.Nama,
		&i.Kota,
		&i.Slug,
		&i.Lat,
		&i.Lng,
		&i.Aktif,
	)
	return i, err
}

const getTerminalBySlug = `-- name: GetTerminalBySlug :one
SELECT id, nama, kota, slug, lat, lng, aktif
FROM terminal
WHERE slug = $1
LIMIT 1
`

type GetTerminalBySlugRow struct {
	ID    int32         `json:"id"`
	Nama  string        `json:"nama"`
	Kota  string        `json:"kota"`
	Slug  string        `json:"slug"`
	Lat   pgtype.Float8 `json:"lat"`
	Lng   pgtype.Float8 `json:"lng"`
	Aktif bool          `json:"aktif"`
}

func (q *Queries) GetTerminalBySlug(ctx context.Context, slug string) (GetTerminalBySlugRow, error) {
	row := q.db.QueryRow(ctx, getTerminalBySlug, slug)
	var i GetTerminalBySlugRow
	err := row.Scan(
		&i.ID,
		&i.Nama,
		&i.Kota,
		&i.Slug,
		&i.Lat,
		&i.Lng,
		&i.Aktif,
	)
	return i, err
}

const insertRuteStop = `-- name: InsertRuteStop :exec
INSERT INTO rute_stop (rute_id, terminal_id, urutan) 
VALUES ($1, $2, $3)
`

type InsertRuteStopParams struct {
	RuteID     int32 `json:"rute_id"`
	TerminalID int32 `json:"terminal_id"`
	Urutan     int32 `json:"urutan"`
}

func (q *Queries) InsertRuteStop(ctx context.Context, arg InsertRuteStopParams) error {
	_, err := q.db.Exec(ctx, insertRuteStop, arg.RuteID, arg.TerminalID, arg.Urutan)
	return err
}

const listActiveTerminals = `-- name: ListActiveTerminals :many

SELECT id, nama, kota, slug, lat, lng
FROM terminal
WHERE aktif = true
ORDER BY kota, nama
`

type ListActiveTerminalsRow struct {
	ID   int32         `json:"id"`
	Nama string        `json:"nama"`
	Kota string        `json:"kota"`
	Slug string        `json:"slug"`
	Lat  pgtype.Float8 `json:"lat"`
	Lng  pgtype.Float8 `json:"lng"`
}

// =====================================================================
// TERMINAL
// =====================================================================
func (q *Queries) ListActiveTerminals(ctx context.Context) ([]ListActiveTerminalsRow, error) {
	rows, err := q.db.Query(ctx, listActiveTerminals)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveTerminalsRow
	for rows.Next() {
		var i ListActiveTerminalsRow
		if err := rows.Scan(
			&i.ID,
			&i.Nama,
			&i.Kota,
			&i.Slug,
			&i.Lat,
			&i.Lng,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllTerminalsAdmin = `-- name: ListAllTerminalsAdmin :many
SELECT id, nama, kota, slug, lat, lng, aktif
FROM terminal
WHERE ($1::text IS NULL OR kota = $1::text)
ORDER BY kota, nama
LIMIT $3 OFFSET $2
`

type ListAllTerminalsAdminParams struct {
	KotaFilter pgtype.Text `json:"kota_filter"`
	OffsetData int32       `json:"offset_data"`
	LimitData  int32       `json:"limit_data"`
}

type ListAllTerminalsAdminRow struct {
	ID    int32         `json:"id"`
	Nama  string        `json:"nama"`
	Kota  string        `json:"kota"`
	Slug  string        `json:"slug"`
	Lat   pgtype.Float8 `json:"lat"`
	Lng   pgtype.Float8 `json:"lng"`
	Aktif bool          `json:"aktif"`
}

func (q *Queries) ListAllTerminalsAdmin(ctx context.Context, arg ListAllTerminalsAdminParams) ([]ListAllTerminalsAdminRow, error) {
	rows, err := q.db.Query(ctx, listAllTerminalsAdmin, arg.KotaFilter, arg.OffsetData, arg.LimitData)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllTerminalsAdminRow
	for rows.Next() {
		var i ListAllTerminalsAdminRow
		if err := rows.Scan(
			&i.ID,
			&i.Nama,
			&i.Kota,
			&i.Slug,
			&i.Lat,
			&i.Lng,
			&i.Aktif,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBusesAdmin = `-- name: ListBusesAdmin :many

SELECT id, kode, layanan, fasilitas, kapasitas
FROM bus
ORDER BY layanan, kode
LIMIT $2 OFFSET $1
`

type ListBusesAdminParams struct {
	OffsetData int32 `json:"offset_data"`
	LimitData  int32 `json:"limit_data"`
}

type ListBusesAdminRow struct {
	ID        int32       `json:"id"`
	Kode      string      `json:"kode"`
	Layanan   LayananType `json:"layanan"`
	Fasilitas pgtype.Text `json:"fasilitas"`
	Kapasitas pgtype.Int4 `json:"kapasitas"`
}

// =====================================================================
// BUS
// =====================================================================
func (q *Queries) ListBusesAdmin(ctx context.Context, arg ListBusesAdminParams) ([]ListBusesAdminRow, error) {
	rows, err := q.db.Query(ctx, listBusesAdmin, arg.OffsetData, arg.LimitData)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBusesAdminRow
	for rows.Next() {
		var i ListBusesAdminRow
		if err := rows.Scan(
			&i.ID,
			&i.Kode,
			&i.Layanan,
			&i.Fasilitas,
			&i.Kapasitas,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHargaAdmin = `-- name: ListHargaAdmin :many
SELECT h.id, h.rute_id, h.layanan, h.tipe_penumpang, h.harga,
       ta.nama AS terminal_asal_nama,
       tt.nama AS terminal_tujuan_nama
FROM harga h
JOIN rute r      ON r.id  = h.rute_id
JOIN terminal ta ON ta.id = r.terminal_asal_id
JOIN terminal tt ON tt.id = r.terminal_tujuan_id
ORDER BY r.id, h.layanan, h.tipe_penumpang
LIMIT $2 OFFSET $1
`

type ListHargaAdminParams struct {
	OffsetData int32 `json:"offset_data"`
	LimitData  int32 `json:"limit_data"`
}

type ListHargaAdminRow struct {
	ID                 int32                 `json:"id"`
	RuteID             int32                 `json:"rute_id"`
	Layanan            LayananType           `json:"layanan"`
	TipePenumpang      NullTipePenumpangType `json:"tipe_penumpang"`
	Harga              int32                 `json:"harga"`
	TerminalAsalNama   string                `json:"terminal_asal_nama"`
	TerminalTujuanNama string                `json:"terminal_tujuan_nama"`
}

func (q *Queries) ListHargaAdmin(ctx context.Context, arg ListHargaAdminParams) ([]ListHargaAdminRow, error) {
	rows, err := q.db.Query(ctx, listHargaAdmin, arg.OffsetData, arg.LimitData)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListHargaAdminRow
	for rows.Next() {
		var i ListHargaAdminRow
		if err := rows.Scan(
			&i.ID,
			&i.RuteID,
			&i.Layanan,
			&i.TipePenumpang,
			&i.Harga,
			&i.TerminalAsalNama,
			&i.TerminalTujuanNama,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJadwalAdmin = `-- name: ListJadwalAdmin :many
SELECT
    j.id, j.jam_berangkat, j.jam_tiba, j.hari_operasi, j.aktif,
    b.kode    AS bus_kode,
    b.layanan AS bus_layanan,
    ta.nama   AS terminal_asal_nama,
    tt.nama   AS terminal_tujuan_nama,
    r.slug    AS rute_slug
FROM jadwal j
JOIN bus b       ON b.id  = j.bus_id
JOIN rute r      ON r.id  = j.rute_id
JOIN terminal ta ON ta.id = r.terminal_asal_id
JOIN terminal tt ON tt.id = r.terminal_tujuan_id
ORDER BY j.id DESC
LIMIT $2 OFFSET $1
`

type ListJadwalAdminParams struct {
	OffsetData int32 `json:"offset_data"`
	LimitData  int32 `json:"limit_data"`
}

type ListJadwalAdminRow struct {
	ID                 int32       `json:"id"`
	JamBerangkat       pgtype.Time `json:"jam_berangkat"`
	JamTiba            pgtype.Time `json:"jam_tiba"`
	HariOperasi        int16       `json:"hari_operasi"`
	Aktif              bool        `json:"aktif"`
	BusKode            string      `json:"bus_kode"`
	BusLayanan         LayananType `json:"bus_layanan"`
	TerminalAsalNama   string      `json:"terminal_asal_nama"`
	TerminalTujuanNama string      `json:"terminal_tujuan_nama"`
	RuteSlug           string      `json:"rute_slug"`
}

func (q *Queries) ListJadwalAdmin(ctx context.Context, arg ListJadwalAdminParams) ([]ListJadwalAdminRow, error) {
	rows, err := q.db.Query(ctx, listJadwalAdmin, arg.OffsetData, arg.LimitData)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListJadwalAdminRow
	for rows.Next() {
		var i ListJadwalAdminRow
		if err := rows.Scan(
			&i.ID,
			&i.JamBerangkat,
			&i.JamTiba,
			&i.HariOperasi,
			&i.Aktif,
			&i.BusKode,
			&i.BusLayanan,
			&i.TerminalAsalNama,
			&i.TerminalTujuanNama,
			&i.RuteSlug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJadwalLibur = `-- name: ListJadwalLibur :many

SELECT id, jadwal_id, tanggal, keterangan
FROM jadwal_libur
ORDER BY tanggal DESC
`

type ListJadwalLiburRow struct {
	ID         int32       `json:"id"`
	JadwalID   pgtype.Int4 `json:"jadwal_id"`
	Tanggal    pgtype.Date `json:"tanggal"`
	Keterangan pgtype.Text `json:"keterangan"`
}

// =====================================================================
// JADWAL LIBUR
// =====================================================================
func (q *Queries) ListJadwalLibur(ctx context.Context) ([]ListJadwalLiburRow, error) {
	rows, err := q.db.Query(ctx, listJadwalLibur)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListJadwalLiburRow
	for rows.Next() {
		var i ListJadwalLiburRow
		if err := rows.Scan(
			&i.ID,
			&i.JadwalID,
			&i.Tanggal,
			&i.Keterangan,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRutesAdmin = `-- name: ListRutesAdmin :many

SELECT r.id, r.slug, r.durasi_menit, r.aktif,
       ta.nama AS terminal_asal_nama,   ta.kota AS kota_asal,
       tt.nama AS terminal_tujuan_nama, tt.kota AS kota_tujuan
FROM rute r
JOIN terminal ta ON ta.id = r.terminal_asal_id
JOIN terminal tt ON tt.id = r.terminal_tujuan_id
ORDER BY ta.kota, ta.nama
LIMIT $2 OFFSET $1
`

type ListRutesAdminParams struct {
	OffsetData int32 `json:"offset_data"`
	LimitData  int32 `json:"limit_data"`
}

type ListRutesAdminRow struct {
	ID                 int32  `json:"id"`
	Slug               string `json:"slug"`
	DurasiMenit        int32  `json:"durasi_menit"`
	Aktif              bool   `json:"aktif"`
	TerminalAsalNama   string `json:"terminal_asal_nama"`
	KotaAsal           string `json:"kota_asal"`
	TerminalTujuanNama string `json:"terminal_tujuan_nama"`
	KotaTujuan         string `json:"kota_tujuan"`
}

// =====================================================================
// RUTE
// =====================================================================
func (q *Queries) ListRutesAdmin(ctx context.Context, arg ListRutesAdminParams) ([]ListRutesAdminRow, error) {
	rows, err := q.db.Query(ctx, listRutesAdmin, arg.OffsetData, arg.LimitData)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRutesAdminRow
	for rows.Next() {
		var i ListRutesAdminRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.DurasiMenit,
			&i.Aktif,
			&i.TerminalAsalNama,
			&i.KotaAsal,
			&i.TerminalTujuanNama,
			&i.KotaTujuan,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchJadwalPublic = `-- name: SearchJadwalPublic :many

SELECT
    j.id,
    j.jam_berangkat,
    j.jam_tiba,
    b.kode      AS bus_kode,
    b.layanan   AS bus_layanan,
    b.fasilitas AS bus_fasilitas,
    r.id        AS rute_id,
    r.durasi_menit,
    ta.nama     AS terminal_asal_nama,
    tt.nama     AS terminal_tujuan_nama,
    COALESCE(h.harga, 0) AS harga_dasar
FROM jadwal j
JOIN bus b       ON b.id  = j.bus_id
JOIN rute r      ON r.id  = j.rute_id
JOIN terminal ta ON ta.id = r.terminal_asal_id
JOIN terminal tt ON tt.id = r.terminal_tujuan_id
LEFT JOIN harga h ON h.rute_id = r.id
    AND h.layanan = b.layanan
    AND (
        (b.layanan = 'luxury'  AND h.tipe_penumpang IS NULL)
     OR (b.layanan = 'reguler' AND h.tipe_penumpang = 'umum')
    )
WHERE r.terminal_asal_id  = $1
  AND r.terminal_tujuan_id = $2
  AND r.aktif = true
  AND j.aktif = true
  AND (j.hari_operasi & $3::SMALLINT) > 0
  AND NOT EXISTS (
        SELECT 1 FROM jadwal_libur jl
        WHERE jl.tanggal = $4
          AND (jl.jadwal_id IS NULL OR jl.jadwal_id = j.id)
      )
ORDER BY j.jam_berangkat
`

type SearchJadwalPublicParams struct {
	TerminalAsalID   int32       `json:"terminal_asal_id"`
	TerminalTujuanID int32       `json:"terminal_tujuan_id"`
	HariBitmask      int16       `json:"hari_bitmask"`
	Tanggal          pgtype.Date `json:"tanggal"`
}

type SearchJadwalPublicRow struct {
	ID                 int32       `json:"id"`
	JamBerangkat       pgtype.Time `json:"jam_berangkat"`
	JamTiba            pgtype.Time `json:"jam_tiba"`
	BusKode            string      `json:"bus_kode"`
	BusLayanan         LayananType `json:"bus_layanan"`
	BusFasilitas       pgtype.Text `json:"bus_fasilitas"`
	RuteID             int32       `json:"rute_id"`
	DurasiMenit        int32       `json:"durasi_menit"`
	TerminalAsalNama   string      `json:"terminal_asal_nama"`
	TerminalTujuanNama string      `json:"terminal_tujuan_nama"`
	HargaDasar         int32       `json:"harga_dasar"`
}

// =====================================================================
// JADWAL
// =====================================================================
func (q *Queries) SearchJadwalPublic(ctx context.Context, arg SearchJadwalPublicParams) ([]SearchJadwalPublicRow, error) {
	rows, err := q.db.Query(ctx, searchJadwalPublic,
		arg.TerminalAsalID,
		arg.TerminalTujuanID,
		arg.HariBitmask,
		arg.Tanggal,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchJadwalPublicRow
	for rows.Next() {
		var i SearchJadwalPublicRow
		if err := rows.Scan(
			&i.ID,
			&i.JamBerangkat,
			&i.JamTiba,
			&i.BusKode,
			&i.BusLayanan,
			&i.BusFasilitas,
			&i.RuteID,
			&i.DurasiMenit,
			&i.TerminalAsalNama,
			&i.TerminalTujuanNama,
			&i.HargaDasar,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBus = `-- name: UpdateBus :exec
UPDATE bus
SET 
    kode       = $1, 
    layanan    = $2, 
    fasilitas  = $3, 
    kapasitas  = $4, 
    updated_at = CURRENT_TIMESTAMP
WHERE id = $5
`

type UpdateBusParams struct {
	Kode      string      `json:"kode"`
	Layanan   LayananType `json:"layanan"`
	Fasilitas pgtype.Text `json:"fasilitas"`
	Kapasitas pgtype.Int4 `json:"kapasitas"`
	ID        int32       `json:"id"`
}

func (q *Queries) UpdateBus(ctx context.Context, arg UpdateBusParams) error {
	_, err := q.db.Exec(ctx, updateBus,
		arg.Kode,
		arg.Layanan,
		arg.Fasilitas,
		arg.Kapasitas,
		arg.ID,
	)
	return err
}

const updateHarga = `-- name: UpdateHarga :exec
UPDATE harga 
SET harga = $1, updated_at = CURRENT_TIMESTAMP 
WHERE id = $2
`

type UpdateHargaParams struct {
	Harga int32 `json:"harga"`
	ID    int32 `json:"id"`
}

func (q *Queries) UpdateHarga(ctx context.Context, arg UpdateHargaParams) error {
	_, err := q.db.Exec(ctx, updateHarga, arg.Harga, arg.ID)
	return err
}

const updateJadwal = `-- name: UpdateJadwal :exec
UPDATE jadwal
SET 
    rute_id       = $1, 
    bus_id        = $2, 
    jam_berangkat = $3, 
    jam_tiba      = $4, 
    hari_operasi  = $5, 
    aktif         = $6, 
    updated_at    = CURRENT_TIMESTAMP
WHERE id = $7
`

type UpdateJadwalParams struct {
	RuteID       int32       `json:"rute_id"`
	BusID        int32       `json:"bus_id"`
	JamBerangkat pgtype.Time `json:"jam_berangkat"`
	JamTiba      pgtype.Time `json:"jam_tiba"`
	HariOperasi  int16       `json:"hari_operasi"`
	Aktif        bool        `json:"aktif"`
	ID           int32       `json:"id"`
}

func (q *Queries) UpdateJadwal(ctx context.Context, arg UpdateJadwalParams) error {
	_, err := q.db.Exec(ctx, updateJadwal,
		arg.RuteID,
		arg.BusID,
		arg.JamBerangkat,
		arg.JamTiba,
		arg.HariOperasi,
		arg.Aktif,
		arg.ID,
	)
	return err
}

const updateRute = `-- name: UpdateRute :exec
UPDATE rute
SET 
    terminal_asal_id   = $1, 
    terminal_tujuan_id = $2, 
    slug               = $3,
    durasi_menit       = $4, 
    aktif              = $5, 
    updated_at         = CURRENT_TIMESTAMP
WHERE slug = $6
`

type UpdateRuteParams struct {
	TerminalAsalID   int32  `json:"terminal_asal_id"`
	TerminalTujuanID int32  `json:"terminal_tujuan_id"`
	SlugBaru         string `json:"slug_baru"`
	DurasiMenit      int32  `json:"durasi_menit"`
	Aktif            bool   `json:"aktif"`
	SlugLama         string `json:"slug_lama"`
}

func (q *Queries) UpdateRute(ctx context.Context, arg UpdateRuteParams) error {
	_, err := q.db.Exec(ctx, updateRute,
		arg.TerminalAsalID,
		arg.TerminalTujuanID,
		arg.SlugBaru,
		arg.DurasiMenit,
		arg.Aktif,
		arg.SlugLama,
	)
	return err
}

const updateTerminal = `-- name: UpdateTerminal :exec
UPDATE terminal
SET 
    nama       = $1, 
    kota       = $2, 
    slug       = $3, 
    lat        = $4, 
    lng        = $5, 
    aktif      = $6, 
    updated_at = CURRENT_TIMESTAMP
WHERE slug = $7
`

type UpdateTerminalParams struct {
	Nama     string        `json:"nama"`
	Kota     string        `json:"kota"`
	SlugBaru string        `json:"slug_baru"`
	Lat      pgtype.Float8 `json:"lat"`
	Lng      pgtype.Float8 `json:"lng"`
	Aktif    bool          `json:"aktif"`
	SlugLama string        `json:"slug_lama"`
}

func (q *Queries) UpdateTerminal(ctx context.Context, arg UpdateTerminalParams) error {
	_, err := q.db.Exec(ctx, updateTerminal,
		arg.Nama,
		arg.Kota,
		arg.SlugBaru,
		arg.Lat,
		arg.Lng,
		arg.Aktif,
		arg.SlugLama,
	)
	return err
}
