// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type GenderType string

const (
	GenderTypeLAKILAKI  GenderType = "LAKI_LAKI"
	GenderTypePEREMPUAN GenderType = "PEREMPUAN"
)

func (e *GenderType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = GenderType(s)
	case string:
		*e = GenderType(s)
	default:
		return fmt.Errorf("unsupported scan type for GenderType: %T", src)
	}
	return nil
}

type NullGenderType struct {
	GenderType GenderType `json:"gender_type"`
	Valid      bool       `json:"valid"` // Valid is true if GenderType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullGenderType) Scan(value interface{}) error {
	if value == nil {
		ns.GenderType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.GenderType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullGenderType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.GenderType), nil
}

type UserRole string

const (
	UserRoleUser       UserRole = "user"
	UserRoleAdmin      UserRole = "admin"
	UserRoleSuperadmin UserRole = "superadmin"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole `json:"user_role"`
	Valid    bool     `json:"valid"` // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type RefreshToken struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	IsRevoked bool               `json:"is_revoked"`
}

type User struct {
	ID                   pgtype.UUID        `json:"id"`
	FirstName            string             `json:"first_name"`
	LastName             string             `json:"last_name"`
	Phone                string             `json:"phone"`
	Email                string             `json:"email"`
	Nik                  string             `json:"nik"`
	Address              pgtype.Text        `json:"address"`
	BirthDate            pgtype.Date        `json:"birth_date"`
	Gender               NullGenderType     `json:"gender"`
	PasswordHash         string             `json:"password_hash"`
	Role                 UserRole           `json:"role"`
	IsActive             bool               `json:"is_active"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
	EmailVerified        bool               `json:"email_verified"`
	EmailVerifyToken     pgtype.Text        `json:"email_verify_token"`
	EmailVerifyExpiresAt pgtype.Timestamptz `json:"email_verify_expires_at"`
}

type UserCategoryPreference struct {
	UserID     pgtype.UUID `json:"user_id"`
	CategoryID pgtype.UUID `json:"category_id"`
}

type UserServiceFavorite struct {
	UserID    pgtype.UUID        `json:"user_id"`
	ServiceID pgtype.UUID        `json:"service_id"`
	AddedAt   pgtype.Timestamptz `json:"added_at"`
}
