// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addUserFavorite = `-- name: AddUserFavorite :exec
INSERT INTO user_service_favorites (user_id, service_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddUserFavoriteParams struct {
	UserID    pgtype.UUID `json:"user_id"`
	ServiceID pgtype.UUID `json:"service_id"`
}

func (q *Queries) AddUserFavorite(ctx context.Context, arg AddUserFavoriteParams) error {
	_, err := q.db.Exec(ctx, addUserFavorite, arg.UserID, arg.ServiceID)
	return err
}

const checkEmailExists = `-- name: CheckEmailExists :one
SELECT id FROM users WHERE email = $1 LIMIT 1
`

func (q *Queries) CheckEmailExists(ctx context.Context, email string) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, checkEmailExists, email)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const checkNIKExists = `-- name: CheckNIKExists :one
SELECT id FROM users WHERE nik = $1 LIMIT 1
`

func (q *Queries) CheckNIKExists(ctx context.Context, nik string) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, checkNIKExists, nik)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const checkPhoneExists = `-- name: CheckPhoneExists :one
SELECT id FROM users WHERE phone = $1 LIMIT 1
`

func (q *Queries) CheckPhoneExists(ctx context.Context, phone string) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, checkPhoneExists, phone)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createRefreshToken = `-- name: CreateRefreshToken :exec

INSERT INTO refresh_tokens (user_id, token_hash, expires_at)
VALUES (
    $1,
    $2,
    $3
)
`

type CreateRefreshTokenParams struct {
	UserID    pgtype.UUID        `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

// =============================================================================
// Refresh Token Queries
// =============================================================================
func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) error {
	_, err := q.db.Exec(ctx, createRefreshToken, arg.UserID, arg.TokenHash, arg.ExpiresAt)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    first_name, last_name, phone, email, nik,
    address, birth_date, gender, password_hash
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9
)
RETURNING id, first_name, last_name, phone, email, nik,
          address, birth_date, gender, role, is_active, created_at, updated_at
`

type CreateUserParams struct {
	FirstName    string         `json:"first_name"`
	LastName     string         `json:"last_name"`
	Phone        string         `json:"phone"`
	Email        string         `json:"email"`
	Nik          string         `json:"nik"`
	Address      pgtype.Text    `json:"address"`
	BirthDate    pgtype.Date    `json:"birth_date"`
	Gender       NullGenderType `json:"gender"`
	PasswordHash string         `json:"password_hash"`
}

type CreateUserRow struct {
	ID        pgtype.UUID        `json:"id"`
	FirstName string             `json:"first_name"`
	LastName  string             `json:"last_name"`
	Phone     string             `json:"phone"`
	Email     string             `json:"email"`
	Nik       string             `json:"nik"`
	Address   pgtype.Text        `json:"address"`
	BirthDate pgtype.Date        `json:"birth_date"`
	Gender    NullGenderType     `json:"gender"`
	Role      UserRole           `json:"role"`
	IsActive  bool               `json:"is_active"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.FirstName,
		arg.LastName,
		arg.Phone,
		arg.Email,
		arg.Nik,
		arg.Address,
		arg.BirthDate,
		arg.Gender,
		arg.PasswordHash,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Phone,
		&i.Email,
		&i.Nik,
		&i.Address,
		&i.BirthDate,
		&i.Gender,
		&i.Role,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deactivateUser = `-- name: DeactivateUser :exec
UPDATE users SET is_active = false WHERE id = $1
`

func (q *Queries) DeactivateUser(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deactivateUser, id)
	return err
}

const bumpFavoritesTimestamp = `-- name: BumpFavoritesTimestamp :exec
UPDATE users SET favorites_updated_at = NOW() WHERE id = $1
`

func (q *Queries) BumpFavoritesTimestamp(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, bumpFavoritesTimestamp, id)
	return err
}

const getFavoritesUpdatedAt = `-- name: GetFavoritesUpdatedAt :one
SELECT favorites_updated_at FROM users WHERE id = $1
`

func (q *Queries) GetFavoritesUpdatedAt(ctx context.Context, id pgtype.UUID) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, getFavoritesUpdatedAt, id)
	var favorites_updated_at pgtype.Timestamptz
	err := row.Scan(&favorites_updated_at)
	return favorites_updated_at, err
}

const deleteExpiredTokens = `-- name: DeleteExpiredTokens :exec
DELETE FROM refresh_tokens WHERE expires_at < NOW() OR is_revoked = true
`

func (q *Queries) DeleteExpiredTokens(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredTokens)
	return err
}

const deleteUserPreference = `-- name: DeleteUserPreference :exec
DELETE FROM user_category_preferences
WHERE user_id = $1
  AND category_id = $2
`

type DeleteUserPreferenceParams struct {
	UserID     pgtype.UUID `json:"user_id"`
	CategoryID pgtype.UUID `json:"category_id"`
}

func (q *Queries) DeleteUserPreference(ctx context.Context, arg DeleteUserPreferenceParams) error {
	_, err := q.db.Exec(ctx, deleteUserPreference, arg.UserID, arg.CategoryID)
	return err
}

const deleteUserPreferences = `-- name: DeleteUserPreferences :exec
DELETE FROM user_category_preferences
WHERE user_id = $1
`

func (q *Queries) DeleteUserPreferences(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteUserPreferences, userID)
	return err
}

const getRefreshToken = `-- name: GetRefreshToken :one
SELECT id, user_id, token_hash, expires_at, created_at, is_revoked
FROM refresh_tokens
WHERE token_hash = $1 LIMIT 1
`

func (q *Queries) GetRefreshToken(ctx context.Context, tokenHash string) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshToken, tokenHash)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.IsRevoked,
	)
	return i, err
}

const getUserByEmailForAuth = `-- name: GetUserByEmailForAuth :one

SELECT id, first_name, last_name, phone, email, nik, address, birth_date, gender,
       password_hash, role, is_active, email_verified, created_at, updated_at
FROM users WHERE email = $1 LIMIT 1
`

type GetUserByEmailForAuthRow struct {
	ID            pgtype.UUID        `json:"id"`
	FirstName     string             `json:"first_name"`
	LastName      string             `json:"last_name"`
	Phone         string             `json:"phone"`
	Email         string             `json:"email"`
	Nik           string             `json:"nik"`
	Address       pgtype.Text        `json:"address"`
	BirthDate     pgtype.Date        `json:"birth_date"`
	Gender        NullGenderType     `json:"gender"`
	PasswordHash  string             `json:"password_hash"`
	Role          UserRole           `json:"role"`
	IsActive      bool               `json:"is_active"`
	EmailVerified bool               `json:"email_verified"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

// =============================================================================
// Auth Queries
// =============================================================================
func (q *Queries) GetUserByEmailForAuth(ctx context.Context, email string) (GetUserByEmailForAuthRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmailForAuth, email)
	var i GetUserByEmailForAuthRow
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Phone,
		&i.Email,
		&i.Nik,
		&i.Address,
		&i.BirthDate,
		&i.Gender,
		&i.PasswordHash,
		&i.Role,
		&i.IsActive,
		&i.EmailVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmailVerifyToken = `-- name: GetUserByEmailVerifyToken :one
SELECT id, first_name, last_name, email, email_verified
FROM users
WHERE email_verify_token = $1
  AND email_verify_expires_at > NOW()
  AND email_verified = false
LIMIT 1
`

type GetUserByEmailVerifyTokenRow struct {
	ID            pgtype.UUID `json:"id"`
	FirstName     string      `json:"first_name"`
	LastName      string      `json:"last_name"`
	Email         string      `json:"email"`
	EmailVerified bool        `json:"email_verified"`
}

func (q *Queries) GetUserByEmailVerifyToken(ctx context.Context, token pgtype.Text) (GetUserByEmailVerifyTokenRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmailVerifyToken, token)
	var i GetUserByEmailVerifyTokenRow
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.EmailVerified,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, first_name, last_name, phone, email, nik, address, birth_date, gender,
       role, is_active, created_at, updated_at
FROM users WHERE id = $1 LIMIT 1
`

type GetUserByIDRow struct {
	ID        pgtype.UUID        `json:"id"`
	FirstName string             `json:"first_name"`
	LastName  string             `json:"last_name"`
	Phone     string             `json:"phone"`
	Email     string             `json:"email"`
	Nik       string             `json:"nik"`
	Address   pgtype.Text        `json:"address"`
	BirthDate pgtype.Date        `json:"birth_date"`
	Gender    NullGenderType     `json:"gender"`
	Role      UserRole           `json:"role"`
	IsActive  bool               `json:"is_active"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Phone,
		&i.Email,
		&i.Nik,
		&i.Address,
		&i.BirthDate,
		&i.Gender,
		&i.Role,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserFavoriteCount = `-- name: GetUserFavoriteCount :one
SELECT COUNT(*) FROM user_service_favorites WHERE user_id = $1
`

func (q *Queries) GetUserFavoriteCount(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getUserFavoriteCount, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getUserFavorites = `-- name: GetUserFavorites :many

SELECT service_id, added_at AS updated_at FROM user_service_favorites
WHERE user_id = $1
ORDER BY added_at DESC
`

type GetUserFavoritesRow struct {
	ServiceID pgtype.UUID        `json:"service_id"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

// =============================================================================
// Service Favorites
// =============================================================================
func (q *Queries) GetUserFavorites(ctx context.Context, userID pgtype.UUID) ([]GetUserFavoritesRow, error) {
	rows, err := q.db.Query(ctx, getUserFavorites, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserFavoritesRow
	for rows.Next() {
		var row GetUserFavoritesRow
		if err := rows.Scan(&row.ServiceID, &row.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, row)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserPreferences = `-- name: GetUserPreferences :many

SELECT category_id
FROM user_category_preferences
WHERE user_id = $1
`

// =============================================================================
// User Category Preferences
// =============================================================================
func (q *Queries) GetUserPreferences(ctx context.Context, userID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, getUserPreferences, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var category_id pgtype.UUID
		if err := rows.Scan(&category_id); err != nil {
			return nil, err
		}
		items = append(items, category_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertUserPreference = `-- name: InsertUserPreference :exec
INSERT INTO user_category_preferences (user_id, category_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type InsertUserPreferenceParams struct {
	UserID     pgtype.UUID `json:"user_id"`
	CategoryID pgtype.UUID `json:"category_id"`
}

func (q *Queries) InsertUserPreference(ctx context.Context, arg InsertUserPreferenceParams) error {
	_, err := q.db.Exec(ctx, insertUserPreference, arg.UserID, arg.CategoryID)
	return err
}

const listUsers = `-- name: ListUsers :many
SELECT id, first_name, last_name, phone, email, nik, role, is_active, created_at
FROM users
ORDER BY created_at DESC
LIMIT $2 OFFSET $1
`

type ListUsersParams struct {
	OffsetData int32 `json:"offset_data"`
	LimitData  int32 `json:"limit_data"`
}

type ListUsersRow struct {
	ID        pgtype.UUID        `json:"id"`
	FirstName string             `json:"first_name"`
	LastName  string             `json:"last_name"`
	Phone     string             `json:"phone"`
	Email     string             `json:"email"`
	Nik       string             `json:"nik"`
	Role      UserRole           `json:"role"`
	IsActive  bool               `json:"is_active"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]ListUsersRow, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.OffsetData, arg.LimitData)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersRow
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.FirstName,
			&i.LastName,
			&i.Phone,
			&i.Email,
			&i.Nik,
			&i.Role,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markEmailVerified = `-- name: MarkEmailVerified :exec
UPDATE users
SET email_verified = true,
    email_verify_token = NULL,
    email_verify_expires_at = NULL
WHERE id = $1
`

func (q *Queries) MarkEmailVerified(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markEmailVerified, id)
	return err
}

const removeUserFavorite = `-- name: RemoveUserFavorite :exec
DELETE FROM user_service_favorites
WHERE user_id = $1 AND service_id = $2
`

type RemoveUserFavoriteParams struct {
	UserID    pgtype.UUID `json:"user_id"`
	ServiceID pgtype.UUID `json:"service_id"`
}

func (q *Queries) RemoveUserFavorite(ctx context.Context, arg RemoveUserFavoriteParams) error {
	_, err := q.db.Exec(ctx, removeUserFavorite, arg.UserID, arg.ServiceID)
	return err
}

const revokeAllUserTokens = `-- name: RevokeAllUserTokens :exec
UPDATE refresh_tokens SET is_revoked = true
WHERE user_id = $1
`

func (q *Queries) RevokeAllUserTokens(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokeAllUserTokens, userID)
	return err
}

const revokeRefreshToken = `-- name: RevokeRefreshToken :exec
UPDATE refresh_tokens SET is_revoked = true
WHERE token_hash = $1
`

func (q *Queries) RevokeRefreshToken(ctx context.Context, tokenHash string) error {
	_, err := q.db.Exec(ctx, revokeRefreshToken, tokenHash)
	return err
}

const setEmailVerificationToken = `-- name: SetEmailVerificationToken :exec

UPDATE users
SET email_verify_token = $1,
    email_verify_expires_at = $2
WHERE id = $3
`

type SetEmailVerificationTokenParams struct {
	EmailVerifyToken     pgtype.Text        `json:"email_verify_token"`
	EmailVerifyExpiresAt pgtype.Timestamptz `json:"email_verify_expires_at"`
	ID                   pgtype.UUID        `json:"id"`
}

// =============================================================================
// Email Verification
// =============================================================================
func (q *Queries) SetEmailVerificationToken(ctx context.Context, arg SetEmailVerificationTokenParams) error {
	_, err := q.db.Exec(ctx, setEmailVerificationToken, arg.EmailVerifyToken, arg.EmailVerifyExpiresAt, arg.ID)
	return err
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE users
SET
    first_name = $1,
    last_name  = $2,
    phone      = $3,
    address    = $4,
    birth_date = $5,
    gender     = $6
WHERE id = $7
RETURNING id, first_name, last_name, phone, email, nik,
          address, birth_date, gender, role, is_active, created_at, updated_at
`

type UpdateUserProfileParams struct {
	FirstName string         `json:"first_name"`
	LastName  string         `json:"last_name"`
	Phone     string         `json:"phone"`
	Address   pgtype.Text    `json:"address"`
	BirthDate pgtype.Date    `json:"birth_date"`
	Gender    NullGenderType `json:"gender"`
	ID        pgtype.UUID    `json:"id"`
}

type UpdateUserProfileRow struct {
	ID        pgtype.UUID        `json:"id"`
	FirstName string             `json:"first_name"`
	LastName  string             `json:"last_name"`
	Phone     string             `json:"phone"`
	Email     string             `json:"email"`
	Nik       string             `json:"nik"`
	Address   pgtype.Text        `json:"address"`
	BirthDate pgtype.Date        `json:"birth_date"`
	Gender    NullGenderType     `json:"gender"`
	Role      UserRole           `json:"role"`
	IsActive  bool               `json:"is_active"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (UpdateUserProfileRow, error) {
	row := q.db.QueryRow(ctx, updateUserProfile,
		arg.FirstName,
		arg.LastName,
		arg.Phone,
		arg.Address,
		arg.BirthDate,
		arg.Gender,
		arg.ID,
	)
	var i UpdateUserProfileRow
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Phone,
		&i.Email,
		&i.Nik,
		&i.Address,
		&i.BirthDate,
		&i.Gender,
		&i.Role,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserRole = `-- name: UpdateUserRole :one
UPDATE users SET role = $1
WHERE id = $2
RETURNING id, first_name, last_name, email, role, is_active, updated_at
`

type UpdateUserRoleParams struct {
	Role UserRole    `json:"role"`
	ID   pgtype.UUID `json:"id"`
}

type UpdateUserRoleRow struct {
	ID        pgtype.UUID        `json:"id"`
	FirstName string             `json:"first_name"`
	LastName  string             `json:"last_name"`
	Email     string             `json:"email"`
	Role      UserRole           `json:"role"`
	IsActive  bool               `json:"is_active"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) (UpdateUserRoleRow, error) {
	row := q.db.QueryRow(ctx, updateUserRole, arg.Role, arg.ID)
	var i UpdateUserRoleRow
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Role,
		&i.IsActive,
		&i.UpdatedAt,
	)
	return i, err
}
