// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type BahanPokok struct {
	ID        int32
	Nama      string
	Slug      string
	Satuan    string
	GambarUrl pgtype.Text
}

type HargaHarian struct {
	ID           int32
	BahanPokokID int32
	AreaID       int32
	Harga        int32
	Tanggal      pgtype.Date
}

type MasterArea struct {
	ID   int32
	Nama string
	Slug string
}
