// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: prices.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const checkBahanPokokNamaExists = `-- name: CheckBahanPokokNamaExists :one
SELECT EXISTS(SELECT 1 FROM bahan_pokok WHERE LOWER(nama) = LOWER($1)) AS "exists"
`

func (q *Queries) CheckBahanPokokNamaExists(ctx context.Context, lower string) (bool, error) {
	row := q.db.QueryRow(ctx, checkBahanPokokNamaExists, lower)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const checkBahanPokokNamaExistsExcluding = `-- name: CheckBahanPokokNamaExistsExcluding :one
SELECT EXISTS(SELECT 1 FROM bahan_pokok WHERE LOWER(nama) = LOWER($1) AND id != $2) AS "exists"
`

type CheckBahanPokokNamaExistsExcludingParams struct {
	Lower string
	ID    int32
}

func (q *Queries) CheckBahanPokokNamaExistsExcluding(ctx context.Context, arg CheckBahanPokokNamaExistsExcludingParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkBahanPokokNamaExistsExcluding, arg.Lower, arg.ID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const countBahanPokok = `-- name: CountBahanPokok :one
SELECT COUNT(id) 
FROM bahan_pokok
WHERE ($1::text IS NULL OR nama ILIKE '%' || $1::text || '%')
`

func (q *Queries) CountBahanPokok(ctx context.Context, keyword pgtype.Text) (int64, error) {
	row := q.db.QueryRow(ctx, countBahanPokok, keyword)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createBahanPokok = `-- name: CreateBahanPokok :one
INSERT INTO bahan_pokok (nama, slug, satuan, gambar_url)
VALUES ($1, $2, $3, $4)
RETURNING id, nama, slug
`

type CreateBahanPokokParams struct {
	Nama      string
	Slug      string
	Satuan    string
	GambarUrl pgtype.Text
}

type CreateBahanPokokRow struct {
	ID   int32
	Nama string
	Slug string
}

func (q *Queries) CreateBahanPokok(ctx context.Context, arg CreateBahanPokokParams) (CreateBahanPokokRow, error) {
	row := q.db.QueryRow(ctx, createBahanPokok,
		arg.Nama,
		arg.Slug,
		arg.Satuan,
		arg.GambarUrl,
	)
	var i CreateBahanPokokRow
	err := row.Scan(&i.ID, &i.Nama, &i.Slug)
	return i, err
}

const deleteBahanPokok = `-- name: DeleteBahanPokok :exec
DELETE FROM bahan_pokok WHERE id = $1
`

func (q *Queries) DeleteBahanPokok(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteBahanPokok, id)
	return err
}

const deleteHargaHarian = `-- name: DeleteHargaHarian :exec
DELETE FROM harga_harian WHERE id = $1
`

func (q *Queries) DeleteHargaHarian(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteHargaHarian, id)
	return err
}

const getAllArea = `-- name: GetAllArea :many
SELECT id, nama, slug, created_at, updated_at 
FROM master_area 
ORDER BY nama ASC
`

func (q *Queries) GetAllArea(ctx context.Context) ([]MasterArea, error) {
	rows, err := q.db.Query(ctx, getAllArea)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MasterArea
	for rows.Next() {
		var i MasterArea
		if err := rows.Scan(
			&i.ID,
			&i.Nama,
			&i.Slug,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllBahanPokok = `-- name: GetAllBahanPokok :many
SELECT id, nama, slug, satuan, gambar_url, created_at, updated_at 
FROM bahan_pokok 
WHERE ($1::text IS NULL OR nama ILIKE '%' || $1::text || '%')
ORDER BY nama ASC
LIMIT $3 OFFSET $2
`

type GetAllBahanPokokParams struct {
	Keyword    pgtype.Text
	OffsetData int32
	LimitData  int32
}

func (q *Queries) GetAllBahanPokok(ctx context.Context, arg GetAllBahanPokokParams) ([]BahanPokok, error) {
	rows, err := q.db.Query(ctx, getAllBahanPokok, arg.Keyword, arg.OffsetData, arg.LimitData)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BahanPokok
	for rows.Next() {
		var i BahanPokok
		if err := rows.Scan(
			&i.ID,
			&i.Nama,
			&i.Slug,
			&i.Satuan,
			&i.GambarUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAreaBySlug = `-- name: GetAreaBySlug :one
SELECT id, nama, slug, created_at, updated_at 
FROM master_area 
WHERE slug = $1 
LIMIT 1
`

func (q *Queries) GetAreaBySlug(ctx context.Context, slug string) (MasterArea, error) {
	row := q.db.QueryRow(ctx, getAreaBySlug, slug)
	var i MasterArea
	err := row.Scan(
		&i.ID,
		&i.Nama,
		&i.Slug,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAreaIDByName = `-- name: GetAreaIDByName :one
SELECT id 
FROM master_area 
WHERE nama ILIKE '%' || $1::text || '%' 
LIMIT 1
`

func (q *Queries) GetAreaIDByName(ctx context.Context, nama string) (int32, error) {
	row := q.db.QueryRow(ctx, getAreaIDByName, nama)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const getBahanPokokByID = `-- name: GetBahanPokokByID :one
SELECT id, nama, slug, satuan, gambar_url
FROM bahan_pokok 
WHERE id = $1 
LIMIT 1
`

type GetBahanPokokByIDRow struct {
	ID        int32
	Nama      string
	Slug      string
	Satuan    string
	GambarUrl pgtype.Text
}

func (q *Queries) GetBahanPokokByID(ctx context.Context, id int32) (GetBahanPokokByIDRow, error) {
	row := q.db.QueryRow(ctx, getBahanPokokByID, id)
	var i GetBahanPokokByIDRow
	err := row.Scan(
		&i.ID,
		&i.Nama,
		&i.Slug,
		&i.Satuan,
		&i.GambarUrl,
	)
	return i, err
}

const getBahanPokokBySlug = `-- name: GetBahanPokokBySlug :one
SELECT id, nama, slug, satuan, gambar_url, created_at, updated_at 
FROM bahan_pokok 
WHERE slug = $1 
LIMIT 1
`

func (q *Queries) GetBahanPokokBySlug(ctx context.Context, slug string) (BahanPokok, error) {
	row := q.db.QueryRow(ctx, getBahanPokokBySlug, slug)
	var i BahanPokok
	err := row.Scan(
		&i.ID,
		&i.Nama,
		&i.Slug,
		&i.Satuan,
		&i.GambarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBahanPokokIDByName = `-- name: GetBahanPokokIDByName :one
SELECT id 
FROM bahan_pokok 
WHERE nama ILIKE '%' || $1::text || '%' 
LIMIT 1
`

func (q *Queries) GetBahanPokokIDByName(ctx context.Context, nama string) (int32, error) {
	row := q.db.QueryRow(ctx, getBahanPokokIDByName, nama)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const getDaftarHargaArea = `-- name: GetDaftarHargaArea :many
SELECT ma.nama AS area, ma.slug AS area_slug, h.harga
FROM harga_harian h
JOIN master_area ma ON h.area_id = ma.id
WHERE h.bahan_pokok_id = $1 
  AND h.tanggal = $2::date
ORDER BY ma.nama ASC
`

type GetDaftarHargaAreaParams struct {
	BahanPokokID int32
	Tanggal      pgtype.Date
}

type GetDaftarHargaAreaRow struct {
	Area     string
	AreaSlug string
	Harga    int32
}

func (q *Queries) GetDaftarHargaArea(ctx context.Context, arg GetDaftarHargaAreaParams) ([]GetDaftarHargaAreaRow, error) {
	rows, err := q.db.Query(ctx, getDaftarHargaArea, arg.BahanPokokID, arg.Tanggal)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDaftarHargaAreaRow
	for rows.Next() {
		var i GetDaftarHargaAreaRow
		if err := rows.Scan(&i.Area, &i.AreaSlug, &i.Harga); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRataRataArea15Hari = `-- name: GetRataRataArea15Hari :many
SELECT ma.nama AS area, ma.slug AS area_slug, ROUND(AVG(h.harga))::int AS rata_rata_15_hari
FROM harga_harian h
JOIN master_area ma ON h.area_id = ma.id
WHERE h.bahan_pokok_id = $1 
  AND h.tanggal <= $2::date 
  AND h.tanggal > ($2::date - INTERVAL '15 days')
GROUP BY ma.id, ma.nama, ma.slug
ORDER BY rata_rata_15_hari DESC
`

type GetRataRataArea15HariParams struct {
	BahanPokokID int32
	Tanggal      pgtype.Date
}

type GetRataRataArea15HariRow struct {
	Area           string
	AreaSlug       string
	RataRata15Hari int32
}

func (q *Queries) GetRataRataArea15Hari(ctx context.Context, arg GetRataRataArea15HariParams) ([]GetRataRataArea15HariRow, error) {
	rows, err := q.db.Query(ctx, getRataRataArea15Hari, arg.BahanPokokID, arg.Tanggal)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRataRataArea15HariRow
	for rows.Next() {
		var i GetRataRataArea15HariRow
		if err := rows.Scan(&i.Area, &i.AreaSlug, &i.RataRata15Hari); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRiwayatHargaRataRata = `-- name: GetRiwayatHargaRataRata :many
SELECT tanggal, ROUND(AVG(harga))::int AS rata_rata_harga
FROM harga_harian
WHERE bahan_pokok_id = $1 
  AND tanggal <= $2::date
  AND tanggal > ($2::date - INTERVAL '30 days')
GROUP BY tanggal
ORDER BY tanggal ASC
`

type GetRiwayatHargaRataRataParams struct {
	BahanPokokID int32
	Tanggal      pgtype.Date
}

type GetRiwayatHargaRataRataRow struct {
	Tanggal       pgtype.Date
	RataRataHarga int32
}

func (q *Queries) GetRiwayatHargaRataRata(ctx context.Context, arg GetRiwayatHargaRataRataParams) ([]GetRiwayatHargaRataRataRow, error) {
	rows, err := q.db.Query(ctx, getRiwayatHargaRataRata, arg.BahanPokokID, arg.Tanggal)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRiwayatHargaRataRataRow
	for rows.Next() {
		var i GetRiwayatHargaRataRataRow
		if err := rows.Scan(&i.Tanggal, &i.RataRataHarga); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTanggalUpdateTerakhir = `-- name: GetTanggalUpdateTerakhir :one
SELECT tanggal 
FROM harga_harian 
WHERE bahan_pokok_id = $1 
  AND tanggal <= $2::date 
ORDER BY tanggal DESC 
LIMIT 1
`

type GetTanggalUpdateTerakhirParams struct {
	BahanPokokID int32
	Tanggal      pgtype.Date
}

func (q *Queries) GetTanggalUpdateTerakhir(ctx context.Context, arg GetTanggalUpdateTerakhirParams) (pgtype.Date, error) {
	row := q.db.QueryRow(ctx, getTanggalUpdateTerakhir, arg.BahanPokokID, arg.Tanggal)
	var tanggal pgtype.Date
	err := row.Scan(&tanggal)
	return tanggal, err
}

const getTotalBahanPokok = `-- name: GetTotalBahanPokok :one
SELECT COUNT(*) 
FROM bahan_pokok
WHERE $1::text IS NULL OR nama ILIKE '%' || $1::text || '%'
`

func (q *Queries) GetTotalBahanPokok(ctx context.Context, keyword string) (int64, error) {
	row := q.db.QueryRow(ctx, getTotalBahanPokok, keyword)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getTrenSemuaBahanPokok = `-- name: GetTrenSemuaBahanPokok :many
SELECT 
    h_outer.bahan_pokok_id,
    h_outer.tanggal,
    ROUND(AVG(h_outer.harga))::int AS rata_rata_harga
FROM harga_harian h_outer
JOIN master_area ma ON h_outer.area_id = ma.id
WHERE h_outer.tanggal <= $1::date
  AND ($2::text IS NULL OR ma.slug = $2::text)
  AND (h_outer.bahan_pokok_id, h_outer.tanggal) IN (
    SELECT ranked.bahan_pokok_id, ranked.tanggal
    FROM (
        SELECT 
            h_inner.bahan_pokok_id, 
            h_inner.tanggal,
            DENSE_RANK() OVER (
                PARTITION BY h_inner.bahan_pokok_id 
                ORDER BY h_inner.tanggal DESC
            ) AS urutan
        FROM harga_harian h_inner
        JOIN master_area ma_inner ON h_inner.area_id = ma_inner.id
        WHERE h_inner.tanggal <= $1::date
          AND ($2::text IS NULL OR ma_inner.slug = $2::text)
    ) ranked
    WHERE ranked.urutan <= 2  
)
GROUP BY h_outer.bahan_pokok_id, h_outer.tanggal
ORDER BY h_outer.bahan_pokok_id ASC, h_outer.tanggal ASC
`

type GetTrenSemuaBahanPokokParams struct {
	Tanggal  pgtype.Date
	AreaSlug pgtype.Text
}

type GetTrenSemuaBahanPokokRow struct {
	BahanPokokID  int32
	Tanggal       pgtype.Date
	RataRataHarga int32
}

func (q *Queries) GetTrenSemuaBahanPokok(ctx context.Context, arg GetTrenSemuaBahanPokokParams) ([]GetTrenSemuaBahanPokokRow, error) {
	rows, err := q.db.Query(ctx, getTrenSemuaBahanPokok, arg.Tanggal, arg.AreaSlug)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTrenSemuaBahanPokokRow
	for rows.Next() {
		var i GetTrenSemuaBahanPokokRow
		if err := rows.Scan(&i.BahanPokokID, &i.Tanggal, &i.RataRataHarga); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTrenSemuaBahanPokokByArea = `-- name: GetTrenSemuaBahanPokokByArea :many
SELECT 
    bp.id AS bahan_pokok_id,
    hh.tanggal,
    hh.harga AS rata_rata_harga
FROM bahan_pokok bp
JOIN harga_harian hh ON bp.id = hh.bahan_pokok_id
JOIN master_area ma ON hh.area_id = ma.id
WHERE hh.tanggal = $1 AND ma.slug = $2
ORDER BY bp.id
`

type GetTrenSemuaBahanPokokByAreaParams struct {
	Tanggal pgtype.Date
	Slug    string
}

type GetTrenSemuaBahanPokokByAreaRow struct {
	BahanPokokID  int32
	Tanggal       pgtype.Date
	RataRataHarga int32
}

func (q *Queries) GetTrenSemuaBahanPokokByArea(ctx context.Context, arg GetTrenSemuaBahanPokokByAreaParams) ([]GetTrenSemuaBahanPokokByAreaRow, error) {
	rows, err := q.db.Query(ctx, getTrenSemuaBahanPokokByArea, arg.Tanggal, arg.Slug)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTrenSemuaBahanPokokByAreaRow
	for rows.Next() {
		var i GetTrenSemuaBahanPokokByAreaRow
		if err := rows.Scan(&i.BahanPokokID, &i.Tanggal, &i.RataRataHarga); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBahanPokok = `-- name: UpdateBahanPokok :one
UPDATE bahan_pokok
SET nama       = $1,
    slug       = $2,
    satuan     = $3,
    gambar_url = $4
WHERE id = $5
RETURNING id, nama, slug
`

type UpdateBahanPokokParams struct {
	Nama      string
	Slug      string
	Satuan    string
	GambarUrl pgtype.Text
	ID        int32
}

type UpdateBahanPokokRow struct {
	ID   int32
	Nama string
	Slug string
}

func (q *Queries) UpdateBahanPokok(ctx context.Context, arg UpdateBahanPokokParams) (UpdateBahanPokokRow, error) {
	row := q.db.QueryRow(ctx, updateBahanPokok,
		arg.Nama,
		arg.Slug,
		arg.Satuan,
		arg.GambarUrl,
		arg.ID,
	)
	var i UpdateBahanPokokRow
	err := row.Scan(&i.ID, &i.Nama, &i.Slug)
	return i, err
}

const upsertHargaHarian = `-- name: UpsertHargaHarian :one
INSERT INTO harga_harian (bahan_pokok_id, area_id, harga, tanggal)
VALUES ($1, $2, $3, $4)
ON CONFLICT (bahan_pokok_id, area_id, tanggal) 
DO UPDATE SET harga = EXCLUDED.harga
RETURNING id, bahan_pokok_id, area_id, harga, tanggal
`

type UpsertHargaHarianParams struct {
	BahanPokokID int32
	AreaID       int32
	Harga        int32
	Tanggal      pgtype.Date
}

type UpsertHargaHarianRow struct {
	ID           int64
	BahanPokokID int32
	AreaID       int32
	Harga        int32
	Tanggal      pgtype.Date
}

func (q *Queries) UpsertHargaHarian(ctx context.Context, arg UpsertHargaHarianParams) (UpsertHargaHarianRow, error) {
	row := q.db.QueryRow(ctx, upsertHargaHarian,
		arg.BahanPokokID,
		arg.AreaID,
		arg.Harga,
		arg.Tanggal,
	)
	var i UpsertHargaHarianRow
	err := row.Scan(
		&i.ID,
		&i.BahanPokokID,
		&i.AreaID,
		&i.Harga,
		&i.Tanggal,
	)
	return i, err
}
