// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: prices.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createBahanPokok = `-- name: CreateBahanPokok :one
INSERT INTO bahan_pokok (nama, slug, satuan, gambar_url)
VALUES ($1, $2, $3, $4)
RETURNING id, nama, slug, satuan, gambar_url
`

type CreateBahanPokokParams struct {
	Nama      string
	Slug      string
	Satuan    string
	GambarUrl pgtype.Text
}

func (q *Queries) CreateBahanPokok(ctx context.Context, arg CreateBahanPokokParams) (BahanPokok, error) {
	row := q.db.QueryRow(ctx, createBahanPokok,
		arg.Nama,
		arg.Slug,
		arg.Satuan,
		arg.GambarUrl,
	)
	var i BahanPokok
	err := row.Scan(
		&i.ID,
		&i.Nama,
		&i.Slug,
		&i.Satuan,
		&i.GambarUrl,
	)
	return i, err
}

const createHargaHarian = `-- name: CreateHargaHarian :one
INSERT INTO harga_harian (bahan_pokok_id, area_id, harga, tanggal)
VALUES ($1, $2, $3, $4)
ON CONFLICT (bahan_pokok_id, area_id, tanggal) 
DO UPDATE SET harga = EXCLUDED.harga
RETURNING id, bahan_pokok_id, area_id, harga, tanggal
`

type CreateHargaHarianParams struct {
	BahanPokokID int32
	AreaID       int32
	Harga        int32
	Tanggal      pgtype.Date
}

func (q *Queries) CreateHargaHarian(ctx context.Context, arg CreateHargaHarianParams) (HargaHarian, error) {
	row := q.db.QueryRow(ctx, createHargaHarian,
		arg.BahanPokokID,
		arg.AreaID,
		arg.Harga,
		arg.Tanggal,
	)
	var i HargaHarian
	err := row.Scan(
		&i.ID,
		&i.BahanPokokID,
		&i.AreaID,
		&i.Harga,
		&i.Tanggal,
	)
	return i, err
}

const deleteBahanPokok = `-- name: DeleteBahanPokok :exec
DELETE FROM bahan_pokok WHERE id = $1
`

func (q *Queries) DeleteBahanPokok(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteBahanPokok, id)
	return err
}

const deleteHargaHarian = `-- name: DeleteHargaHarian :exec
DELETE FROM harga_harian WHERE id = $1
`

func (q *Queries) DeleteHargaHarian(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteHargaHarian, id)
	return err
}

const getAllArea = `-- name: GetAllArea :many
SELECT id, nama, slug FROM master_area ORDER BY nama ASC
`

func (q *Queries) GetAllArea(ctx context.Context) ([]MasterArea, error) {
	rows, err := q.db.Query(ctx, getAllArea)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MasterArea
	for rows.Next() {
		var i MasterArea
		if err := rows.Scan(&i.ID, &i.Nama, &i.Slug); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllAreas = `-- name: GetAllAreas :many
SELECT id, nama, slug 
FROM master_area
ORDER BY nama ASC
`

func (q *Queries) GetAllAreas(ctx context.Context) ([]MasterArea, error) {
	rows, err := q.db.Query(ctx, getAllAreas)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MasterArea
	for rows.Next() {
		var i MasterArea
		if err := rows.Scan(&i.ID, &i.Nama, &i.Slug); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllBahanPokok = `-- name: GetAllBahanPokok :many
SELECT id, nama, slug, satuan, gambar_url 
FROM bahan_pokok 
WHERE ($3::text = '' OR nama ILIKE '%' || $3 || '%')
ORDER BY id ASC
LIMIT $1 OFFSET $2
`

type GetAllBahanPokokParams struct {
	Limit  int32
	Offset int32
	Nama   string
}

func (q *Queries) GetAllBahanPokok(ctx context.Context, arg GetAllBahanPokokParams) ([]BahanPokok, error) {
	rows, err := q.db.Query(ctx, getAllBahanPokok, arg.Limit, arg.Offset, arg.Nama)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BahanPokok
	for rows.Next() {
		var i BahanPokok
		if err := rows.Scan(
			&i.ID,
			&i.Nama,
			&i.Slug,
			&i.Satuan,
			&i.GambarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAreaBySlug = `-- name: GetAreaBySlug :one
SELECT id, nama, slug FROM master_area WHERE slug = $1 LIMIT 1
`

func (q *Queries) GetAreaBySlug(ctx context.Context, slug string) (MasterArea, error) {
	row := q.db.QueryRow(ctx, getAreaBySlug, slug)
	var i MasterArea
	err := row.Scan(&i.ID, &i.Nama, &i.Slug)
	return i, err
}

const getAreaIDByName = `-- name: GetAreaIDByName :one
SELECT id FROM master_area 
WHERE nama ILIKE '%' || $1::text || '%' 
LIMIT 1
`

func (q *Queries) GetAreaIDByName(ctx context.Context, nama string) (int32, error) {
	row := q.db.QueryRow(ctx, getAreaIDByName, nama)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const getBahanPokokByID = `-- name: GetBahanPokokByID :one
SELECT id, nama, slug, satuan, gambar_url
FROM bahan_pokok 
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetBahanPokokByID(ctx context.Context, id int32) (BahanPokok, error) {
	row := q.db.QueryRow(ctx, getBahanPokokByID, id)
	var i BahanPokok
	err := row.Scan(
		&i.ID,
		&i.Nama,
		&i.Slug,
		&i.Satuan,
		&i.GambarUrl,
	)
	return i, err
}

const getBahanPokokBySlug = `-- name: GetBahanPokokBySlug :one
SELECT id, nama, slug, satuan, gambar_url 
FROM bahan_pokok 
WHERE slug = $1 LIMIT 1
`

func (q *Queries) GetBahanPokokBySlug(ctx context.Context, slug string) (BahanPokok, error) {
	row := q.db.QueryRow(ctx, getBahanPokokBySlug, slug)
	var i BahanPokok
	err := row.Scan(
		&i.ID,
		&i.Nama,
		&i.Slug,
		&i.Satuan,
		&i.GambarUrl,
	)
	return i, err
}

const getBahanPokokIDByName = `-- name: GetBahanPokokIDByName :one
SELECT id FROM bahan_pokok 
WHERE nama ILIKE '%' || $1::text || '%' 
LIMIT 1
`

func (q *Queries) GetBahanPokokIDByName(ctx context.Context, nama string) (int32, error) {
	row := q.db.QueryRow(ctx, getBahanPokokIDByName, nama)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const getDaftarHargaArea = `-- name: GetDaftarHargaArea :many
SELECT ma.nama AS area, ma.slug AS area_slug, h.harga
FROM harga_harian h
JOIN master_area ma ON h.area_id = ma.id
WHERE h.bahan_pokok_id = $1 AND h.tanggal = $2
ORDER BY ma.nama ASC
`

type GetDaftarHargaAreaParams struct {
	BahanPokokID int32
	Tanggal      pgtype.Date
}

type GetDaftarHargaAreaRow struct {
	Area     string
	AreaSlug string
	Harga    int32
}

func (q *Queries) GetDaftarHargaArea(ctx context.Context, arg GetDaftarHargaAreaParams) ([]GetDaftarHargaAreaRow, error) {
	rows, err := q.db.Query(ctx, getDaftarHargaArea, arg.BahanPokokID, arg.Tanggal)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDaftarHargaAreaRow
	for rows.Next() {
		var i GetDaftarHargaAreaRow
		if err := rows.Scan(&i.Area, &i.AreaSlug, &i.Harga); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRataRataArea15Hari = `-- name: GetRataRataArea15Hari :many
SELECT ma.nama AS area, ma.slug AS area_slug, ROUND(AVG(h.harga))::int AS rata_rata_15_hari
FROM harga_harian h
JOIN master_area ma ON h.area_id = ma.id
WHERE h.bahan_pokok_id = $1 
  AND h.tanggal <= $2 
  AND h.tanggal > ($2::date - INTERVAL '15 days')
GROUP BY ma.id, ma.nama, ma.slug
ORDER BY rata_rata_15_hari DESC
`

type GetRataRataArea15HariParams struct {
	BahanPokokID int32
	Tanggal      pgtype.Date
}

type GetRataRataArea15HariRow struct {
	Area           string
	AreaSlug       string
	RataRata15Hari int32
}

func (q *Queries) GetRataRataArea15Hari(ctx context.Context, arg GetRataRataArea15HariParams) ([]GetRataRataArea15HariRow, error) {
	rows, err := q.db.Query(ctx, getRataRataArea15Hari, arg.BahanPokokID, arg.Tanggal)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRataRataArea15HariRow
	for rows.Next() {
		var i GetRataRataArea15HariRow
		if err := rows.Scan(&i.Area, &i.AreaSlug, &i.RataRata15Hari); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRiwayatHargaRataRata = `-- name: GetRiwayatHargaRataRata :many
SELECT tanggal, ROUND(AVG(harga))::int AS rata_rata_harga
FROM harga_harian
WHERE bahan_pokok_id = $1 
  AND tanggal <= $2
  AND tanggal > ($2::date - INTERVAL '30 days')
GROUP BY tanggal
ORDER BY tanggal ASC
`

type GetRiwayatHargaRataRataParams struct {
	BahanPokokID int32
	Tanggal      pgtype.Date
}

type GetRiwayatHargaRataRataRow struct {
	Tanggal       pgtype.Date
	RataRataHarga int32
}

func (q *Queries) GetRiwayatHargaRataRata(ctx context.Context, arg GetRiwayatHargaRataRataParams) ([]GetRiwayatHargaRataRataRow, error) {
	rows, err := q.db.Query(ctx, getRiwayatHargaRataRata, arg.BahanPokokID, arg.Tanggal)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRiwayatHargaRataRataRow
	for rows.Next() {
		var i GetRiwayatHargaRataRataRow
		if err := rows.Scan(&i.Tanggal, &i.RataRataHarga); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTanggalUpdateTerakhir = `-- name: GetTanggalUpdateTerakhir :one
SELECT tanggal 
FROM harga_harian 
WHERE bahan_pokok_id = $1 AND tanggal <= $2 
ORDER BY tanggal DESC LIMIT 1
`

type GetTanggalUpdateTerakhirParams struct {
	BahanPokokID int32
	Tanggal      pgtype.Date
}

func (q *Queries) GetTanggalUpdateTerakhir(ctx context.Context, arg GetTanggalUpdateTerakhirParams) (pgtype.Date, error) {
	row := q.db.QueryRow(ctx, getTanggalUpdateTerakhir, arg.BahanPokokID, arg.Tanggal)
	var tanggal pgtype.Date
	err := row.Scan(&tanggal)
	return tanggal, err
}

const getTotalBahanPokok = `-- name: GetTotalBahanPokok :one
SELECT count(*) 
FROM bahan_pokok
WHERE ($1::text = '' OR nama ILIKE '%' || $1 || '%')
`

func (q *Queries) GetTotalBahanPokok(ctx context.Context, nama string) (int64, error) {
	row := q.db.QueryRow(ctx, getTotalBahanPokok, nama)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getTrenSemuaBahanPokok = `-- name: GetTrenSemuaBahanPokok :many
SELECT 
    h_outer.bahan_pokok_id,
    h_outer.tanggal,
    ROUND(AVG(h_outer.harga))::int AS rata_rata_harga
FROM harga_harian h_outer
JOIN master_area ma ON h_outer.area_id = ma.id
WHERE h_outer.tanggal <= $1::date
  AND ($2::text = '' OR ma.slug = $2)
  AND (h_outer.bahan_pokok_id, h_outer.tanggal) IN (
    SELECT ranked.bahan_pokok_id, ranked.tanggal
    FROM (
        SELECT 
            h_inner.bahan_pokok_id, 
            h_inner.tanggal,
            DENSE_RANK() OVER (
                PARTITION BY h_inner.bahan_pokok_id 
                ORDER BY h_inner.tanggal DESC
            ) AS urutan
        FROM harga_harian h_inner
        JOIN master_area ma_inner ON h_inner.area_id = ma_inner.id
        WHERE h_inner.tanggal <= $1::date
          AND ($2::text = '' OR ma_inner.slug = $2)
    ) ranked
    WHERE ranked.urutan <= 2  
)
GROUP BY h_outer.bahan_pokok_id, h_outer.tanggal
ORDER BY h_outer.bahan_pokok_id ASC, h_outer.tanggal ASC
`

type GetTrenSemuaBahanPokokParams struct {
	Tanggal  pgtype.Date
	AreaSlug string
}

type GetTrenSemuaBahanPokokRow struct {
	BahanPokokID  int32
	Tanggal       pgtype.Date
	RataRataHarga int32
}

func (q *Queries) GetTrenSemuaBahanPokok(ctx context.Context, arg GetTrenSemuaBahanPokokParams) ([]GetTrenSemuaBahanPokokRow, error) {
	rows, err := q.db.Query(ctx, getTrenSemuaBahanPokok, arg.Tanggal, arg.AreaSlug)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTrenSemuaBahanPokokRow
	for rows.Next() {
		var i GetTrenSemuaBahanPokokRow
		if err := rows.Scan(&i.BahanPokokID, &i.Tanggal, &i.RataRataHarga); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTrenSemuaBahanPokokByArea = `-- name: GetTrenSemuaBahanPokokByArea :many
SELECT 
    h_outer.bahan_pokok_id,
    h_outer.tanggal,
    h_outer.harga AS rata_rata_harga
FROM harga_harian h_outer
JOIN master_area ma ON h_outer.area_id = ma.id
WHERE h_outer.tanggal <= $1::date
  AND ma.slug = $2
  AND (h_outer.bahan_pokok_id, h_outer.tanggal) IN (
    SELECT ranked.bahan_pokok_id, ranked.tanggal
    FROM (
        SELECT 
            h_inner.bahan_pokok_id, 
            h_inner.tanggal,
            DENSE_RANK() OVER (
                PARTITION BY h_inner.bahan_pokok_id 
                ORDER BY h_inner.tanggal DESC
            ) AS urutan
        FROM harga_harian h_inner
        JOIN master_area ma_inner ON h_inner.area_id = ma_inner.id
        WHERE h_inner.tanggal <= $1::date
          AND ma_inner.slug = $2
    ) ranked
    WHERE ranked.urutan <= 2  
)
ORDER BY h_outer.bahan_pokok_id ASC, h_outer.tanggal ASC
`

type GetTrenSemuaBahanPokokByAreaParams struct {
	Tanggal  pgtype.Date
	AreaSlug string
}

type GetTrenSemuaBahanPokokByAreaRow struct {
	BahanPokokID  int32
	Tanggal       pgtype.Date
	RataRataHarga int32
}

func (q *Queries) GetTrenSemuaBahanPokokByArea(ctx context.Context, arg GetTrenSemuaBahanPokokByAreaParams) ([]GetTrenSemuaBahanPokokByAreaRow, error) {
	rows, err := q.db.Query(ctx, getTrenSemuaBahanPokokByArea, arg.Tanggal, arg.AreaSlug)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTrenSemuaBahanPokokByAreaRow
	for rows.Next() {
		var i GetTrenSemuaBahanPokokByAreaRow
		if err := rows.Scan(&i.BahanPokokID, &i.Tanggal, &i.RataRataHarga); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBahanPokok = `-- name: UpdateBahanPokok :one
UPDATE bahan_pokok
SET nama = $2,
    slug = $3,
    satuan = $4,
    gambar_url = $5
WHERE id = $1
RETURNING id, nama, slug, satuan, gambar_url
`

type UpdateBahanPokokParams struct {
	ID        int32
	Nama      string
	Slug      string
	Satuan    string
	GambarUrl pgtype.Text
}

func (q *Queries) UpdateBahanPokok(ctx context.Context, arg UpdateBahanPokokParams) (BahanPokok, error) {
	row := q.db.QueryRow(ctx, updateBahanPokok,
		arg.ID,
		arg.Nama,
		arg.Slug,
		arg.Satuan,
		arg.GambarUrl,
	)
	var i BahanPokok
	err := row.Scan(
		&i.ID,
		&i.Nama,
		&i.Slug,
		&i.Satuan,
		&i.GambarUrl,
	)
	return i, err
}

const updateHargaHarian = `-- name: UpdateHargaHarian :one
UPDATE harga_harian SET harga = $2 WHERE id = $1
RETURNING id, bahan_pokok_id, area_id, harga, tanggal
`

type UpdateHargaHarianParams struct {
	ID    int32
	Harga int32
}

func (q *Queries) UpdateHargaHarian(ctx context.Context, arg UpdateHargaHarianParams) (HargaHarian, error) {
	row := q.db.QueryRow(ctx, updateHargaHarian, arg.ID, arg.Harga)
	var i HargaHarian
	err := row.Scan(
		&i.ID,
		&i.BahanPokokID,
		&i.AreaID,
		&i.Harga,
		&i.Tanggal,
	)
	return i, err
}
