// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: 001_queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countPenerima = `-- name: CountPenerima :one
SELECT COUNT(id)
FROM penerima
WHERE ($1::text IS NULL
       OR nama ILIKE '%' || $1::text || '%'
       OR nik  ILIKE '%' || $1::text || '%')
`

func (q *Queries) CountPenerima(ctx context.Context, keyword pgtype.Text) (int64, error) {
	row := q.db.QueryRow(ctx, countPenerima, keyword)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPenyaluran = `-- name: CountPenyaluran :one
SELECT COUNT(py.id)
FROM penyaluran py
WHERE ($1::int IS NULL OR py.program_id = $1::int)
  AND ($2::status_penyaluran_type IS NULL OR py.status = $2::status_penyaluran_type)
`

type CountPenyaluranParams struct {
	ProgramID pgtype.Int4              `json:"program_id"`
	Status    NullStatusPenyaluranType `json:"status"`
}

func (q *Queries) CountPenyaluran(ctx context.Context, arg CountPenyaluranParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPenyaluran, arg.ProgramID, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countProgram = `-- name: CountProgram :one
SELECT COUNT(id) FROM program_bansos
`

func (q *Queries) CountProgram(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countProgram)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPenerima = `-- name: CreatePenerima :one
INSERT INTO penerima (nik, nama, alamat)
VALUES ($1, $2, $3)
RETURNING id
`

type CreatePenerimaParams struct {
	Nik    string `json:"nik"`
	Nama   string `json:"nama"`
	Alamat string `json:"alamat"`
}

func (q *Queries) CreatePenerima(ctx context.Context, arg CreatePenerimaParams) (int32, error) {
	row := q.db.QueryRow(ctx, createPenerima, arg.Nik, arg.Nama, arg.Alamat)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const createPenyaluran = `-- name: CreatePenyaluran :one
INSERT INTO penyaluran (penerima_id, program_id, nominal, periode_mulai, periode_selesai, metode, status)
VALUES (
    $1, $2, $3,
    $4, $5,
    $6, $7
)
RETURNING id
`

type CreatePenyaluranParams struct {
	PenerimaID     int32                `json:"penerima_id"`
	ProgramID      int32                `json:"program_id"`
	Nominal        int32                `json:"nominal"`
	PeriodeMulai   pgtype.Date          `json:"periode_mulai"`
	PeriodeSelesai pgtype.Date          `json:"periode_selesai"`
	Metode         MetodePenyaluranType `json:"metode"`
	Status         StatusPenyaluranType `json:"status"`
}

func (q *Queries) CreatePenyaluran(ctx context.Context, arg CreatePenyaluranParams) (int32, error) {
	row := q.db.QueryRow(ctx, createPenyaluran,
		arg.PenerimaID,
		arg.ProgramID,
		arg.Nominal,
		arg.PeriodeMulai,
		arg.PeriodeSelesai,
		arg.Metode,
		arg.Status,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const createProgram = `-- name: CreateProgram :one
INSERT INTO program_bansos (nama, kode, deskripsi)
VALUES ($1, $2, $3)
RETURNING id
`

type CreateProgramParams struct {
	Nama      string      `json:"nama"`
	Kode      string      `json:"kode"`
	Deskripsi pgtype.Text `json:"deskripsi"`
}

func (q *Queries) CreateProgram(ctx context.Context, arg CreateProgramParams) (int32, error) {
	row := q.db.QueryRow(ctx, createProgram, arg.Nama, arg.Kode, arg.Deskripsi)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const deletePenerima = `-- name: DeletePenerima :exec
DELETE FROM penerima WHERE id = $1
`

func (q *Queries) DeletePenerima(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deletePenerima, id)
	return err
}

const deletePenyaluran = `-- name: DeletePenyaluran :exec
DELETE FROM penyaluran WHERE id = $1
`

func (q *Queries) DeletePenyaluran(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deletePenyaluran, id)
	return err
}

const deleteProgram = `-- name: DeleteProgram :exec
DELETE FROM program_bansos WHERE id = $1
`

func (q *Queries) DeleteProgram(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteProgram, id)
	return err
}

const getDetailPenyaluran = `-- name: GetDetailPenyaluran :one
SELECT
    py.id,
    py.nominal,
    py.periode_mulai,
    py.periode_selesai,
    py.metode,
    py.status,
    pb.nama      AS program_nama,
    pb.kode      AS program_kode,
    pb.deskripsi AS program_deskripsi
FROM penyaluran py
JOIN program_bansos pb ON pb.id = py.program_id
WHERE py.id = $1
LIMIT 1
`

type GetDetailPenyaluranRow struct {
	ID               int32                `json:"id"`
	Nominal          int32                `json:"nominal"`
	PeriodeMulai     pgtype.Date          `json:"periode_mulai"`
	PeriodeSelesai   pgtype.Date          `json:"periode_selesai"`
	Metode           MetodePenyaluranType `json:"metode"`
	Status           StatusPenyaluranType `json:"status"`
	ProgramNama      string               `json:"program_nama"`
	ProgramKode      string               `json:"program_kode"`
	ProgramDeskripsi pgtype.Text          `json:"program_deskripsi"`
}

// Dipakai: halaman Detail Bansos (nominal, periode, metode, status, deskripsi program)
func (q *Queries) GetDetailPenyaluran(ctx context.Context, id int32) (GetDetailPenyaluranRow, error) {
	row := q.db.QueryRow(ctx, getDetailPenyaluran, id)
	var i GetDetailPenyaluranRow
	err := row.Scan(
		&i.ID,
		&i.Nominal,
		&i.PeriodeMulai,
		&i.PeriodeSelesai,
		&i.Metode,
		&i.Status,
		&i.ProgramNama,
		&i.ProgramKode,
		&i.ProgramDeskripsi,
	)
	return i, err
}

const getPenerimaByID = `-- name: GetPenerimaByID :one
SELECT id, nik, nama, alamat
FROM penerima
WHERE id = $1
LIMIT 1
`

type GetPenerimaByIDRow struct {
	ID     int32  `json:"id"`
	Nik    string `json:"nik"`
	Nama   string `json:"nama"`
	Alamat string `json:"alamat"`
}

func (q *Queries) GetPenerimaByID(ctx context.Context, id int32) (GetPenerimaByIDRow, error) {
	row := q.db.QueryRow(ctx, getPenerimaByID, id)
	var i GetPenerimaByIDRow
	err := row.Scan(
		&i.ID,
		&i.Nik,
		&i.Nama,
		&i.Alamat,
	)
	return i, err
}

const getPenerimaByNIK = `-- name: GetPenerimaByNIK :one

SELECT id, nik, nama, alamat
FROM penerima
WHERE nik = $1
LIMIT 1
`

type GetPenerimaByNIKRow struct {
	ID     int32  `json:"id"`
	Nik    string `json:"nik"`
	Nama   string `json:"nama"`
	Alamat string `json:"alamat"`
}

// =====================================================================
// PENERIMA — PUBLIC
// =====================================================================
// Dipakai: validasi NIK dan tampilkan kartu identitas di Info Bansos
func (q *Queries) GetPenerimaByNIK(ctx context.Context, nik string) (GetPenerimaByNIKRow, error) {
	row := q.db.QueryRow(ctx, getPenerimaByNIK, nik)
	var i GetPenerimaByNIKRow
	err := row.Scan(
		&i.ID,
		&i.Nik,
		&i.Nama,
		&i.Alamat,
	)
	return i, err
}

const getPenyaluranByPenerima = `-- name: GetPenyaluranByPenerima :many

SELECT
    py.id,
    py.nominal,
    py.periode_mulai,
    py.periode_selesai,
    py.metode,
    py.status,
    pb.nama AS program_nama,
    pb.kode AS program_kode
FROM penyaluran py
JOIN program_bansos pb ON pb.id = py.program_id
WHERE py.penerima_id = $1
ORDER BY py.periode_selesai DESC
`

type GetPenyaluranByPenerimaRow struct {
	ID             int32                `json:"id"`
	Nominal        int32                `json:"nominal"`
	PeriodeMulai   pgtype.Date          `json:"periode_mulai"`
	PeriodeSelesai pgtype.Date          `json:"periode_selesai"`
	Metode         MetodePenyaluranType `json:"metode"`
	Status         StatusPenyaluranType `json:"status"`
	ProgramNama    string               `json:"program_nama"`
	ProgramKode    string               `json:"program_kode"`
}

// =====================================================================
// PENYALURAN — PUBLIC
// =====================================================================
// Dipakai: daftar bansos di halaman Info Bansos (list setelah lookup NIK)
func (q *Queries) GetPenyaluranByPenerima(ctx context.Context, penerimaID int32) ([]GetPenyaluranByPenerimaRow, error) {
	rows, err := q.db.Query(ctx, getPenyaluranByPenerima, penerimaID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPenyaluranByPenerimaRow
	for rows.Next() {
		var i GetPenyaluranByPenerimaRow
		if err := rows.Scan(
			&i.ID,
			&i.Nominal,
			&i.PeriodeMulai,
			&i.PeriodeSelesai,
			&i.Metode,
			&i.Status,
			&i.ProgramNama,
			&i.ProgramKode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProgramByID = `-- name: GetProgramByID :one
SELECT id, nama, kode, deskripsi, aktif
FROM program_bansos
WHERE id = $1
LIMIT 1
`

type GetProgramByIDRow struct {
	ID        int32       `json:"id"`
	Nama      string      `json:"nama"`
	Kode      string      `json:"kode"`
	Deskripsi pgtype.Text `json:"deskripsi"`
	Aktif     bool        `json:"aktif"`
}

func (q *Queries) GetProgramByID(ctx context.Context, id int32) (GetProgramByIDRow, error) {
	row := q.db.QueryRow(ctx, getProgramByID, id)
	var i GetProgramByIDRow
	err := row.Scan(
		&i.ID,
		&i.Nama,
		&i.Kode,
		&i.Deskripsi,
		&i.Aktif,
	)
	return i, err
}

const listPenerimaAdmin = `-- name: ListPenerimaAdmin :many

SELECT id, nik, nama, alamat
FROM penerima
WHERE ($1::text IS NULL
       OR nama ILIKE '%' || $1::text || '%'
       OR nik  ILIKE '%' || $1::text || '%')
ORDER BY nama
LIMIT $3 OFFSET $2
`

type ListPenerimaAdminParams struct {
	Keyword    pgtype.Text `json:"keyword"`
	OffsetData int32       `json:"offset_data"`
	LimitData  int32       `json:"limit_data"`
}

type ListPenerimaAdminRow struct {
	ID     int32  `json:"id"`
	Nik    string `json:"nik"`
	Nama   string `json:"nama"`
	Alamat string `json:"alamat"`
}

// =====================================================================
// PENERIMA — ADMIN
// =====================================================================
func (q *Queries) ListPenerimaAdmin(ctx context.Context, arg ListPenerimaAdminParams) ([]ListPenerimaAdminRow, error) {
	rows, err := q.db.Query(ctx, listPenerimaAdmin, arg.Keyword, arg.OffsetData, arg.LimitData)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPenerimaAdminRow
	for rows.Next() {
		var i ListPenerimaAdminRow
		if err := rows.Scan(
			&i.ID,
			&i.Nik,
			&i.Nama,
			&i.Alamat,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPenyaluranAdmin = `-- name: ListPenyaluranAdmin :many

SELECT
    py.id, py.nominal, py.periode_mulai, py.periode_selesai,
    py.metode, py.status, py.created_at,
    pn.nik   AS penerima_nik,
    pn.nama  AS penerima_nama,
    pb.nama  AS program_nama,
    pb.kode  AS program_kode
FROM penyaluran py
JOIN penerima      pn ON pn.id = py.penerima_id
JOIN program_bansos pb ON pb.id = py.program_id
WHERE ($1::int IS NULL OR py.program_id = $1::int)
  AND ($2::status_penyaluran_type IS NULL OR py.status = $2::status_penyaluran_type)
ORDER BY py.created_at DESC
LIMIT $4 OFFSET $3
`

type ListPenyaluranAdminParams struct {
	ProgramID  pgtype.Int4              `json:"program_id"`
	Status     NullStatusPenyaluranType `json:"status"`
	OffsetData int32                    `json:"offset_data"`
	LimitData  int32                    `json:"limit_data"`
}

type ListPenyaluranAdminRow struct {
	ID             int32                `json:"id"`
	Nominal        int32                `json:"nominal"`
	PeriodeMulai   pgtype.Date          `json:"periode_mulai"`
	PeriodeSelesai pgtype.Date          `json:"periode_selesai"`
	Metode         MetodePenyaluranType `json:"metode"`
	Status         StatusPenyaluranType `json:"status"`
	CreatedAt      pgtype.Timestamptz   `json:"created_at"`
	PenerimaNik    string               `json:"penerima_nik"`
	PenerimaNama   string               `json:"penerima_nama"`
	ProgramNama    string               `json:"program_nama"`
	ProgramKode    string               `json:"program_kode"`
}

// =====================================================================
// PENYALURAN — ADMIN
// =====================================================================
func (q *Queries) ListPenyaluranAdmin(ctx context.Context, arg ListPenyaluranAdminParams) ([]ListPenyaluranAdminRow, error) {
	rows, err := q.db.Query(ctx, listPenyaluranAdmin,
		arg.ProgramID,
		arg.Status,
		arg.OffsetData,
		arg.LimitData,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPenyaluranAdminRow
	for rows.Next() {
		var i ListPenyaluranAdminRow
		if err := rows.Scan(
			&i.ID,
			&i.Nominal,
			&i.PeriodeMulai,
			&i.PeriodeSelesai,
			&i.Metode,
			&i.Status,
			&i.CreatedAt,
			&i.PenerimaNik,
			&i.PenerimaNama,
			&i.ProgramNama,
			&i.ProgramKode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProgramAdmin = `-- name: ListProgramAdmin :many

SELECT id, nama, kode, deskripsi, aktif
FROM program_bansos
ORDER BY nama
LIMIT $2 OFFSET $1
`

type ListProgramAdminParams struct {
	OffsetData int32 `json:"offset_data"`
	LimitData  int32 `json:"limit_data"`
}

type ListProgramAdminRow struct {
	ID        int32       `json:"id"`
	Nama      string      `json:"nama"`
	Kode      string      `json:"kode"`
	Deskripsi pgtype.Text `json:"deskripsi"`
	Aktif     bool        `json:"aktif"`
}

// =====================================================================
// PROGRAM BANSOS — ADMIN
// =====================================================================
func (q *Queries) ListProgramAdmin(ctx context.Context, arg ListProgramAdminParams) ([]ListProgramAdminRow, error) {
	rows, err := q.db.Query(ctx, listProgramAdmin, arg.OffsetData, arg.LimitData)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProgramAdminRow
	for rows.Next() {
		var i ListProgramAdminRow
		if err := rows.Scan(
			&i.ID,
			&i.Nama,
			&i.Kode,
			&i.Deskripsi,
			&i.Aktif,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePenerima = `-- name: UpdatePenerima :exec
UPDATE penerima
SET nik = $1, nama = $2,
    alamat = $3, updated_at = CURRENT_TIMESTAMP
WHERE id = $4
`

type UpdatePenerimaParams struct {
	Nik    string `json:"nik"`
	Nama   string `json:"nama"`
	Alamat string `json:"alamat"`
	ID     int32  `json:"id"`
}

func (q *Queries) UpdatePenerima(ctx context.Context, arg UpdatePenerimaParams) error {
	_, err := q.db.Exec(ctx, updatePenerima,
		arg.Nik,
		arg.Nama,
		arg.Alamat,
		arg.ID,
	)
	return err
}

const updatePenyaluran = `-- name: UpdatePenyaluran :exec
UPDATE penyaluran
SET
    program_id      = $1,
    nominal         = $2,
    periode_mulai   = $3,
    periode_selesai = $4,
    metode          = $5,
    status          = $6,
    updated_at      = CURRENT_TIMESTAMP
WHERE id = $7
`

type UpdatePenyaluranParams struct {
	ProgramID      int32                `json:"program_id"`
	Nominal        int32                `json:"nominal"`
	PeriodeMulai   pgtype.Date          `json:"periode_mulai"`
	PeriodeSelesai pgtype.Date          `json:"periode_selesai"`
	Metode         MetodePenyaluranType `json:"metode"`
	Status         StatusPenyaluranType `json:"status"`
	ID             int32                `json:"id"`
}

func (q *Queries) UpdatePenyaluran(ctx context.Context, arg UpdatePenyaluranParams) error {
	_, err := q.db.Exec(ctx, updatePenyaluran,
		arg.ProgramID,
		arg.Nominal,
		arg.PeriodeMulai,
		arg.PeriodeSelesai,
		arg.Metode,
		arg.Status,
		arg.ID,
	)
	return err
}

const updateProgram = `-- name: UpdateProgram :exec
UPDATE program_bansos
SET
    nama      = $1,
    kode      = $2,
    deskripsi = $3,
    aktif     = $4,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $5
`

type UpdateProgramParams struct {
	Nama      string      `json:"nama"`
	Kode      string      `json:"kode"`
	Deskripsi pgtype.Text `json:"deskripsi"`
	Aktif     bool        `json:"aktif"`
	ID        int32       `json:"id"`
}

func (q *Queries) UpdateProgram(ctx context.Context, arg UpdateProgramParams) error {
	_, err := q.db.Exec(ctx, updateProgram,
		arg.Nama,
		arg.Kode,
		arg.Deskripsi,
		arg.Aktif,
		arg.ID,
	)
	return err
}

const updateStatusPenyaluran = `-- name: UpdateStatusPenyaluran :exec
UPDATE penyaluran
SET status = $1, updated_at = CURRENT_TIMESTAMP
WHERE id = $2
`

type UpdateStatusPenyaluranParams struct {
	Status StatusPenyaluranType `json:"status"`
	ID     int32                `json:"id"`
}

func (q *Queries) UpdateStatusPenyaluran(ctx context.Context, arg UpdateStatusPenyaluranParams) error {
	_, err := q.db.Exec(ctx, updateStatusPenyaluran, arg.Status, arg.ID)
	return err
}
