// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type MetodePenyaluranType string

const (
	MetodePenyaluranTypeTransferBri     MetodePenyaluranType = "transfer_bri"
	MetodePenyaluranTypeTransferBni     MetodePenyaluranType = "transfer_bni"
	MetodePenyaluranTypeTransferMandiri MetodePenyaluranType = "transfer_mandiri"
	MetodePenyaluranTypeTransferBca     MetodePenyaluranType = "transfer_bca"
	MetodePenyaluranTypeTransferPos     MetodePenyaluranType = "transfer_pos"
	MetodePenyaluranTypeTunai           MetodePenyaluranType = "tunai"
)

func (e *MetodePenyaluranType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MetodePenyaluranType(s)
	case string:
		*e = MetodePenyaluranType(s)
	default:
		return fmt.Errorf("unsupported scan type for MetodePenyaluranType: %T", src)
	}
	return nil
}

type NullMetodePenyaluranType struct {
	MetodePenyaluranType MetodePenyaluranType `json:"metode_penyaluran_type"`
	Valid                bool                 `json:"valid"` // Valid is true if MetodePenyaluranType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMetodePenyaluranType) Scan(value interface{}) error {
	if value == nil {
		ns.MetodePenyaluranType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MetodePenyaluranType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMetodePenyaluranType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MetodePenyaluranType), nil
}

type StatusPenyaluranType string

const (
	StatusPenyaluranTypeProses   StatusPenyaluranType = "proses"
	StatusPenyaluranTypeDiterima StatusPenyaluranType = "diterima"
	StatusPenyaluranTypeDitolak  StatusPenyaluranType = "ditolak"
)

func (e *StatusPenyaluranType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = StatusPenyaluranType(s)
	case string:
		*e = StatusPenyaluranType(s)
	default:
		return fmt.Errorf("unsupported scan type for StatusPenyaluranType: %T", src)
	}
	return nil
}

type NullStatusPenyaluranType struct {
	StatusPenyaluranType StatusPenyaluranType `json:"status_penyaluran_type"`
	Valid                bool                 `json:"valid"` // Valid is true if StatusPenyaluranType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullStatusPenyaluranType) Scan(value interface{}) error {
	if value == nil {
		ns.StatusPenyaluranType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.StatusPenyaluranType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullStatusPenyaluranType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.StatusPenyaluranType), nil
}

type Penerima struct {
	ID        int32              `json:"id"`
	Nik       string             `json:"nik"`
	Nama      string             `json:"nama"`
	Alamat    string             `json:"alamat"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Penyaluran struct {
	ID             int32                `json:"id"`
	PenerimaID     int32                `json:"penerima_id"`
	ProgramID      int32                `json:"program_id"`
	Nominal        int32                `json:"nominal"`
	PeriodeMulai   pgtype.Date          `json:"periode_mulai"`
	PeriodeSelesai pgtype.Date          `json:"periode_selesai"`
	Metode         MetodePenyaluranType `json:"metode"`
	Status         StatusPenyaluranType `json:"status"`
	CreatedAt      pgtype.Timestamptz   `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz   `json:"updated_at"`
}

type ProgramBanso struct {
	ID        int32              `json:"id"`
	Nama      string             `json:"nama"`
	Kode      string             `json:"kode"`
	Deskripsi pgtype.Text        `json:"deskripsi"`
	Aktif     bool               `json:"aktif"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}
