// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type MasterKela struct {
	ID        int32
	Nama      string
	Slug      string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Ruangan struct {
	ID        int32
	KelasID   int32
	Nama      string
	Slug      string
	Kapasitas int32
	Terisi    int32
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	Tersedia  pgtype.Int4
}
