// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countRuanganPublic = `-- name: CountRuanganPublic :one
SELECT COUNT(r.id) 
FROM ruangan r
JOIN master_kelas k ON r.kelas_id = k.id
WHERE 
    ($1::text = '' OR k.slug = $1::text)
    AND 
    ($2::text = '' OR r.nama ILIKE '%' || $2::text || '%')
`

type CountRuanganPublicParams struct {
	KelasSlug string
	Keyword   string
}

func (q *Queries) CountRuanganPublic(ctx context.Context, arg CountRuanganPublicParams) (int64, error) {
	row := q.db.QueryRow(ctx, countRuanganPublic, arg.KelasSlug, arg.Keyword)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSearchRuangan = `-- name: CountSearchRuangan :one
SELECT count(*)
FROM ruangan r
JOIN master_kelas k ON r.kelas_id = k.id
WHERE 
    ($1::text = '' OR r.nama ILIKE '%' || $1 || '%') AND
    ($2::text = '' OR k.slug = $2)
`

type CountSearchRuanganParams struct {
	Keyword   string
	KelasSlug string
}

func (q *Queries) CountSearchRuangan(ctx context.Context, arg CountSearchRuanganParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSearchRuangan, arg.Keyword, arg.KelasSlug)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createRuangan = `-- name: CreateRuangan :one

INSERT INTO ruangan (kelas_id, nama, slug, kapasitas, terisi)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, kelas_id, nama, slug, kapasitas, terisi, tersedia, created_at, updated_at
`

type CreateRuanganParams struct {
	KelasID   int32
	Nama      string
	Slug      string
	Kapasitas int32
	Terisi    int32
}

type CreateRuanganRow struct {
	ID        int32
	KelasID   int32
	Nama      string
	Slug      string
	Kapasitas int32
	Terisi    int32
	Tersedia  pgtype.Int4
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

// ==========================================
// ADMIN: CRUD RUANGAN
// ==========================================
func (q *Queries) CreateRuangan(ctx context.Context, arg CreateRuanganParams) (CreateRuanganRow, error) {
	row := q.db.QueryRow(ctx, createRuangan,
		arg.KelasID,
		arg.Nama,
		arg.Slug,
		arg.Kapasitas,
		arg.Terisi,
	)
	var i CreateRuanganRow
	err := row.Scan(
		&i.ID,
		&i.KelasID,
		&i.Nama,
		&i.Slug,
		&i.Kapasitas,
		&i.Terisi,
		&i.Tersedia,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteRuangan = `-- name: DeleteRuangan :exec
DELETE FROM ruangan
WHERE id = $1
`

func (q *Queries) DeleteRuangan(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteRuangan, id)
	return err
}

const getAllMasterKelas = `-- name: GetAllMasterKelas :many
SELECT id, nama, slug 
FROM master_kelas 
ORDER BY nama ASC
`

type GetAllMasterKelasRow struct {
	ID   int32
	Nama string
	Slug string
}

// Untuk tombol filter chips di UI
func (q *Queries) GetAllMasterKelas(ctx context.Context) ([]GetAllMasterKelasRow, error) {
	rows, err := q.db.Query(ctx, getAllMasterKelas)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllMasterKelasRow
	for rows.Next() {
		var i GetAllMasterKelasRow
		if err := rows.Scan(&i.ID, &i.Nama, &i.Slug); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMasterKelas = `-- name: GetMasterKelas :many
SELECT id, nama, slug FROM master_kelas ORDER BY id ASC
`

type GetMasterKelasRow struct {
	ID   int32
	Nama string
	Slug string
}

func (q *Queries) GetMasterKelas(ctx context.Context) ([]GetMasterKelasRow, error) {
	rows, err := q.db.Query(ctx, getMasterKelas)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMasterKelasRow
	for rows.Next() {
		var i GetMasterKelasRow
		if err := rows.Scan(&i.ID, &i.Nama, &i.Slug); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRuanganByID = `-- name: GetRuanganByID :one
SELECT 
    r.id, 
    r.kelas_id,
    k.nama AS kelas_nama,
    r.nama, 
    r.slug, 
    r.kapasitas, 
    r.terisi, 
    r.tersedia
FROM ruangan r
JOIN master_kelas k ON r.kelas_id = k.id
WHERE r.id = $1 LIMIT 1
`

type GetRuanganByIDRow struct {
	ID        int32
	KelasID   int32
	KelasNama string
	Nama      string
	Slug      string
	Kapasitas int32
	Terisi    int32
	Tersedia  pgtype.Int4
}

func (q *Queries) GetRuanganByID(ctx context.Context, id int32) (GetRuanganByIDRow, error) {
	row := q.db.QueryRow(ctx, getRuanganByID, id)
	var i GetRuanganByIDRow
	err := row.Scan(
		&i.ID,
		&i.KelasID,
		&i.KelasNama,
		&i.Nama,
		&i.Slug,
		&i.Kapasitas,
		&i.Terisi,
		&i.Tersedia,
	)
	return i, err
}

const getSummaryRuangan = `-- name: GetSummaryRuangan :one
SELECT 
    COALESCE(SUM(kapasitas), 0)::int AS total_kapasitas,
    COALESCE(SUM(tersedia), 0)::int AS total_tersedia
FROM ruangan
`

type GetSummaryRuanganRow struct {
	TotalKapasitas int32
	TotalTersedia  int32
}

func (q *Queries) GetSummaryRuangan(ctx context.Context) (GetSummaryRuanganRow, error) {
	row := q.db.QueryRow(ctx, getSummaryRuangan)
	var i GetSummaryRuanganRow
	err := row.Scan(&i.TotalKapasitas, &i.TotalTersedia)
	return i, err
}

const listRuanganPublic = `-- name: ListRuanganPublic :many
SELECT 
    r.id, 
    r.nama, 
    r.slug,
    r.kapasitas, 
    r.terisi, 
    r.tersedia,
    k.nama AS kelas_nama,
    k.slug AS kelas_slug
FROM ruangan r
JOIN master_kelas k ON r.kelas_id = k.id
WHERE 
    ($3::text = '' OR k.slug = $3::text)
    AND 
    ($4::text = '' OR r.nama ILIKE '%' || $4::text || '%')
ORDER BY r.nama ASC
LIMIT $2 OFFSET $1
`

type ListRuanganPublicParams struct {
	Offset    int32
	Limit     int32
	KelasSlug string
	Keyword   string
}

type ListRuanganPublicRow struct {
	ID        int32
	Nama      string
	Slug      string
	Kapasitas int32
	Terisi    int32
	Tersedia  pgtype.Int4
	KelasNama string
	KelasSlug string
}

func (q *Queries) ListRuanganPublic(ctx context.Context, arg ListRuanganPublicParams) ([]ListRuanganPublicRow, error) {
	rows, err := q.db.Query(ctx, listRuanganPublic,
		arg.Offset,
		arg.Limit,
		arg.KelasSlug,
		arg.Keyword,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRuanganPublicRow
	for rows.Next() {
		var i ListRuanganPublicRow
		if err := rows.Scan(
			&i.ID,
			&i.Nama,
			&i.Slug,
			&i.Kapasitas,
			&i.Terisi,
			&i.Tersedia,
			&i.KelasNama,
			&i.KelasSlug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchRuangan = `-- name: SearchRuangan :many
SELECT 
    r.id, 
    r.nama, 
    r.slug, 
    k.nama as kelas_nama, 
    k.slug as kelas_slug, 
    r.kapasitas, 
    r.terisi, 
    (r.kapasitas - r.terisi)::int as tersedia
FROM ruangan r
JOIN master_kelas k ON r.kelas_id = k.id
WHERE 
    ($1::text = '' OR r.nama ILIKE '%' || $1 || '%') AND
    ($2::text = '' OR k.slug = $2)
ORDER BY r.nama ASC
`

type SearchRuanganParams struct {
	Keyword   string
	KelasSlug string
}

type SearchRuanganRow struct {
	ID        int32
	Nama      string
	Slug      string
	KelasNama string
	KelasSlug string
	Kapasitas int32
	Terisi    int32
	Tersedia  int32
}

func (q *Queries) SearchRuangan(ctx context.Context, arg SearchRuanganParams) ([]SearchRuanganRow, error) {
	rows, err := q.db.Query(ctx, searchRuangan, arg.Keyword, arg.KelasSlug)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchRuanganRow
	for rows.Next() {
		var i SearchRuanganRow
		if err := rows.Scan(
			&i.ID,
			&i.Nama,
			&i.Slug,
			&i.KelasNama,
			&i.KelasSlug,
			&i.Kapasitas,
			&i.Terisi,
			&i.Tersedia,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRuangan = `-- name: UpdateRuangan :one
UPDATE ruangan
SET 
    kelas_id = $2,
    nama = $3,
    slug = $4,
    kapasitas = $5,
    terisi = $6
WHERE id = $1
RETURNING id, kelas_id, nama, slug, kapasitas, terisi, tersedia, created_at, updated_at
`

type UpdateRuanganParams struct {
	ID        int32
	KelasID   int32
	Nama      string
	Slug      string
	Kapasitas int32
	Terisi    int32
}

type UpdateRuanganRow struct {
	ID        int32
	KelasID   int32
	Nama      string
	Slug      string
	Kapasitas int32
	Terisi    int32
	Tersedia  pgtype.Int4
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) UpdateRuangan(ctx context.Context, arg UpdateRuanganParams) (UpdateRuanganRow, error) {
	row := q.db.QueryRow(ctx, updateRuangan,
		arg.ID,
		arg.KelasID,
		arg.Nama,
		arg.Slug,
		arg.Kapasitas,
		arg.Terisi,
	)
	var i UpdateRuanganRow
	err := row.Scan(
		&i.ID,
		&i.KelasID,
		&i.Nama,
		&i.Slug,
		&i.Kapasitas,
		&i.Terisi,
		&i.Tersedia,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
