// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type JenisDokumenType string

const (
	JenisDokumenTypePerda     JenisDokumenType = "perda"
	JenisDokumenTypePergub    JenisDokumenType = "pergub"
	JenisDokumenTypePeraturan JenisDokumenType = "peraturan"
	JenisDokumenTypePerdes    JenisDokumenType = "perdes"
	JenisDokumenTypeSkGub     JenisDokumenType = "sk_gub"
	JenisDokumenTypeInstruksi JenisDokumenType = "instruksi"
	JenisDokumenTypeSe        JenisDokumenType = "se"
	JenisDokumenTypeKeputusan JenisDokumenType = "keputusan"
)

func (e *JenisDokumenType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = JenisDokumenType(s)
	case string:
		*e = JenisDokumenType(s)
	default:
		return fmt.Errorf("unsupported scan type for JenisDokumenType: %T", src)
	}
	return nil
}

type NullJenisDokumenType struct {
	JenisDokumenType JenisDokumenType `json:"jenis_dokumen_type"`
	Valid            bool             `json:"valid"` // Valid is true if JenisDokumenType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullJenisDokumenType) Scan(value interface{}) error {
	if value == nil {
		ns.JenisDokumenType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.JenisDokumenType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullJenisDokumenType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.JenisDokumenType), nil
}

type StatusDokumenType string

const (
	StatusDokumenTypeBerlaku StatusDokumenType = "berlaku"
	StatusDokumenTypeDiubah  StatusDokumenType = "diubah"
	StatusDokumenTypeDicabut StatusDokumenType = "dicabut"
)

func (e *StatusDokumenType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = StatusDokumenType(s)
	case string:
		*e = StatusDokumenType(s)
	default:
		return fmt.Errorf("unsupported scan type for StatusDokumenType: %T", src)
	}
	return nil
}

type NullStatusDokumenType struct {
	StatusDokumenType StatusDokumenType `json:"status_dokumen_type"`
	Valid             bool              `json:"valid"` // Valid is true if StatusDokumenType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullStatusDokumenType) Scan(value interface{}) error {
	if value == nil {
		ns.StatusDokumenType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.StatusDokumenType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullStatusDokumenType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.StatusDokumenType), nil
}

type DokumenHukum struct {
	ID                 int32              `json:"id"`
	Jenis              JenisDokumenType   `json:"jenis"`
	Nomor              string             `json:"nomor"`
	Tahun              int16              `json:"tahun"`
	Judul              string             `json:"judul"`
	Ringkasan          pgtype.Text        `json:"ringkasan"`
	TanggalPenetapan   pgtype.Date        `json:"tanggal_penetapan"`
	Status             StatusDokumenType  `json:"status"`
	PdfUrl             string             `json:"pdf_url"`
	PdfSizeKb          pgtype.Int4        `json:"pdf_size_kb"`
	UrusanPemerintahan pgtype.Text        `json:"urusan_pemerintahan"`
	JumlahView         int32              `json:"jumlah_view"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type DokumenSubjek struct {
	DokumenID int32 `json:"dokumen_id"`
	SubjekID  int32 `json:"subjek_id"`
}

type Pengumuman struct {
	ID        int32              `json:"id"`
	Judul     string             `json:"judul"`
	Isi       pgtype.Text        `json:"isi"`
	Aktif     bool               `json:"aktif"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Subjek struct {
	ID   int32  `json:"id"`
	Nama string `json:"nama"`
}
