// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addSubjekToDokumen = `-- name: AddSubjekToDokumen :exec
INSERT INTO dokumen_subjek (dokumen_id, subjek_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddSubjekToDokumenParams struct {
	DokumenID int32 `json:"dokumen_id"`
	SubjekID  int32 `json:"subjek_id"`
}

func (q *Queries) AddSubjekToDokumen(ctx context.Context, arg AddSubjekToDokumenParams) error {
	_, err := q.db.Exec(ctx, addSubjekToDokumen, arg.DokumenID, arg.SubjekID)
	return err
}

const countAllDokumen = `-- name: CountAllDokumen :one
SELECT COUNT(id)
FROM dokumen_hukum
WHERE ($1::jenis_dokumen_type IS NULL OR jenis = $1::jenis_dokumen_type)
  AND ($2::smallint IS NULL OR tahun = $2::smallint)
`

type CountAllDokumenParams struct {
	Jenis NullJenisDokumenType `json:"jenis"`
	Tahun pgtype.Int2          `json:"tahun"`
}

func (q *Queries) CountAllDokumen(ctx context.Context, arg CountAllDokumenParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAllDokumen, arg.Jenis, arg.Tahun)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countDokumenByJenis = `-- name: CountDokumenByJenis :one
SELECT COUNT(id)
FROM dokumen_hukum
WHERE jenis = $1
  AND ($2::smallint IS NULL OR tahun = $2::smallint)
  AND ($3::text   IS NULL
       OR nomor ILIKE '%' || $3::text || '%'
       OR judul ILIKE '%' || $3::text || '%')
`

type CountDokumenByJenisParams struct {
	Jenis   JenisDokumenType `json:"jenis"`
	Tahun   pgtype.Int2      `json:"tahun"`
	Keyword pgtype.Text      `json:"keyword"`
}

func (q *Queries) CountDokumenByJenis(ctx context.Context, arg CountDokumenByJenisParams) (int64, error) {
	row := q.db.QueryRow(ctx, countDokumenByJenis, arg.Jenis, arg.Tahun, arg.Keyword)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPengumuman = `-- name: CountPengumuman :one
SELECT COUNT(id) FROM pengumuman
`

func (q *Queries) CountPengumuman(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countPengumuman)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSearchDokumen = `-- name: CountSearchDokumen :one
SELECT COUNT(id)
FROM dokumen_hukum
WHERE ($1::text    IS NULL OR judul ILIKE '%' || $1::text || '%')
  AND ($2::text      IS NULL OR nomor ILIKE '%' || $2::text || '%')
  AND ($3::smallint  IS NULL OR tahun = $3::smallint)
  AND ($4::jenis_dokumen_type IS NULL OR jenis = $4::jenis_dokumen_type)
`

type CountSearchDokumenParams struct {
	Keyword pgtype.Text          `json:"keyword"`
	Nomor   pgtype.Text          `json:"nomor"`
	Tahun   pgtype.Int2          `json:"tahun"`
	Jenis   NullJenisDokumenType `json:"jenis"`
}

func (q *Queries) CountSearchDokumen(ctx context.Context, arg CountSearchDokumenParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSearchDokumen,
		arg.Keyword,
		arg.Nomor,
		arg.Tahun,
		arg.Jenis,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDokumen = `-- name: CreateDokumen :one
INSERT INTO dokumen_hukum (
    jenis, nomor, tahun, judul, ringkasan, tanggal_penetapan,
    status, pdf_url, pdf_size_kb, urusan_pemerintahan
)
VALUES (
    $1, $2, $3,
    $4, $5, $6,
    $7, $8, $9,
    $10
)
RETURNING id
`

type CreateDokumenParams struct {
	Jenis              JenisDokumenType  `json:"jenis"`
	Nomor              string            `json:"nomor"`
	Tahun              int16             `json:"tahun"`
	Judul              string            `json:"judul"`
	Ringkasan          pgtype.Text       `json:"ringkasan"`
	TanggalPenetapan   pgtype.Date       `json:"tanggal_penetapan"`
	Status             StatusDokumenType `json:"status"`
	PdfUrl             string            `json:"pdf_url"`
	PdfSizeKb          pgtype.Int4       `json:"pdf_size_kb"`
	UrusanPemerintahan pgtype.Text       `json:"urusan_pemerintahan"`
}

func (q *Queries) CreateDokumen(ctx context.Context, arg CreateDokumenParams) (int32, error) {
	row := q.db.QueryRow(ctx, createDokumen,
		arg.Jenis,
		arg.Nomor,
		arg.Tahun,
		arg.Judul,
		arg.Ringkasan,
		arg.TanggalPenetapan,
		arg.Status,
		arg.PdfUrl,
		arg.PdfSizeKb,
		arg.UrusanPemerintahan,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const createPengumuman = `-- name: CreatePengumuman :one
INSERT INTO pengumuman (judul, isi)
VALUES ($1, $2)
RETURNING id
`

type CreatePengumumanParams struct {
	Judul string      `json:"judul"`
	Isi   pgtype.Text `json:"isi"`
}

func (q *Queries) CreatePengumuman(ctx context.Context, arg CreatePengumumanParams) (int32, error) {
	row := q.db.QueryRow(ctx, createPengumuman, arg.Judul, arg.Isi)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const deleteDokumen = `-- name: DeleteDokumen :exec
DELETE FROM dokumen_hukum WHERE id = $1
`

func (q *Queries) DeleteDokumen(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteDokumen, id)
	return err
}

const deletePengumuman = `-- name: DeletePengumuman :exec
DELETE FROM pengumuman WHERE id = $1
`

func (q *Queries) DeletePengumuman(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deletePengumuman, id)
	return err
}

const getDistinctTahunByJenis = `-- name: GetDistinctTahunByJenis :many
SELECT DISTINCT tahun
FROM dokumen_hukum
WHERE jenis = $1
ORDER BY tahun DESC
`

// Dipakai: tab filter tahun di halaman Akses Cepat
func (q *Queries) GetDistinctTahunByJenis(ctx context.Context, jenis JenisDokumenType) ([]int16, error) {
	rows, err := q.db.Query(ctx, getDistinctTahunByJenis, jenis)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int16
	for rows.Next() {
		var tahun int16
		if err := rows.Scan(&tahun); err != nil {
			return nil, err
		}
		items = append(items, tahun)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDokumenByID = `-- name: GetDokumenByID :one
SELECT id, jenis, nomor, tahun, judul, ringkasan, tanggal_penetapan, status,
       pdf_url, pdf_size_kb, urusan_pemerintahan, jumlah_view
FROM dokumen_hukum
WHERE id = $1
LIMIT 1
`

type GetDokumenByIDRow struct {
	ID                 int32             `json:"id"`
	Jenis              JenisDokumenType  `json:"jenis"`
	Nomor              string            `json:"nomor"`
	Tahun              int16             `json:"tahun"`
	Judul              string            `json:"judul"`
	Ringkasan          pgtype.Text       `json:"ringkasan"`
	TanggalPenetapan   pgtype.Date       `json:"tanggal_penetapan"`
	Status             StatusDokumenType `json:"status"`
	PdfUrl             string            `json:"pdf_url"`
	PdfSizeKb          pgtype.Int4       `json:"pdf_size_kb"`
	UrusanPemerintahan pgtype.Text       `json:"urusan_pemerintahan"`
	JumlahView         int32             `json:"jumlah_view"`
}

func (q *Queries) GetDokumenByID(ctx context.Context, id int32) (GetDokumenByIDRow, error) {
	row := q.db.QueryRow(ctx, getDokumenByID, id)
	var i GetDokumenByIDRow
	err := row.Scan(
		&i.ID,
		&i.Jenis,
		&i.Nomor,
		&i.Tahun,
		&i.Judul,
		&i.Ringkasan,
		&i.TanggalPenetapan,
		&i.Status,
		&i.PdfUrl,
		&i.PdfSizeKb,
		&i.UrusanPemerintahan,
		&i.JumlahView,
	)
	return i, err
}

const getOrCreateSubjek = `-- name: GetOrCreateSubjek :one

INSERT INTO subjek (nama)
VALUES ($1)
ON CONFLICT (nama) DO UPDATE SET nama = EXCLUDED.nama
RETURNING id, nama
`

// =====================================================================
// SUBJEK — ADMIN
// =====================================================================
func (q *Queries) GetOrCreateSubjek(ctx context.Context, nama string) (Subjek, error) {
	row := q.db.QueryRow(ctx, getOrCreateSubjek, nama)
	var i Subjek
	err := row.Scan(&i.ID, &i.Nama)
	return i, err
}

const getSubjekByDokumen = `-- name: GetSubjekByDokumen :many
SELECT s.id, s.nama
FROM subjek s
JOIN dokumen_subjek ds ON ds.subjek_id = s.id
WHERE ds.dokumen_id = $1
ORDER BY s.nama
`

// Dipakai: bagian SUBJEK di Detail Dokumen
func (q *Queries) GetSubjekByDokumen(ctx context.Context, dokumenID int32) ([]Subjek, error) {
	rows, err := q.db.Query(ctx, getSubjekByDokumen, dokumenID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Subjek
	for rows.Next() {
		var i Subjek
		if err := rows.Scan(&i.ID, &i.Nama); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const incrementView = `-- name: IncrementView :exec
UPDATE dokumen_hukum
SET jumlah_view = jumlah_view + 1
WHERE id = $1
`

func (q *Queries) IncrementView(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, incrementView, id)
	return err
}

const listAllDokumenAdmin = `-- name: ListAllDokumenAdmin :many

SELECT id, jenis, nomor, tahun, judul, tanggal_penetapan, status, jumlah_view
FROM dokumen_hukum
WHERE ($1::jenis_dokumen_type IS NULL OR jenis = $1::jenis_dokumen_type)
  AND ($2::smallint IS NULL OR tahun = $2::smallint)
ORDER BY created_at DESC
LIMIT $4 OFFSET $3
`

type ListAllDokumenAdminParams struct {
	Jenis      NullJenisDokumenType `json:"jenis"`
	Tahun      pgtype.Int2          `json:"tahun"`
	OffsetData int32                `json:"offset_data"`
	LimitData  int32                `json:"limit_data"`
}

type ListAllDokumenAdminRow struct {
	ID               int32             `json:"id"`
	Jenis            JenisDokumenType  `json:"jenis"`
	Nomor            string            `json:"nomor"`
	Tahun            int16             `json:"tahun"`
	Judul            string            `json:"judul"`
	TanggalPenetapan pgtype.Date       `json:"tanggal_penetapan"`
	Status           StatusDokumenType `json:"status"`
	JumlahView       int32             `json:"jumlah_view"`
}

// =====================================================================
// DOKUMEN HUKUM — ADMIN
// =====================================================================
func (q *Queries) ListAllDokumenAdmin(ctx context.Context, arg ListAllDokumenAdminParams) ([]ListAllDokumenAdminRow, error) {
	rows, err := q.db.Query(ctx, listAllDokumenAdmin,
		arg.Jenis,
		arg.Tahun,
		arg.OffsetData,
		arg.LimitData,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllDokumenAdminRow
	for rows.Next() {
		var i ListAllDokumenAdminRow
		if err := rows.Scan(
			&i.ID,
			&i.Jenis,
			&i.Nomor,
			&i.Tahun,
			&i.Judul,
			&i.TanggalPenetapan,
			&i.Status,
			&i.JumlahView,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDokumenByJenis = `-- name: ListDokumenByJenis :many
SELECT id, nomor, tahun, judul, tanggal_penetapan, status, pdf_url, pdf_size_kb
FROM dokumen_hukum
WHERE jenis = $1
  AND ($2::smallint IS NULL OR tahun = $2::smallint)
  AND ($3::text   IS NULL
       OR nomor ILIKE '%' || $3::text || '%'
       OR judul ILIKE '%' || $3::text || '%')
ORDER BY tanggal_penetapan DESC
LIMIT $5 OFFSET $4
`

type ListDokumenByJenisParams struct {
	Jenis      JenisDokumenType `json:"jenis"`
	Tahun      pgtype.Int2      `json:"tahun"`
	Keyword    pgtype.Text      `json:"keyword"`
	OffsetData int32            `json:"offset_data"`
	LimitData  int32            `json:"limit_data"`
}

type ListDokumenByJenisRow struct {
	ID               int32             `json:"id"`
	Nomor            string            `json:"nomor"`
	Tahun            int16             `json:"tahun"`
	Judul            string            `json:"judul"`
	TanggalPenetapan pgtype.Date       `json:"tanggal_penetapan"`
	Status           StatusDokumenType `json:"status"`
	PdfUrl           string            `json:"pdf_url"`
	PdfSizeKb        pgtype.Int4       `json:"pdf_size_kb"`
}

// Dipakai: halaman Akses Cepat per jenis (search nomor/judul + filter tahun)
func (q *Queries) ListDokumenByJenis(ctx context.Context, arg ListDokumenByJenisParams) ([]ListDokumenByJenisRow, error) {
	rows, err := q.db.Query(ctx, listDokumenByJenis,
		arg.Jenis,
		arg.Tahun,
		arg.Keyword,
		arg.OffsetData,
		arg.LimitData,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDokumenByJenisRow
	for rows.Next() {
		var i ListDokumenByJenisRow
		if err := rows.Scan(
			&i.ID,
			&i.Nomor,
			&i.Tahun,
			&i.Judul,
			&i.TanggalPenetapan,
			&i.Status,
			&i.PdfUrl,
			&i.PdfSizeKb,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPengumumanAdmin = `-- name: ListPengumumanAdmin :many

SELECT id, judul, isi, aktif, created_at
FROM pengumuman
ORDER BY created_at DESC
LIMIT $2 OFFSET $1
`

type ListPengumumanAdminParams struct {
	OffsetData int32 `json:"offset_data"`
	LimitData  int32 `json:"limit_data"`
}

type ListPengumumanAdminRow struct {
	ID        int32              `json:"id"`
	Judul     string             `json:"judul"`
	Isi       pgtype.Text        `json:"isi"`
	Aktif     bool               `json:"aktif"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

// =====================================================================
// PENGUMUMAN — ADMIN
// =====================================================================
func (q *Queries) ListPengumumanAdmin(ctx context.Context, arg ListPengumumanAdminParams) ([]ListPengumumanAdminRow, error) {
	rows, err := q.db.Query(ctx, listPengumumanAdmin, arg.OffsetData, arg.LimitData)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPengumumanAdminRow
	for rows.Next() {
		var i ListPengumumanAdminRow
		if err := rows.Scan(
			&i.ID,
			&i.Judul,
			&i.Isi,
			&i.Aktif,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPengumumanTerbaru = `-- name: ListPengumumanTerbaru :many

SELECT id, judul, isi, created_at
FROM pengumuman
WHERE aktif = true
ORDER BY created_at DESC
LIMIT $1
`

type ListPengumumanTerbaruRow struct {
	ID        int32              `json:"id"`
	Judul     string             `json:"judul"`
	Isi       pgtype.Text        `json:"isi"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

// =====================================================================
// PENGUMUMAN — PUBLIC
// =====================================================================
// Dipakai: carousel TERBARU di homepage
func (q *Queries) ListPengumumanTerbaru(ctx context.Context, limitData int32) ([]ListPengumumanTerbaruRow, error) {
	rows, err := q.db.Query(ctx, listPengumumanTerbaru, limitData)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPengumumanTerbaruRow
	for rows.Next() {
		var i ListPengumumanTerbaruRow
		if err := rows.Scan(
			&i.ID,
			&i.Judul,
			&i.Isi,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeAllSubjekFromDokumen = `-- name: RemoveAllSubjekFromDokumen :exec
DELETE FROM dokumen_subjek WHERE dokumen_id = $1
`

func (q *Queries) RemoveAllSubjekFromDokumen(ctx context.Context, dokumenID int32) error {
	_, err := q.db.Exec(ctx, removeAllSubjekFromDokumen, dokumenID)
	return err
}

const removeSubjekFromDokumen = `-- name: RemoveSubjekFromDokumen :exec
DELETE FROM dokumen_subjek
WHERE dokumen_id = $1
  AND subjek_id  = $2
`

type RemoveSubjekFromDokumenParams struct {
	DokumenID int32 `json:"dokumen_id"`
	SubjekID  int32 `json:"subjek_id"`
}

func (q *Queries) RemoveSubjekFromDokumen(ctx context.Context, arg RemoveSubjekFromDokumenParams) error {
	_, err := q.db.Exec(ctx, removeSubjekFromDokumen, arg.DokumenID, arg.SubjekID)
	return err
}

const searchDokumenPopuler = `-- name: SearchDokumenPopuler :many
SELECT id, jenis, nomor, tahun, judul, ringkasan, tanggal_penetapan, status, jumlah_view
FROM dokumen_hukum
WHERE ($1::text    IS NULL OR judul ILIKE '%' || $1::text || '%')
  AND ($2::text      IS NULL OR nomor ILIKE '%' || $2::text || '%')
  AND ($3::smallint  IS NULL OR tahun = $3::smallint)
  AND ($4::jenis_dokumen_type IS NULL OR jenis = $4::jenis_dokumen_type)
ORDER BY jumlah_view DESC, tanggal_penetapan DESC
LIMIT $6 OFFSET $5
`

type SearchDokumenPopulerParams struct {
	Keyword    pgtype.Text          `json:"keyword"`
	Nomor      pgtype.Text          `json:"nomor"`
	Tahun      pgtype.Int2          `json:"tahun"`
	Jenis      NullJenisDokumenType `json:"jenis"`
	OffsetData int32                `json:"offset_data"`
	LimitData  int32                `json:"limit_data"`
}

type SearchDokumenPopulerRow struct {
	ID               int32             `json:"id"`
	Jenis            JenisDokumenType  `json:"jenis"`
	Nomor            string            `json:"nomor"`
	Tahun            int16             `json:"tahun"`
	Judul            string            `json:"judul"`
	Ringkasan        pgtype.Text       `json:"ringkasan"`
	TanggalPenetapan pgtype.Date       `json:"tanggal_penetapan"`
	Status           StatusDokumenType `json:"status"`
	JumlahView       int32             `json:"jumlah_view"`
}

// Dipakai: halaman Hasil Pencarian, sort Populer
func (q *Queries) SearchDokumenPopuler(ctx context.Context, arg SearchDokumenPopulerParams) ([]SearchDokumenPopulerRow, error) {
	rows, err := q.db.Query(ctx, searchDokumenPopuler,
		arg.Keyword,
		arg.Nomor,
		arg.Tahun,
		arg.Jenis,
		arg.OffsetData,
		arg.LimitData,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchDokumenPopulerRow
	for rows.Next() {
		var i SearchDokumenPopulerRow
		if err := rows.Scan(
			&i.ID,
			&i.Jenis,
			&i.Nomor,
			&i.Tahun,
			&i.Judul,
			&i.Ringkasan,
			&i.TanggalPenetapan,
			&i.Status,
			&i.JumlahView,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchDokumenTerbaru = `-- name: SearchDokumenTerbaru :many

SELECT id, jenis, nomor, tahun, judul, ringkasan, tanggal_penetapan, status, jumlah_view
FROM dokumen_hukum
WHERE ($1::text    IS NULL OR judul ILIKE '%' || $1::text || '%')
  AND ($2::text      IS NULL OR nomor ILIKE '%' || $2::text || '%')
  AND ($3::smallint  IS NULL OR tahun = $3::smallint)
  AND ($4::jenis_dokumen_type IS NULL OR jenis = $4::jenis_dokumen_type)
ORDER BY tanggal_penetapan DESC
LIMIT $6 OFFSET $5
`

type SearchDokumenTerbaruParams struct {
	Keyword    pgtype.Text          `json:"keyword"`
	Nomor      pgtype.Text          `json:"nomor"`
	Tahun      pgtype.Int2          `json:"tahun"`
	Jenis      NullJenisDokumenType `json:"jenis"`
	OffsetData int32                `json:"offset_data"`
	LimitData  int32                `json:"limit_data"`
}

type SearchDokumenTerbaruRow struct {
	ID               int32             `json:"id"`
	Jenis            JenisDokumenType  `json:"jenis"`
	Nomor            string            `json:"nomor"`
	Tahun            int16             `json:"tahun"`
	Judul            string            `json:"judul"`
	Ringkasan        pgtype.Text       `json:"ringkasan"`
	TanggalPenetapan pgtype.Date       `json:"tanggal_penetapan"`
	Status           StatusDokumenType `json:"status"`
	JumlahView       int32             `json:"jumlah_view"`
}

// =====================================================================
// DOKUMEN HUKUM — PUBLIC
// =====================================================================
// Dipakai: halaman Hasil Pencarian, sort Terbaru
func (q *Queries) SearchDokumenTerbaru(ctx context.Context, arg SearchDokumenTerbaruParams) ([]SearchDokumenTerbaruRow, error) {
	rows, err := q.db.Query(ctx, searchDokumenTerbaru,
		arg.Keyword,
		arg.Nomor,
		arg.Tahun,
		arg.Jenis,
		arg.OffsetData,
		arg.LimitData,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchDokumenTerbaruRow
	for rows.Next() {
		var i SearchDokumenTerbaruRow
		if err := rows.Scan(
			&i.ID,
			&i.Jenis,
			&i.Nomor,
			&i.Tahun,
			&i.Judul,
			&i.Ringkasan,
			&i.TanggalPenetapan,
			&i.Status,
			&i.JumlahView,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDokumen = `-- name: UpdateDokumen :exec
UPDATE dokumen_hukum
SET
    jenis               = $1,
    nomor               = $2,
    tahun               = $3,
    judul               = $4,
    ringkasan           = $5,
    tanggal_penetapan   = $6,
    status              = $7,
    pdf_url             = $8,
    pdf_size_kb         = $9,
    urusan_pemerintahan = $10,
    updated_at          = CURRENT_TIMESTAMP
WHERE id = $11
`

type UpdateDokumenParams struct {
	Jenis              JenisDokumenType  `json:"jenis"`
	Nomor              string            `json:"nomor"`
	Tahun              int16             `json:"tahun"`
	Judul              string            `json:"judul"`
	Ringkasan          pgtype.Text       `json:"ringkasan"`
	TanggalPenetapan   pgtype.Date       `json:"tanggal_penetapan"`
	Status             StatusDokumenType `json:"status"`
	PdfUrl             string            `json:"pdf_url"`
	PdfSizeKb          pgtype.Int4       `json:"pdf_size_kb"`
	UrusanPemerintahan pgtype.Text       `json:"urusan_pemerintahan"`
	ID                 int32             `json:"id"`
}

func (q *Queries) UpdateDokumen(ctx context.Context, arg UpdateDokumenParams) error {
	_, err := q.db.Exec(ctx, updateDokumen,
		arg.Jenis,
		arg.Nomor,
		arg.Tahun,
		arg.Judul,
		arg.Ringkasan,
		arg.TanggalPenetapan,
		arg.Status,
		arg.PdfUrl,
		arg.PdfSizeKb,
		arg.UrusanPemerintahan,
		arg.ID,
	)
	return err
}

const updatePengumuman = `-- name: UpdatePengumuman :exec
UPDATE pengumuman
SET judul = $1, isi = $2,
    aktif = $3, updated_at = CURRENT_TIMESTAMP
WHERE id = $4
`

type UpdatePengumumanParams struct {
	Judul string      `json:"judul"`
	Isi   pgtype.Text `json:"isi"`
	Aktif bool        `json:"aktif"`
	ID    int32       `json:"id"`
}

func (q *Queries) UpdatePengumuman(ctx context.Context, arg UpdatePengumumanParams) error {
	_, err := q.db.Exec(ctx, updatePengumuman,
		arg.Judul,
		arg.Isi,
		arg.Aktif,
		arg.ID,
	)
	return err
}
