-- =============================================================================
-- SEED DATA: MASTER AREA
-- =============================================================================
INSERT INTO master_area (nama, slug) VALUES 
    ('Bangkalan', 'bangkalan'),
    ('Banyuwangi', 'banyuwangi'),
    ('Bojonegoro', 'bojonegoro'),
    ('Bondowoso', 'bondowoso'),
    ('Gresik', 'gresik'),
    ('Jember', 'jember'),
    ('Jombang', 'jombang'),
    ('Lamongan', 'lamongan'),
    ('Lumajang', 'lumajang'),
    ('Magetan', 'magetan'),
    ('Nganjuk', 'nganjuk'),
    ('Ngawi', 'ngawi'),
    ('Pacitan', 'pacitan'),
    ('Pamekasan', 'pamekasan'),
    ('Ponorogo', 'ponorogo'),
    ('Sampang', 'sampang'),
    ('Sidoarjo', 'sidoarjo'),
    ('Situbondo', 'situbondo'),
    ('Sumenep', 'sumenep'),
    ('Surabaya', 'surabaya'),
    ('Trenggalek', 'trenggalek'),
    ('Tuban', 'tuban'),
    ('Tulungagung', 'tulungagung'),
    ('Batu', 'batu'),
    ('Blitar', 'blitar'),
    ('Kabupaten Blitar', 'kab-blitar'),
    ('Kediri', 'kediri'),
    ('Kabupaten Kediri', 'kab-kediri'),
    ('Madiun', 'madiun'),
    ('Kabupaten Madiun', 'kab-madiun'),
    ('Malang', 'malang'),
    ('Kabupaten Malang', 'kab-malang'),
    ('Mojokerto', 'mojokerto'),
    ('Kabupaten Mojokerto', 'kab-mojokerto'),
    ('Pasuruan', 'pasuruan'),
    ('Kabupaten Pasuruan', 'kab-pasuruan'),
    ('Probolinggo', 'probolinggo'),
    ('Kabupaten Probolinggo', 'kab-probolinggo')
ON CONFLICT (slug) DO NOTHING;

-- =============================================================================
-- SEED DATA: BAHAN POKOK
-- =============================================================================
INSERT INTO bahan_pokok (nama, slug, satuan, gambar_url) VALUES 
    ('Bawang Merah / Kg', 'bawang-merah', 'kg', 'https://nhsdrdhzkogczngslvvh.supabase.co/storage/v1/object/public/image-asset/siskaperbapo/bawang-merah.webp'),
    ('Beras Medium / Kg', 'beras-medium', 'kg', 'https://nhsdrdhzkogczngslvvh.supabase.co/storage/v1/object/public/image-asset/siskaperbapo/beras-premium.webp'),
    ('Bawang Putih / Kg', 'bawang-putih', 'kg', 'https://nhsdrdhzkogczngslvvh.supabase.co/storage/v1/object/public/image-asset/siskaperbapo/bawang-putih.webp'),
    ('Cabai Rawit / Kg', 'cabai-rawit', 'kg', 'https://nhsdrdhzkogczngslvvh.supabase.co/storage/v1/object/public/image-asset/siskaperbapo/cabai-rawit.webp'),
    ('Cabai Merah / Kg', 'cabai-merah', 'kg', 'https://nhsdrdhzkogczngslvvh.supabase.co/storage/v1/object/public/image-asset/siskaperbapo/cabe-merah.webp'),
    ('Tepung Terigu / Kg', 'tepung-terigu', 'kg', 'https://nhsdrdhzkogczngslvvh.supabase.co/storage/v1/object/public/image-asset/siskaperbapo/tepung-terigu.webp')
ON CONFLICT (slug) DO NOTHING;


INSERT INTO harga_harian (bahan_pokok_id, area_id, harga, tanggal) VALUES

-- BAWANG MERAH
((SELECT id FROM bahan_pokok WHERE slug='bawang-merah'),(SELECT id FROM master_area WHERE slug='surabaya'),28000,'2026-05-10'),
((SELECT id FROM bahan_pokok WHERE slug='bawang-merah'),(SELECT id FROM master_area WHERE slug='malang'),27500,'2026-05-10'),
((SELECT id FROM bahan_pokok WHERE slug='bawang-merah'),(SELECT id FROM master_area WHERE slug='sidoarjo'),28500,'2026-05-10'),
((SELECT id FROM bahan_pokok WHERE slug='bawang-merah'),(SELECT id FROM master_area WHERE slug='gresik'),27000,'2026-05-10'),
((SELECT id FROM bahan_pokok WHERE slug='bawang-merah'),(SELECT id FROM master_area WHERE slug='jombang'),26000,'2026-05-10'),
((SELECT id FROM bahan_pokok WHERE slug='bawang-merah'),(SELECT id FROM master_area WHERE slug='kediri'),25500,'2026-05-10'),
((SELECT id FROM bahan_pokok WHERE slug='bawang-merah'),(SELECT id FROM master_area WHERE slug='madiun'),26500,'2026-05-10'),
((SELECT id FROM bahan_pokok WHERE slug='bawang-merah'),(SELECT id FROM master_area WHERE slug='jember'),27000,'2026-05-10'),
((SELECT id FROM bahan_pokok WHERE slug='bawang-merah'),(SELECT id FROM master_area WHERE slug='lamongan'),26000,'2026-05-10'),
((SELECT id FROM bahan_pokok WHERE slug='bawang-merah'),(SELECT id FROM master_area WHERE slug='banyuwangi'),27500,'2026-05-10'),
((SELECT id FROM bahan_pokok WHERE slug='bawang-merah'),(SELECT id FROM master_area WHERE slug='surabaya'),29000,'2026-05-17'),
((SELECT id FROM bahan_pokok WHERE slug='bawang-merah'),(SELECT id FROM master_area WHERE slug='malang'),28000,'2026-05-17'),
((SELECT id FROM bahan_pokok WHERE slug='bawang-merah'),(SELECT id FROM master_area WHERE slug='sidoarjo'),29500,'2026-05-17'),
((SELECT id FROM bahan_pokok WHERE slug='bawang-merah'),(SELECT id FROM master_area WHERE slug='gresik'),28000,'2026-05-17'),
((SELECT id FROM bahan_pokok WHERE slug='bawang-merah'),(SELECT id FROM master_area WHERE slug='jombang'),27000,'2026-05-17'),
((SELECT id FROM bahan_pokok WHERE slug='bawang-merah'),(SELECT id FROM master_area WHERE slug='kediri'),26500,'2026-05-17'),
((SELECT id FROM bahan_pokok WHERE slug='bawang-merah'),(SELECT id FROM master_area WHERE slug='madiun'),27500,'2026-05-17'),
((SELECT id FROM bahan_pokok WHERE slug='bawang-merah'),(SELECT id FROM master_area WHERE slug='jember'),28000,'2026-05-17'),
((SELECT id FROM bahan_pokok WHERE slug='bawang-merah'),(SELECT id FROM master_area WHERE slug='lamongan'),27000,'2026-05-17'),
((SELECT id FROM bahan_pokok WHERE slug='bawang-merah'),(SELECT id FROM master_area WHERE slug='banyuwangi'),28500,'2026-05-17'),
((SELECT id FROM bahan_pokok WHERE slug='bawang-merah'),(SELECT id FROM master_area WHERE slug='surabaya'),30000,'2026-05-24'),
((SELECT id FROM bahan_pokok WHERE slug='bawang-merah'),(SELECT id FROM master_area WHERE slug='malang'),29000,'2026-05-24'),
((SELECT id FROM bahan_pokok WHERE slug='bawang-merah'),(SELECT id FROM master_area WHERE slug='sidoarjo'),30500,'2026-05-24'),
((SELECT id FROM bahan_pokok WHERE slug='bawang-merah'),(SELECT id FROM master_area WHERE slug='gresik'),29000,'2026-05-24'),
((SELECT id FROM bahan_pokok WHERE slug='bawang-merah'),(SELECT id FROM master_area WHERE slug='jombang'),28000,'2026-05-24'),
((SELECT id FROM bahan_pokok WHERE slug='bawang-merah'),(SELECT id FROM master_area WHERE slug='kediri'),27500,'2026-05-24'),
((SELECT id FROM bahan_pokok WHERE slug='bawang-merah'),(SELECT id FROM master_area WHERE slug='madiun'),28500,'2026-05-24'),
((SELECT id FROM bahan_pokok WHERE slug='bawang-merah'),(SELECT id FROM master_area WHERE slug='jember'),29000,'2026-05-24'),
((SELECT id FROM bahan_pokok WHERE slug='bawang-merah'),(SELECT id FROM master_area WHERE slug='lamongan'),28000,'2026-05-24'),
((SELECT id FROM bahan_pokok WHERE slug='bawang-merah'),(SELECT id FROM master_area WHERE slug='banyuwangi'),29500,'2026-05-24'),
((SELECT id FROM bahan_pokok WHERE slug='bawang-merah'),(SELECT id FROM master_area WHERE slug='surabaya'),31000,'2026-05-31'),
((SELECT id FROM bahan_pokok WHERE slug='bawang-merah'),(SELECT id FROM master_area WHERE slug='malang'),30000,'2026-05-31'),
((SELECT id FROM bahan_pokok WHERE slug='bawang-merah'),(SELECT id FROM master_area WHERE slug='sidoarjo'),31500,'2026-05-31'),
((SELECT id FROM bahan_pokok WHERE slug='bawang-merah'),(SELECT id FROM master_area WHERE slug='gresik'),30000,'2026-05-31'),
((SELECT id FROM bahan_pokok WHERE slug='bawang-merah'),(SELECT id FROM master_area WHERE slug='jombang'),29000,'2026-05-31'),
((SELECT id FROM bahan_pokok WHERE slug='bawang-merah'),(SELECT id FROM master_area WHERE slug='kediri'),28500,'2026-05-31'),
((SELECT id FROM bahan_pokok WHERE slug='bawang-merah'),(SELECT id FROM master_area WHERE slug='madiun'),29500,'2026-05-31'),
((SELECT id FROM bahan_pokok WHERE slug='bawang-merah'),(SELECT id FROM master_area WHERE slug='jember'),30000,'2026-05-31'),
((SELECT id FROM bahan_pokok WHERE slug='bawang-merah'),(SELECT id FROM master_area WHERE slug='lamongan'),29000,'2026-05-31'),
((SELECT id FROM bahan_pokok WHERE slug='bawang-merah'),(SELECT id FROM master_area WHERE slug='banyuwangi'),30500,'2026-05-31'),
((SELECT id FROM bahan_pokok WHERE slug='bawang-merah'),(SELECT id FROM master_area WHERE slug='surabaya'),30500,'2026-06-03'),
((SELECT id FROM bahan_pokok WHERE slug='bawang-merah'),(SELECT id FROM master_area WHERE slug='malang'),29500,'2026-06-03'),
((SELECT id FROM bahan_pokok WHERE slug='bawang-merah'),(SELECT id FROM master_area WHERE slug='sidoarjo'),31000,'2026-06-03'),
((SELECT id FROM bahan_pokok WHERE slug='bawang-merah'),(SELECT id FROM master_area WHERE slug='gresik'),29500,'2026-06-03'),
((SELECT id FROM bahan_pokok WHERE slug='bawang-merah'),(SELECT id FROM master_area WHERE slug='jombang'),28500,'2026-06-03'),
((SELECT id FROM bahan_pokok WHERE slug='bawang-merah'),(SELECT id FROM master_area WHERE slug='kediri'),28000,'2026-06-03'),
((SELECT id FROM bahan_pokok WHERE slug='bawang-merah'),(SELECT id FROM master_area WHERE slug='madiun'),29000,'2026-06-03'),
((SELECT id FROM bahan_pokok WHERE slug='bawang-merah'),(SELECT id FROM master_area WHERE slug='jember'),29500,'2026-06-03'),
((SELECT id FROM bahan_pokok WHERE slug='bawang-merah'),(SELECT id FROM master_area WHERE slug='lamongan'),28500,'2026-06-03'),
((SELECT id FROM bahan_pokok WHERE slug='bawang-merah'),(SELECT id FROM master_area WHERE slug='banyuwangi'),30000,'2026-06-03'),
((SELECT id FROM bahan_pokok WHERE slug='bawang-merah'),(SELECT id FROM master_area WHERE slug='surabaya'),29500,'2026-06-06'),
((SELECT id FROM bahan_pokok WHERE slug='bawang-merah'),(SELECT id FROM master_area WHERE slug='malang'),28500,'2026-06-06'),
((SELECT id FROM bahan_pokok WHERE slug='bawang-merah'),(SELECT id FROM master_area WHERE slug='sidoarjo'),30000,'2026-06-06'),
((SELECT id FROM bahan_pokok WHERE slug='bawang-merah'),(SELECT id FROM master_area WHERE slug='gresik'),28500,'2026-06-06'),
((SELECT id FROM bahan_pokok WHERE slug='bawang-merah'),(SELECT id FROM master_area WHERE slug='jombang'),27500,'2026-06-06'),
((SELECT id FROM bahan_pokok WHERE slug='bawang-merah'),(SELECT id FROM master_area WHERE slug='kediri'),27000,'2026-06-06'),
((SELECT id FROM bahan_pokok WHERE slug='bawang-merah'),(SELECT id FROM master_area WHERE slug='madiun'),28000,'2026-06-06'),
((SELECT id FROM bahan_pokok WHERE slug='bawang-merah'),(SELECT id FROM master_area WHERE slug='jember'),28500,'2026-06-06'),
((SELECT id FROM bahan_pokok WHERE slug='bawang-merah'),(SELECT id FROM master_area WHERE slug='lamongan'),27500,'2026-06-06'),
((SELECT id FROM bahan_pokok WHERE slug='bawang-merah'),(SELECT id FROM master_area WHERE slug='banyuwangi'),29000,'2026-06-06'),
((SELECT id FROM bahan_pokok WHERE slug='bawang-merah'),(SELECT id FROM master_area WHERE slug='surabaya'),29000,'2026-06-07'),
((SELECT id FROM bahan_pokok WHERE slug='bawang-merah'),(SELECT id FROM master_area WHERE slug='malang'),28000,'2026-06-07'),
((SELECT id FROM bahan_pokok WHERE slug='bawang-merah'),(SELECT id FROM master_area WHERE slug='sidoarjo'),29500,'2026-06-07'),
((SELECT id FROM bahan_pokok WHERE slug='bawang-merah'),(SELECT id FROM master_area WHERE slug='gresik'),28000,'2026-06-07'),
((SELECT id FROM bahan_pokok WHERE slug='bawang-merah'),(SELECT id FROM master_area WHERE slug='jombang'),27000,'2026-06-07'),
((SELECT id FROM bahan_pokok WHERE slug='bawang-merah'),(SELECT id FROM master_area WHERE slug='kediri'),26500,'2026-06-07'),
((SELECT id FROM bahan_pokok WHERE slug='bawang-merah'),(SELECT id FROM master_area WHERE slug='madiun'),27500,'2026-06-07'),
((SELECT id FROM bahan_pokok WHERE slug='bawang-merah'),(SELECT id FROM master_area WHERE slug='jember'),28000,'2026-06-07'),
((SELECT id FROM bahan_pokok WHERE slug='bawang-merah'),(SELECT id FROM master_area WHERE slug='lamongan'),27000,'2026-06-07'),
((SELECT id FROM bahan_pokok WHERE slug='bawang-merah'),(SELECT id FROM master_area WHERE slug='banyuwangi'),28500,'2026-06-07'),

-- BERAS MEDIUM
((SELECT id FROM bahan_pokok WHERE slug='beras-medium'),(SELECT id FROM master_area WHERE slug='surabaya'),13000,'2026-05-10'),
((SELECT id FROM bahan_pokok WHERE slug='beras-medium'),(SELECT id FROM master_area WHERE slug='malang'),12500,'2026-05-10'),
((SELECT id FROM bahan_pokok WHERE slug='beras-medium'),(SELECT id FROM master_area WHERE slug='sidoarjo'),13200,'2026-05-10'),
((SELECT id FROM bahan_pokok WHERE slug='beras-medium'),(SELECT id FROM master_area WHERE slug='gresik'),12800,'2026-05-10'),
((SELECT id FROM bahan_pokok WHERE slug='beras-medium'),(SELECT id FROM master_area WHERE slug='jombang'),12500,'2026-05-10'),
((SELECT id FROM bahan_pokok WHERE slug='beras-medium'),(SELECT id FROM master_area WHERE slug='kediri'),12300,'2026-05-10'),
((SELECT id FROM bahan_pokok WHERE slug='beras-medium'),(SELECT id FROM master_area WHERE slug='madiun'),12500,'2026-05-10'),
((SELECT id FROM bahan_pokok WHERE slug='beras-medium'),(SELECT id FROM master_area WHERE slug='jember'),12800,'2026-05-10'),
((SELECT id FROM bahan_pokok WHERE slug='beras-medium'),(SELECT id FROM master_area WHERE slug='lamongan'),12500,'2026-05-10'),
((SELECT id FROM bahan_pokok WHERE slug='beras-medium'),(SELECT id FROM master_area WHERE slug='banyuwangi'),12800,'2026-05-10'),
((SELECT id FROM bahan_pokok WHERE slug='beras-medium'),(SELECT id FROM master_area WHERE slug='surabaya'),13200,'2026-05-17'),
((SELECT id FROM bahan_pokok WHERE slug='beras-medium'),(SELECT id FROM master_area WHERE slug='malang'),12700,'2026-05-17'),
((SELECT id FROM bahan_pokok WHERE slug='beras-medium'),(SELECT id FROM master_area WHERE slug='sidoarjo'),13400,'2026-05-17'),
((SELECT id FROM bahan_pokok WHERE slug='beras-medium'),(SELECT id FROM master_area WHERE slug='gresik'),13000,'2026-05-17'),
((SELECT id FROM bahan_pokok WHERE slug='beras-medium'),(SELECT id FROM master_area WHERE slug='jombang'),12700,'2026-05-17'),
((SELECT id FROM bahan_pokok WHERE slug='beras-medium'),(SELECT id FROM master_area WHERE slug='kediri'),12500,'2026-05-17'),
((SELECT id FROM bahan_pokok WHERE slug='beras-medium'),(SELECT id FROM master_area WHERE slug='madiun'),12700,'2026-05-17'),
((SELECT id FROM bahan_pokok WHERE slug='beras-medium'),(SELECT id FROM master_area WHERE slug='jember'),13000,'2026-05-17'),
((SELECT id FROM bahan_pokok WHERE slug='beras-medium'),(SELECT id FROM master_area WHERE slug='lamongan'),12700,'2026-05-17'),
((SELECT id FROM bahan_pokok WHERE slug='beras-medium'),(SELECT id FROM master_area WHERE slug='banyuwangi'),13000,'2026-05-17'),
((SELECT id FROM bahan_pokok WHERE slug='beras-medium'),(SELECT id FROM master_area WHERE slug='surabaya'),13500,'2026-05-24'),
((SELECT id FROM bahan_pokok WHERE slug='beras-medium'),(SELECT id FROM master_area WHERE slug='malang'),13000,'2026-05-24'),
((SELECT id FROM bahan_pokok WHERE slug='beras-medium'),(SELECT id FROM master_area WHERE slug='sidoarjo'),13700,'2026-05-24'),
((SELECT id FROM bahan_pokok WHERE slug='beras-medium'),(SELECT id FROM master_area WHERE slug='gresik'),13300,'2026-05-24'),
((SELECT id FROM bahan_pokok WHERE slug='beras-medium'),(SELECT id FROM master_area WHERE slug='jombang'),13000,'2026-05-24'),
((SELECT id FROM bahan_pokok WHERE slug='beras-medium'),(SELECT id FROM master_area WHERE slug='kediri'),12800,'2026-05-24'),
((SELECT id FROM bahan_pokok WHERE slug='beras-medium'),(SELECT id FROM master_area WHERE slug='madiun'),13000,'2026-05-24'),
((SELECT id FROM bahan_pokok WHERE slug='beras-medium'),(SELECT id FROM master_area WHERE slug='jember'),13300,'2026-05-24'),
((SELECT id FROM bahan_pokok WHERE slug='beras-medium'),(SELECT id FROM master_area WHERE slug='lamongan'),13000,'2026-05-24'),
((SELECT id FROM bahan_pokok WHERE slug='beras-medium'),(SELECT id FROM master_area WHERE slug='banyuwangi'),13300,'2026-05-24'),
((SELECT id FROM bahan_pokok WHERE slug='beras-medium'),(SELECT id FROM master_area WHERE slug='surabaya'),13800,'2026-05-31'),
((SELECT id FROM bahan_pokok WHERE slug='beras-medium'),(SELECT id FROM master_area WHERE slug='malang'),13300,'2026-05-31'),
((SELECT id FROM bahan_pokok WHERE slug='beras-medium'),(SELECT id FROM master_area WHERE slug='sidoarjo'),14000,'2026-05-31'),
((SELECT id FROM bahan_pokok WHERE slug='beras-medium'),(SELECT id FROM master_area WHERE slug='gresik'),13500,'2026-05-31'),
((SELECT id FROM bahan_pokok WHERE slug='beras-medium'),(SELECT id FROM master_area WHERE slug='jombang'),13200,'2026-05-31'),
((SELECT id FROM bahan_pokok WHERE slug='beras-medium'),(SELECT id FROM master_area WHERE slug='kediri'),13000,'2026-05-31'),
((SELECT id FROM bahan_pokok WHERE slug='beras-medium'),(SELECT id FROM master_area WHERE slug='madiun'),13200,'2026-05-31'),
((SELECT id FROM bahan_pokok WHERE slug='beras-medium'),(SELECT id FROM master_area WHERE slug='jember'),13500,'2026-05-31'),
((SELECT id FROM bahan_pokok WHERE slug='beras-medium'),(SELECT id FROM master_area WHERE slug='lamongan'),13200,'2026-05-31'),
((SELECT id FROM bahan_pokok WHERE slug='beras-medium'),(SELECT id FROM master_area WHERE slug='banyuwangi'),13500,'2026-05-31'),
((SELECT id FROM bahan_pokok WHERE slug='beras-medium'),(SELECT id FROM master_area WHERE slug='surabaya'),14000,'2026-06-03'),
((SELECT id FROM bahan_pokok WHERE slug='beras-medium'),(SELECT id FROM master_area WHERE slug='malang'),13500,'2026-06-03'),
((SELECT id FROM bahan_pokok WHERE slug='beras-medium'),(SELECT id FROM master_area WHERE slug='sidoarjo'),14200,'2026-06-03'),
((SELECT id FROM bahan_pokok WHERE slug='beras-medium'),(SELECT id FROM master_area WHERE slug='gresik'),13800,'2026-06-03'),
((SELECT id FROM bahan_pokok WHERE slug='beras-medium'),(SELECT id FROM master_area WHERE slug='jombang'),13500,'2026-06-03'),
((SELECT id FROM bahan_pokok WHERE slug='beras-medium'),(SELECT id FROM master_area WHERE slug='kediri'),13300,'2026-06-03'),
((SELECT id FROM bahan_pokok WHERE slug='beras-medium'),(SELECT id FROM master_area WHERE slug='madiun'),13500,'2026-06-03'),
((SELECT id FROM bahan_pokok WHERE slug='beras-medium'),(SELECT id FROM master_area WHERE slug='jember'),13800,'2026-06-03'),
((SELECT id FROM bahan_pokok WHERE slug='beras-medium'),(SELECT id FROM master_area WHERE slug='lamongan'),13500,'2026-06-03'),
((SELECT id FROM bahan_pokok WHERE slug='beras-medium'),(SELECT id FROM master_area WHERE slug='banyuwangi'),13800,'2026-06-03'),
((SELECT id FROM bahan_pokok WHERE slug='beras-medium'),(SELECT id FROM master_area WHERE slug='surabaya'),14000,'2026-06-06'),
((SELECT id FROM bahan_pokok WHERE slug='beras-medium'),(SELECT id FROM master_area WHERE slug='malang'),13500,'2026-06-06'),
((SELECT id FROM bahan_pokok WHERE slug='beras-medium'),(SELECT id FROM master_area WHERE slug='sidoarjo'),14200,'2026-06-06'),
((SELECT id FROM bahan_pokok WHERE slug='beras-medium'),(SELECT id FROM master_area WHERE slug='gresik'),13800,'2026-06-06'),
((SELECT id FROM bahan_pokok WHERE slug='beras-medium'),(SELECT id FROM master_area WHERE slug='jombang'),13500,'2026-06-06'),
((SELECT id FROM bahan_pokok WHERE slug='beras-medium'),(SELECT id FROM master_area WHERE slug='kediri'),13300,'2026-06-06'),
((SELECT id FROM bahan_pokok WHERE slug='beras-medium'),(SELECT id FROM master_area WHERE slug='madiun'),13500,'2026-06-06'),
((SELECT id FROM bahan_pokok WHERE slug='beras-medium'),(SELECT id FROM master_area WHERE slug='jember'),13800,'2026-06-06'),
((SELECT id FROM bahan_pokok WHERE slug='beras-medium'),(SELECT id FROM master_area WHERE slug='lamongan'),13500,'2026-06-06'),
((SELECT id FROM bahan_pokok WHERE slug='beras-medium'),(SELECT id FROM master_area WHERE slug='banyuwangi'),13800,'2026-06-06'),
((SELECT id FROM bahan_pokok WHERE slug='beras-medium'),(SELECT id FROM master_area WHERE slug='surabaya'),14200,'2026-06-07'),
((SELECT id FROM bahan_pokok WHERE slug='beras-medium'),(SELECT id FROM master_area WHERE slug='malang'),13700,'2026-06-07'),
((SELECT id FROM bahan_pokok WHERE slug='beras-medium'),(SELECT id FROM master_area WHERE slug='sidoarjo'),14500,'2026-06-07'),
((SELECT id FROM bahan_pokok WHERE slug='beras-medium'),(SELECT id FROM master_area WHERE slug='gresik'),14000,'2026-06-07'),
((SELECT id FROM bahan_pokok WHERE slug='beras-medium'),(SELECT id FROM master_area WHERE slug='jombang'),13700,'2026-06-07'),
((SELECT id FROM bahan_pokok WHERE slug='beras-medium'),(SELECT id FROM master_area WHERE slug='kediri'),13500,'2026-06-07'),
((SELECT id FROM bahan_pokok WHERE slug='beras-medium'),(SELECT id FROM master_area WHERE slug='madiun'),13700,'2026-06-07'),
((SELECT id FROM bahan_pokok WHERE slug='beras-medium'),(SELECT id FROM master_area WHERE slug='jember'),14000,'2026-06-07'),
((SELECT id FROM bahan_pokok WHERE slug='beras-medium'),(SELECT id FROM master_area WHERE slug='lamongan'),13700,'2026-06-07'),
((SELECT id FROM bahan_pokok WHERE slug='beras-medium'),(SELECT id FROM master_area WHERE slug='banyuwangi'),14000,'2026-06-07'),

-- BAWANG PUTIH
((SELECT id FROM bahan_pokok WHERE slug='bawang-putih'),(SELECT id FROM master_area WHERE slug='surabaya'),35000,'2026-05-10'),
((SELECT id FROM bahan_pokok WHERE slug='bawang-putih'),(SELECT id FROM master_area WHERE slug='malang'),34000,'2026-05-10'),
((SELECT id FROM bahan_pokok WHERE slug='bawang-putih'),(SELECT id FROM master_area WHERE slug='sidoarjo'),35500,'2026-05-10'),
((SELECT id FROM bahan_pokok WHERE slug='bawang-putih'),(SELECT id FROM master_area WHERE slug='gresik'),34500,'2026-05-10'),
((SELECT id FROM bahan_pokok WHERE slug='bawang-putih'),(SELECT id FROM master_area WHERE slug='jombang'),33000,'2026-05-10'),
((SELECT id FROM bahan_pokok WHERE slug='bawang-putih'),(SELECT id FROM master_area WHERE slug='kediri'),33500,'2026-05-10'),
((SELECT id FROM bahan_pokok WHERE slug='bawang-putih'),(SELECT id FROM master_area WHERE slug='madiun'),34000,'2026-05-10'),
((SELECT id FROM bahan_pokok WHERE slug='bawang-putih'),(SELECT id FROM master_area WHERE slug='jember'),34500,'2026-05-10'),
((SELECT id FROM bahan_pokok WHERE slug='bawang-putih'),(SELECT id FROM master_area WHERE slug='lamongan'),33500,'2026-05-10'),
((SELECT id FROM bahan_pokok WHERE slug='bawang-putih'),(SELECT id FROM master_area WHERE slug='banyuwangi'),34000,'2026-05-10'),
((SELECT id FROM bahan_pokok WHERE slug='bawang-putih'),(SELECT id FROM master_area WHERE slug='surabaya'),36000,'2026-05-17'),
((SELECT id FROM bahan_pokok WHERE slug='bawang-putih'),(SELECT id FROM master_area WHERE slug='malang'),35000,'2026-05-17'),
((SELECT id FROM bahan_pokok WHERE slug='bawang-putih'),(SELECT id FROM master_area WHERE slug='sidoarjo'),36500,'2026-05-17'),
((SELECT id FROM bahan_pokok WHERE slug='bawang-putih'),(SELECT id FROM master_area WHERE slug='gresik'),35500,'2026-05-17'),
((SELECT id FROM bahan_pokok WHERE slug='bawang-putih'),(SELECT id FROM master_area WHERE slug='jombang'),34000,'2026-05-17'),
((SELECT id FROM bahan_pokok WHERE slug='bawang-putih'),(SELECT id FROM master_area WHERE slug='kediri'),34500,'2026-05-17'),
((SELECT id FROM bahan_pokok WHERE slug='bawang-putih'),(SELECT id FROM master_area WHERE slug='madiun'),35000,'2026-05-17'),
((SELECT id FROM bahan_pokok WHERE slug='bawang-putih'),(SELECT id FROM master_area WHERE slug='jember'),35500,'2026-05-17'),
((SELECT id FROM bahan_pokok WHERE slug='bawang-putih'),(SELECT id FROM master_area WHERE slug='lamongan'),34500,'2026-05-17'),
((SELECT id FROM bahan_pokok WHERE slug='bawang-putih'),(SELECT id FROM master_area WHERE slug='banyuwangi'),35000,'2026-05-17'),
((SELECT id FROM bahan_pokok WHERE slug='bawang-putih'),(SELECT id FROM master_area WHERE slug='surabaya'),37000,'2026-05-24'),
((SELECT id FROM bahan_pokok WHERE slug='bawang-putih'),(SELECT id FROM master_area WHERE slug='malang'),36000,'2026-05-24'),
((SELECT id FROM bahan_pokok WHERE slug='bawang-putih'),(SELECT id FROM master_area WHERE slug='sidoarjo'),37500,'2026-05-24'),
((SELECT id FROM bahan_pokok WHERE slug='bawang-putih'),(SELECT id FROM master_area WHERE slug='gresik'),36500,'2026-05-24'),
((SELECT id FROM bahan_pokok WHERE slug='bawang-putih'),(SELECT id FROM master_area WHERE slug='jombang'),35000,'2026-05-24'),
((SELECT id FROM bahan_pokok WHERE slug='bawang-putih'),(SELECT id FROM master_area WHERE slug='kediri'),35500,'2026-05-24'),
((SELECT id FROM bahan_pokok WHERE slug='bawang-putih'),(SELECT id FROM master_area WHERE slug='madiun'),36000,'2026-05-24'),
((SELECT id FROM bahan_pokok WHERE slug='bawang-putih'),(SELECT id FROM master_area WHERE slug='jember'),36500,'2026-05-24'),
((SELECT id FROM bahan_pokok WHERE slug='bawang-putih'),(SELECT id FROM master_area WHERE slug='lamongan'),35500,'2026-05-24'),
((SELECT id FROM bahan_pokok WHERE slug='bawang-putih'),(SELECT id FROM master_area WHERE slug='banyuwangi'),36000,'2026-05-24'),
((SELECT id FROM bahan_pokok WHERE slug='bawang-putih'),(SELECT id FROM master_area WHERE slug='surabaya'),38000,'2026-05-31'),
((SELECT id FROM bahan_pokok WHERE slug='bawang-putih'),(SELECT id FROM master_area WHERE slug='malang'),37000,'2026-05-31'),
((SELECT id FROM bahan_pokok WHERE slug='bawang-putih'),(SELECT id FROM master_area WHERE slug='sidoarjo'),38500,'2026-05-31'),
((SELECT id FROM bahan_pokok WHERE slug='bawang-putih'),(SELECT id FROM master_area WHERE slug='gresik'),37500,'2026-05-31'),
((SELECT id FROM bahan_pokok WHERE slug='bawang-putih'),(SELECT id FROM master_area WHERE slug='jombang'),36000,'2026-05-31'),
((SELECT id FROM bahan_pokok WHERE slug='bawang-putih'),(SELECT id FROM master_area WHERE slug='kediri'),36500,'2026-05-31'),
((SELECT id FROM bahan_pokok WHERE slug='bawang-putih'),(SELECT id FROM master_area WHERE slug='madiun'),37000,'2026-05-31'),
((SELECT id FROM bahan_pokok WHERE slug='bawang-putih'),(SELECT id FROM master_area WHERE slug='jember'),37500,'2026-05-31'),
((SELECT id FROM bahan_pokok WHERE slug='bawang-putih'),(SELECT id FROM master_area WHERE slug='lamongan'),36500,'2026-05-31'),
((SELECT id FROM bahan_pokok WHERE slug='bawang-putih'),(SELECT id FROM master_area WHERE slug='banyuwangi'),37000,'2026-05-31'),
((SELECT id FROM bahan_pokok WHERE slug='bawang-putih'),(SELECT id FROM master_area WHERE slug='surabaya'),38500,'2026-06-03'),
((SELECT id FROM bahan_pokok WHERE slug='bawang-putih'),(SELECT id FROM master_area WHERE slug='malang'),37500,'2026-06-03'),
((SELECT id FROM bahan_pokok WHERE slug='bawang-putih'),(SELECT id FROM master_area WHERE slug='sidoarjo'),39000,'2026-06-03'),
((SELECT id FROM bahan_pokok WHERE slug='bawang-putih'),(SELECT id FROM master_area WHERE slug='gresik'),38000,'2026-06-03'),
((SELECT id FROM bahan_pokok WHERE slug='bawang-putih'),(SELECT id FROM master_area WHERE slug='jombang'),36500,'2026-06-03'),
((SELECT id FROM bahan_pokok WHERE slug='bawang-putih'),(SELECT id FROM master_area WHERE slug='kediri'),37000,'2026-06-03'),
((SELECT id FROM bahan_pokok WHERE slug='bawang-putih'),(SELECT id FROM master_area WHERE slug='madiun'),37500,'2026-06-03'),
((SELECT id FROM bahan_pokok WHERE slug='bawang-putih'),(SELECT id FROM master_area WHERE slug='jember'),38000,'2026-06-03'),
((SELECT id FROM bahan_pokok WHERE slug='bawang-putih'),(SELECT id FROM master_area WHERE slug='lamongan'),37000,'2026-06-03'),
((SELECT id FROM bahan_pokok WHERE slug='bawang-putih'),(SELECT id FROM master_area WHERE slug='banyuwangi'),37500,'2026-06-03'),
((SELECT id FROM bahan_pokok WHERE slug='bawang-putih'),(SELECT id FROM master_area WHERE slug='surabaya'),38000,'2026-06-06'),
((SELECT id FROM bahan_pokok WHERE slug='bawang-putih'),(SELECT id FROM master_area WHERE slug='malang'),37000,'2026-06-06'),
((SELECT id FROM bahan_pokok WHERE slug='bawang-putih'),(SELECT id FROM master_area WHERE slug='sidoarjo'),38500,'2026-06-06'),
((SELECT id FROM bahan_pokok WHERE slug='bawang-putih'),(SELECT id FROM master_area WHERE slug='gresik'),37500,'2026-06-06'),
((SELECT id FROM bahan_pokok WHERE slug='bawang-putih'),(SELECT id FROM master_area WHERE slug='jombang'),36000,'2026-06-06'),
((SELECT id FROM bahan_pokok WHERE slug='bawang-putih'),(SELECT id FROM master_area WHERE slug='kediri'),36500,'2026-06-06'),
((SELECT id FROM bahan_pokok WHERE slug='bawang-putih'),(SELECT id FROM master_area WHERE slug='madiun'),37000,'2026-06-06'),
((SELECT id FROM bahan_pokok WHERE slug='bawang-putih'),(SELECT id FROM master_area WHERE slug='jember'),37500,'2026-06-06'),
((SELECT id FROM bahan_pokok WHERE slug='bawang-putih'),(SELECT id FROM master_area WHERE slug='lamongan'),36500,'2026-06-06'),
((SELECT id FROM bahan_pokok WHERE slug='bawang-putih'),(SELECT id FROM master_area WHERE slug='banyuwangi'),37000,'2026-06-06'),
((SELECT id FROM bahan_pokok WHERE slug='bawang-putih'),(SELECT id FROM master_area WHERE slug='surabaya'),37500,'2026-06-07'),
((SELECT id FROM bahan_pokok WHERE slug='bawang-putih'),(SELECT id FROM master_area WHERE slug='malang'),36500,'2026-06-07'),
((SELECT id FROM bahan_pokok WHERE slug='bawang-putih'),(SELECT id FROM master_area WHERE slug='sidoarjo'),38000,'2026-06-07'),
((SELECT id FROM bahan_pokok WHERE slug='bawang-putih'),(SELECT id FROM master_area WHERE slug='gresik'),37000,'2026-06-07'),
((SELECT id FROM bahan_pokok WHERE slug='bawang-putih'),(SELECT id FROM master_area WHERE slug='jombang'),35500,'2026-06-07'),
((SELECT id FROM bahan_pokok WHERE slug='bawang-putih'),(SELECT id FROM master_area WHERE slug='kediri'),36000,'2026-06-07'),
((SELECT id FROM bahan_pokok WHERE slug='bawang-putih'),(SELECT id FROM master_area WHERE slug='madiun'),36500,'2026-06-07'),
((SELECT id FROM bahan_pokok WHERE slug='bawang-putih'),(SELECT id FROM master_area WHERE slug='jember'),37000,'2026-06-07'),
((SELECT id FROM bahan_pokok WHERE slug='bawang-putih'),(SELECT id FROM master_area WHERE slug='lamongan'),36000,'2026-06-07'),
((SELECT id FROM bahan_pokok WHERE slug='bawang-putih'),(SELECT id FROM master_area WHERE slug='banyuwangi'),36500,'2026-06-07'),

-- CABAI RAWIT
((SELECT id FROM bahan_pokok WHERE slug='cabai-rawit'),(SELECT id FROM master_area WHERE slug='surabaya'),45000,'2026-05-10'),
((SELECT id FROM bahan_pokok WHERE slug='cabai-rawit'),(SELECT id FROM master_area WHERE slug='malang'),43000,'2026-05-10'),
((SELECT id FROM bahan_pokok WHERE slug='cabai-rawit'),(SELECT id FROM master_area WHERE slug='sidoarjo'),46000,'2026-05-10'),
((SELECT id FROM bahan_pokok WHERE slug='cabai-rawit'),(SELECT id FROM master_area WHERE slug='gresik'),44000,'2026-05-10'),
((SELECT id FROM bahan_pokok WHERE slug='cabai-rawit'),(SELECT id FROM master_area WHERE slug='jombang'),42000,'2026-05-10'),
((SELECT id FROM bahan_pokok WHERE slug='cabai-rawit'),(SELECT id FROM master_area WHERE slug='kediri'),41000,'2026-05-10'),
((SELECT id FROM bahan_pokok WHERE slug='cabai-rawit'),(SELECT id FROM master_area WHERE slug='madiun'),43000,'2026-05-10'),
((SELECT id FROM bahan_pokok WHERE slug='cabai-rawit'),(SELECT id FROM master_area WHERE slug='jember'),44000,'2026-05-10'),
((SELECT id FROM bahan_pokok WHERE slug='cabai-rawit'),(SELECT id FROM master_area WHERE slug='lamongan'),42000,'2026-05-10'),
((SELECT id FROM bahan_pokok WHERE slug='cabai-rawit'),(SELECT id FROM master_area WHERE slug='banyuwangi'),43000,'2026-05-10'),
((SELECT id FROM bahan_pokok WHERE slug='cabai-rawit'),(SELECT id FROM master_area WHERE slug='surabaya'),50000,'2026-05-17'),
((SELECT id FROM bahan_pokok WHERE slug='cabai-rawit'),(SELECT id FROM master_area WHERE slug='malang'),48000,'2026-05-17'),
((SELECT id FROM bahan_pokok WHERE slug='cabai-rawit'),(SELECT id FROM master_area WHERE slug='sidoarjo'),52000,'2026-05-17'),
((SELECT id FROM bahan_pokok WHERE slug='cabai-rawit'),(SELECT id FROM master_area WHERE slug='gresik'),49000,'2026-05-17'),
((SELECT id FROM bahan_pokok WHERE slug='cabai-rawit'),(SELECT id FROM master_area WHERE slug='jombang'),47000,'2026-05-17'),
((SELECT id FROM bahan_pokok WHERE slug='cabai-rawit'),(SELECT id FROM master_area WHERE slug='kediri'),46000,'2026-05-17'),
((SELECT id FROM bahan_pokok WHERE slug='cabai-rawit'),(SELECT id FROM master_area WHERE slug='madiun'),48000,'2026-05-17'),
((SELECT id FROM bahan_pokok WHERE slug='cabai-rawit'),(SELECT id FROM master_area WHERE slug='jember'),49000,'2026-05-17'),
((SELECT id FROM bahan_pokok WHERE slug='cabai-rawit'),(SELECT id FROM master_area WHERE slug='lamongan'),47000,'2026-05-17'),
((SELECT id FROM bahan_pokok WHERE slug='cabai-rawit'),(SELECT id FROM master_area WHERE slug='banyuwangi'),48000,'2026-05-17'),
((SELECT id FROM bahan_pokok WHERE slug='cabai-rawit'),(SELECT id FROM master_area WHERE slug='surabaya'),60000,'2026-05-24'),
((SELECT id FROM bahan_pokok WHERE slug='cabai-rawit'),(SELECT id FROM master_area WHERE slug='malang'),58000,'2026-05-24'),
((SELECT id FROM bahan_pokok WHERE slug='cabai-rawit'),(SELECT id FROM master_area WHERE slug='sidoarjo'),62000,'2026-05-24'),
((SELECT id FROM bahan_pokok WHERE slug='cabai-rawit'),(SELECT id FROM master_area WHERE slug='gresik'),59000,'2026-05-24'),
((SELECT id FROM bahan_pokok WHERE slug='cabai-rawit'),(SELECT id FROM master_area WHERE slug='jombang'),57000,'2026-05-24'),
((SELECT id FROM bahan_pokok WHERE slug='cabai-rawit'),(SELECT id FROM master_area WHERE slug='kediri'),56000,'2026-05-24'),
((SELECT id FROM bahan_pokok WHERE slug='cabai-rawit'),(SELECT id FROM master_area WHERE slug='madiun'),58000,'2026-05-24'),
((SELECT id FROM bahan_pokok WHERE slug='cabai-rawit'),(SELECT id FROM master_area WHERE slug='jember'),59000,'2026-05-24'),
((SELECT id FROM bahan_pokok WHERE slug='cabai-rawit'),(SELECT id FROM master_area WHERE slug='lamongan'),57000,'2026-05-24'),
((SELECT id FROM bahan_pokok WHERE slug='cabai-rawit'),(SELECT id FROM master_area WHERE slug='banyuwangi'),58000,'2026-05-24'),
((SELECT id FROM bahan_pokok WHERE slug='cabai-rawit'),(SELECT id FROM master_area WHERE slug='surabaya'),55000,'2026-05-31'),
((SELECT id FROM bahan_pokok WHERE slug='cabai-rawit'),(SELECT id FROM master_area WHERE slug='malang'),53000,'2026-05-31'),
((SELECT id FROM bahan_pokok WHERE slug='cabai-rawit'),(SELECT id FROM master_area WHERE slug='sidoarjo'),57000,'2026-05-31'),
((SELECT id FROM bahan_pokok WHERE slug='cabai-rawit'),(SELECT id FROM master_area WHERE slug='gresik'),54000,'2026-05-31'),
((SELECT id FROM bahan_pokok WHERE slug='cabai-rawit'),(SELECT id FROM master_area WHERE slug='jombang'),52000,'2026-05-31'),
((SELECT id FROM bahan_pokok WHERE slug='cabai-rawit'),(SELECT id FROM master_area WHERE slug='kediri'),51000,'2026-05-31'),
((SELECT id FROM bahan_pokok WHERE slug='cabai-rawit'),(SELECT id FROM master_area WHERE slug='madiun'),53000,'2026-05-31'),
((SELECT id FROM bahan_pokok WHERE slug='cabai-rawit'),(SELECT id FROM master_area WHERE slug='jember'),54000,'2026-05-31'),
((SELECT id FROM bahan_pokok WHERE slug='cabai-rawit'),(SELECT id FROM master_area WHERE slug='lamongan'),52000,'2026-05-31'),
((SELECT id FROM bahan_pokok WHERE slug='cabai-rawit'),(SELECT id FROM master_area WHERE slug='banyuwangi'),53000,'2026-05-31'),
((SELECT id FROM bahan_pokok WHERE slug='cabai-rawit'),(SELECT id FROM master_area WHERE slug='surabaya'),48000,'2026-06-03'),
((SELECT id FROM bahan_pokok WHERE slug='cabai-rawit'),(SELECT id FROM master_area WHERE slug='malang'),46000,'2026-06-03'),
((SELECT id FROM bahan_pokok WHERE slug='cabai-rawit'),(SELECT id FROM master_area WHERE slug='sidoarjo'),50000,'2026-06-03'),
((SELECT id FROM bahan_pokok WHERE slug='cabai-rawit'),(SELECT id FROM master_area WHERE slug='gresik'),47000,'2026-06-03'),
((SELECT id FROM bahan_pokok WHERE slug='cabai-rawit'),(SELECT id FROM master_area WHERE slug='jombang'),45000,'2026-06-03'),
((SELECT id FROM bahan_pokok WHERE slug='cabai-rawit'),(SELECT id FROM master_area WHERE slug='kediri'),44000,'2026-06-03'),
((SELECT id FROM bahan_pokok WHERE slug='cabai-rawit'),(SELECT id FROM master_area WHERE slug='madiun'),46000,'2026-06-03'),
((SELECT id FROM bahan_pokok WHERE slug='cabai-rawit'),(SELECT id FROM master_area WHERE slug='jember'),47000,'2026-06-03'),
((SELECT id FROM bahan_pokok WHERE slug='cabai-rawit'),(SELECT id FROM master_area WHERE slug='lamongan'),45000,'2026-06-03'),
((SELECT id FROM bahan_pokok WHERE slug='cabai-rawit'),(SELECT id FROM master_area WHERE slug='banyuwangi'),46000,'2026-06-03'),
((SELECT id FROM bahan_pokok WHERE slug='cabai-rawit'),(SELECT id FROM master_area WHERE slug='surabaya'),46000,'2026-06-06'),
((SELECT id FROM bahan_pokok WHERE slug='cabai-rawit'),(SELECT id FROM master_area WHERE slug='malang'),44000,'2026-06-06'),
((SELECT id FROM bahan_pokok WHERE slug='cabai-rawit'),(SELECT id FROM master_area WHERE slug='sidoarjo'),48000,'2026-06-06'),
((SELECT id FROM bahan_pokok WHERE slug='cabai-rawit'),(SELECT id FROM master_area WHERE slug='gresik'),45000,'2026-06-06'),
((SELECT id FROM bahan_pokok WHERE slug='cabai-rawit'),(SELECT id FROM master_area WHERE slug='jombang'),43000,'2026-06-06'),
((SELECT id FROM bahan_pokok WHERE slug='cabai-rawit'),(SELECT id FROM master_area WHERE slug='kediri'),42000,'2026-06-06'),
((SELECT id FROM bahan_pokok WHERE slug='cabai-rawit'),(SELECT id FROM master_area WHERE slug='madiun'),44000,'2026-06-06'),
((SELECT id FROM bahan_pokok WHERE slug='cabai-rawit'),(SELECT id FROM master_area WHERE slug='jember'),45000,'2026-06-06'),
((SELECT id FROM bahan_pokok WHERE slug='cabai-rawit'),(SELECT id FROM master_area WHERE slug='lamongan'),43000,'2026-06-06'),
((SELECT id FROM bahan_pokok WHERE slug='cabai-rawit'),(SELECT id FROM master_area WHERE slug='banyuwangi'),44000,'2026-06-06'),
((SELECT id FROM bahan_pokok WHERE slug='cabai-rawit'),(SELECT id FROM master_area WHERE slug='surabaya'),44000,'2026-06-07'),
((SELECT id FROM bahan_pokok WHERE slug='cabai-rawit'),(SELECT id FROM master_area WHERE slug='malang'),42000,'2026-06-07'),
((SELECT id FROM bahan_pokok WHERE slug='cabai-rawit'),(SELECT id FROM master_area WHERE slug='sidoarjo'),46000,'2026-06-07'),
((SELECT id FROM bahan_pokok WHERE slug='cabai-rawit'),(SELECT id FROM master_area WHERE slug='gresik'),43000,'2026-06-07'),
((SELECT id FROM bahan_pokok WHERE slug='cabai-rawit'),(SELECT id FROM master_area WHERE slug='jombang'),41000,'2026-06-07'),
((SELECT id FROM bahan_pokok WHERE slug='cabai-rawit'),(SELECT id FROM master_area WHERE slug='kediri'),40000,'2026-06-07'),
((SELECT id FROM bahan_pokok WHERE slug='cabai-rawit'),(SELECT id FROM master_area WHERE slug='madiun'),42000,'2026-06-07'),
((SELECT id FROM bahan_pokok WHERE slug='cabai-rawit'),(SELECT id FROM master_area WHERE slug='jember'),43000,'2026-06-07'),
((SELECT id FROM bahan_pokok WHERE slug='cabai-rawit'),(SELECT id FROM master_area WHERE slug='lamongan'),41000,'2026-06-07'),
((SELECT id FROM bahan_pokok WHERE slug='cabai-rawit'),(SELECT id FROM master_area WHERE slug='banyuwangi'),42000,'2026-06-07'),

-- CABAI MERAH
((SELECT id FROM bahan_pokok WHERE slug='cabai-merah'),(SELECT id FROM master_area WHERE slug='surabaya'),32000,'2026-05-10'),
((SELECT id FROM bahan_pokok WHERE slug='cabai-merah'),(SELECT id FROM master_area WHERE slug='malang'),31000,'2026-05-10'),
((SELECT id FROM bahan_pokok WHERE slug='cabai-merah'),(SELECT id FROM master_area WHERE slug='sidoarjo'),33000,'2026-05-10'),
((SELECT id FROM bahan_pokok WHERE slug='cabai-merah'),(SELECT id FROM master_area WHERE slug='gresik'),31500,'2026-05-10'),
((SELECT id FROM bahan_pokok WHERE slug='cabai-merah'),(SELECT id FROM master_area WHERE slug='jombang'),30000,'2026-05-10'),
((SELECT id FROM bahan_pokok WHERE slug='cabai-merah'),(SELECT id FROM master_area WHERE slug='kediri'),29500,'2026-05-10'),
((SELECT id FROM bahan_pokok WHERE slug='cabai-merah'),(SELECT id FROM master_area WHERE slug='madiun'),31000,'2026-05-10'),
((SELECT id FROM bahan_pokok WHERE slug='cabai-merah'),(SELECT id FROM master_area WHERE slug='jember'),31500,'2026-05-10'),
((SELECT id FROM bahan_pokok WHERE slug='cabai-merah'),(SELECT id FROM master_area WHERE slug='lamongan'),30000,'2026-05-10'),
((SELECT id FROM bahan_pokok WHERE slug='cabai-merah'),(SELECT id FROM master_area WHERE slug='banyuwangi'),31000,'2026-05-10'),
((SELECT id FROM bahan_pokok WHERE slug='cabai-merah'),(SELECT id FROM master_area WHERE slug='surabaya'),35000,'2026-05-17'),
((SELECT id FROM bahan_pokok WHERE slug='cabai-merah'),(SELECT id FROM master_area WHERE slug='malang'),34000,'2026-05-17'),
((SELECT id FROM bahan_pokok WHERE slug='cabai-merah'),(SELECT id FROM master_area WHERE slug='sidoarjo'),36000,'2026-05-17'),
((SELECT id FROM bahan_pokok WHERE slug='cabai-merah'),(SELECT id FROM master_area WHERE slug='gresik'),34500,'2026-05-17'),
((SELECT id FROM bahan_pokok WHERE slug='cabai-merah'),(SELECT id FROM master_area WHERE slug='jombang'),33000,'2026-05-17'),
((SELECT id FROM bahan_pokok WHERE slug='cabai-merah'),(SELECT id FROM master_area WHERE slug='kediri'),32500,'2026-05-17'),
((SELECT id FROM bahan_pokok WHERE slug='cabai-merah'),(SELECT id FROM master_area WHERE slug='madiun'),34000,'2026-05-17'),
((SELECT id FROM bahan_pokok WHERE slug='cabai-merah'),(SELECT id FROM master_area WHERE slug='jember'),34500,'2026-05-17'),
((SELECT id FROM bahan_pokok WHERE slug='cabai-merah'),(SELECT id FROM master_area WHERE slug='lamongan'),33000,'2026-05-17'),
((SELECT id FROM bahan_pokok WHERE slug='cabai-merah'),(SELECT id FROM master_area WHERE slug='banyuwangi'),34000,'2026-05-17'),
((SELECT id FROM bahan_pokok WHERE slug='cabai-merah'),(SELECT id FROM master_area WHERE slug='surabaya'),40000,'2026-05-24'),
((SELECT id FROM bahan_pokok WHERE slug='cabai-merah'),(SELECT id FROM master_area WHERE slug='malang'),39000,'2026-05-24'),
((SELECT id FROM bahan_pokok WHERE slug='cabai-merah'),(SELECT id FROM master_area WHERE slug='sidoarjo'),41000,'2026-05-24'),
((SELECT id FROM bahan_pokok WHERE slug='cabai-merah'),(SELECT id FROM master_area WHERE slug='gresik'),39500,'2026-05-24'),
((SELECT id FROM bahan_pokok WHERE slug='cabai-merah'),(SELECT id FROM master_area WHERE slug='jombang'),38000,'2026-05-24'),
((SELECT id FROM bahan_pokok WHERE slug='cabai-merah'),(SELECT id FROM master_area WHERE slug='kediri'),37500,'2026-05-24'),
((SELECT id FROM bahan_pokok WHERE slug='cabai-merah'),(SELECT id FROM master_area WHERE slug='madiun'),39000,'2026-05-24'),
((SELECT id FROM bahan_pokok WHERE slug='cabai-merah'),(SELECT id FROM master_area WHERE slug='jember'),39500,'2026-05-24'),
((SELECT id FROM bahan_pokok WHERE slug='cabai-merah'),(SELECT id FROM master_area WHERE slug='lamongan'),38000,'2026-05-24'),
((SELECT id FROM bahan_pokok WHERE slug='cabai-merah'),(SELECT id FROM master_area WHERE slug='banyuwangi'),39000,'2026-05-24'),
((SELECT id FROM bahan_pokok WHERE slug='cabai-merah'),(SELECT id FROM master_area WHERE slug='surabaya'),38000,'2026-05-31'),
((SELECT id FROM bahan_pokok WHERE slug='cabai-merah'),(SELECT id FROM master_area WHERE slug='malang'),37000,'2026-05-31'),
((SELECT id FROM bahan_pokok WHERE slug='cabai-merah'),(SELECT id FROM master_area WHERE slug='sidoarjo'),39000,'2026-05-31'),
((SELECT id FROM bahan_pokok WHERE slug='cabai-merah'),(SELECT id FROM master_area WHERE slug='gresik'),37500,'2026-05-31'),
((SELECT id FROM bahan_pokok WHERE slug='cabai-merah'),(SELECT id FROM master_area WHERE slug='jombang'),36000,'2026-05-31'),
((SELECT id FROM bahan_pokok WHERE slug='cabai-merah'),(SELECT id FROM master_area WHERE slug='kediri'),35500,'2026-05-31'),
((SELECT id FROM bahan_pokok WHERE slug='cabai-merah'),(SELECT id FROM master_area WHERE slug='madiun'),37000,'2026-05-31'),
((SELECT id FROM bahan_pokok WHERE slug='cabai-merah'),(SELECT id FROM master_area WHERE slug='jember'),37500,'2026-05-31'),
((SELECT id FROM bahan_pokok WHERE slug='cabai-merah'),(SELECT id FROM master_area WHERE slug='lamongan'),36000,'2026-05-31'),
((SELECT id FROM bahan_pokok WHERE slug='cabai-merah'),(SELECT id FROM master_area WHERE slug='banyuwangi'),37000,'2026-05-31'),
((SELECT id FROM bahan_pokok WHERE slug='cabai-merah'),(SELECT id FROM master_area WHERE slug='surabaya'),35000,'2026-06-03'),
((SELECT id FROM bahan_pokok WHERE slug='cabai-merah'),(SELECT id FROM master_area WHERE slug='malang'),34000,'2026-06-03'),
((SELECT id FROM bahan_pokok WHERE slug='cabai-merah'),(SELECT id FROM master_area WHERE slug='sidoarjo'),36000,'2026-06-03'),
((SELECT id FROM bahan_pokok WHERE slug='cabai-merah'),(SELECT id FROM master_area WHERE slug='gresik'),34500,'2026-06-03'),
((SELECT id FROM bahan_pokok WHERE slug='cabai-merah'),(SELECT id FROM master_area WHERE slug='jombang'),33000,'2026-06-03'),
((SELECT id FROM bahan_pokok WHERE slug='cabai-merah'),(SELECT id FROM master_area WHERE slug='kediri'),32500,'2026-06-03'),
((SELECT id FROM bahan_pokok WHERE slug='cabai-merah'),(SELECT id FROM master_area WHERE slug='madiun'),34000,'2026-06-03'),
((SELECT id FROM bahan_pokok WHERE slug='cabai-merah'),(SELECT id FROM master_area WHERE slug='jember'),34500,'2026-06-03'),
((SELECT id FROM bahan_pokok WHERE slug='cabai-merah'),(SELECT id FROM master_area WHERE slug='lamongan'),33000,'2026-06-03'),
((SELECT id FROM bahan_pokok WHERE slug='cabai-merah'),(SELECT id FROM master_area WHERE slug='banyuwangi'),34000,'2026-06-03'),
((SELECT id FROM bahan_pokok WHERE slug='cabai-merah'),(SELECT id FROM master_area WHERE slug='surabaya'),33000,'2026-06-06'),
((SELECT id FROM bahan_pokok WHERE slug='cabai-merah'),(SELECT id FROM master_area WHERE slug='malang'),32000,'2026-06-06'),
((SELECT id FROM bahan_pokok WHERE slug='cabai-merah'),(SELECT id FROM master_area WHERE slug='sidoarjo'),34000,'2026-06-06'),
((SELECT id FROM bahan_pokok WHERE slug='cabai-merah'),(SELECT id FROM master_area WHERE slug='gresik'),32500,'2026-06-06'),
((SELECT id FROM bahan_pokok WHERE slug='cabai-merah'),(SELECT id FROM master_area WHERE slug='jombang'),31000,'2026-06-06'),
((SELECT id FROM bahan_pokok WHERE slug='cabai-merah'),(SELECT id FROM master_area WHERE slug='kediri'),30500,'2026-06-06'),
((SELECT id FROM bahan_pokok WHERE slug='cabai-merah'),(SELECT id FROM master_area WHERE slug='madiun'),32000,'2026-06-06'),
((SELECT id FROM bahan_pokok WHERE slug='cabai-merah'),(SELECT id FROM master_area WHERE slug='jember'),32500,'2026-06-06'),
((SELECT id FROM bahan_pokok WHERE slug='cabai-merah'),(SELECT id FROM master_area WHERE slug='lamongan'),31000,'2026-06-06'),
((SELECT id FROM bahan_pokok WHERE slug='cabai-merah'),(SELECT id FROM master_area WHERE slug='banyuwangi'),32000,'2026-06-06'),
((SELECT id FROM bahan_pokok WHERE slug='cabai-merah'),(SELECT id FROM master_area WHERE slug='surabaya'),32000,'2026-06-07'),
((SELECT id FROM bahan_pokok WHERE slug='cabai-merah'),(SELECT id FROM master_area WHERE slug='malang'),31000,'2026-06-07'),
((SELECT id FROM bahan_pokok WHERE slug='cabai-merah'),(SELECT id FROM master_area WHERE slug='sidoarjo'),33000,'2026-06-07'),
((SELECT id FROM bahan_pokok WHERE slug='cabai-merah'),(SELECT id FROM master_area WHERE slug='gresik'),31500,'2026-06-07'),
((SELECT id FROM bahan_pokok WHERE slug='cabai-merah'),(SELECT id FROM master_area WHERE slug='jombang'),30000,'2026-06-07'),
((SELECT id FROM bahan_pokok WHERE slug='cabai-merah'),(SELECT id FROM master_area WHERE slug='kediri'),29500,'2026-06-07'),
((SELECT id FROM bahan_pokok WHERE slug='cabai-merah'),(SELECT id FROM master_area WHERE slug='madiun'),31000,'2026-06-07'),
((SELECT id FROM bahan_pokok WHERE slug='cabai-merah'),(SELECT id FROM master_area WHERE slug='jember'),31500,'2026-06-07'),
((SELECT id FROM bahan_pokok WHERE slug='cabai-merah'),(SELECT id FROM master_area WHERE slug='lamongan'),30000,'2026-06-07'),
((SELECT id FROM bahan_pokok WHERE slug='cabai-merah'),(SELECT id FROM master_area WHERE slug='banyuwangi'),31000,'2026-06-07'),

-- TEPUNG TERIGU
((SELECT id FROM bahan_pokok WHERE slug='tepung-terigu'),(SELECT id FROM master_area WHERE slug='surabaya'),11000,'2026-05-10'),
((SELECT id FROM bahan_pokok WHERE slug='tepung-terigu'),(SELECT id FROM master_area WHERE slug='malang'),10800,'2026-05-10'),
((SELECT id FROM bahan_pokok WHERE slug='tepung-terigu'),(SELECT id FROM master_area WHERE slug='sidoarjo'),11200,'2026-05-10'),
((SELECT id FROM bahan_pokok WHERE slug='tepung-terigu'),(SELECT id FROM master_area WHERE slug='gresik'),11000,'2026-05-10'),
((SELECT id FROM bahan_pokok WHERE slug='tepung-terigu'),(SELECT id FROM master_area WHERE slug='jombang'),10500,'2026-05-10'),
((SELECT id FROM bahan_pokok WHERE slug='tepung-terigu'),(SELECT id FROM master_area WHERE slug='kediri'),10500,'2026-05-10'),
((SELECT id FROM bahan_pokok WHERE slug='tepung-terigu'),(SELECT id FROM master_area WHERE slug='madiun'),10800,'2026-05-10'),
((SELECT id FROM bahan_pokok WHERE slug='tepung-terigu'),(SELECT id FROM master_area WHERE slug='jember'),11000,'2026-05-10'),
((SELECT id FROM bahan_pokok WHERE slug='tepung-terigu'),(SELECT id FROM master_area WHERE slug='lamongan'),10500,'2026-05-10'),
((SELECT id FROM bahan_pokok WHERE slug='tepung-terigu'),(SELECT id FROM master_area WHERE slug='banyuwangi'),10800,'2026-05-10'),
((SELECT id FROM bahan_pokok WHERE slug='tepung-terigu'),(SELECT id FROM master_area WHERE slug='surabaya'),11200,'2026-05-17'),
((SELECT id FROM bahan_pokok WHERE slug='tepung-terigu'),(SELECT id FROM master_area WHERE slug='malang'),11000,'2026-05-17'),
((SELECT id FROM bahan_pokok WHERE slug='tepung-terigu'),(SELECT id FROM master_area WHERE slug='sidoarjo'),11400,'2026-05-17'),
((SELECT id FROM bahan_pokok WHERE slug='tepung-terigu'),(SELECT id FROM master_area WHERE slug='gresik'),11200,'2026-05-17'),
((SELECT id FROM bahan_pokok WHERE slug='tepung-terigu'),(SELECT id FROM master_area WHERE slug='jombang'),10800,'2026-05-17'),
((SELECT id FROM bahan_pokok WHERE slug='tepung-terigu'),(SELECT id FROM master_area WHERE slug='kediri'),10800,'2026-05-17'),
((SELECT id FROM bahan_pokok WHERE slug='tepung-terigu'),(SELECT id FROM master_area WHERE slug='madiun'),11000,'2026-05-17'),
((SELECT id FROM bahan_pokok WHERE slug='tepung-terigu'),(SELECT id FROM master_area WHERE slug='jember'),11200,'2026-05-17'),
((SELECT id FROM bahan_pokok WHERE slug='tepung-terigu'),(SELECT id FROM master_area WHERE slug='lamongan'),10800,'2026-05-17'),
((SELECT id FROM bahan_pokok WHERE slug='tepung-terigu'),(SELECT id FROM master_area WHERE slug='banyuwangi'),11000,'2026-05-17'),
((SELECT id FROM bahan_pokok WHERE slug='tepung-terigu'),(SELECT id FROM master_area WHERE slug='surabaya'),11500,'2026-05-24'),
((SELECT id FROM bahan_pokok WHERE slug='tepung-terigu'),(SELECT id FROM master_area WHERE slug='malang'),11300,'2026-05-24'),
((SELECT id FROM bahan_pokok WHERE slug='tepung-terigu'),(SELECT id FROM master_area WHERE slug='sidoarjo'),11700,'2026-05-24'),
((SELECT id FROM bahan_pokok WHERE slug='tepung-terigu'),(SELECT id FROM master_area WHERE slug='gresik'),11500,'2026-05-24'),
((SELECT id FROM bahan_pokok WHERE slug='tepung-terigu'),(SELECT id FROM master_area WHERE slug='jombang'),11000,'2026-05-24'),
((SELECT id FROM bahan_pokok WHERE slug='tepung-terigu'),(SELECT id FROM master_area WHERE slug='kediri'),11000,'2026-05-24'),
((SELECT id FROM bahan_pokok WHERE slug='tepung-terigu'),(SELECT id FROM master_area WHERE slug='madiun'),11300,'2026-05-24'),
((SELECT id FROM bahan_pokok WHERE slug='tepung-terigu'),(SELECT id FROM master_area WHERE slug='jember'),11500,'2026-05-24'),
((SELECT id FROM bahan_pokok WHERE slug='tepung-terigu'),(SELECT id FROM master_area WHERE slug='lamongan'),11000,'2026-05-24'),
((SELECT id FROM bahan_pokok WHERE slug='tepung-terigu'),(SELECT id FROM master_area WHERE slug='banyuwangi'),11300,'2026-05-24'),
((SELECT id FROM bahan_pokok WHERE slug='tepung-terigu'),(SELECT id FROM master_area WHERE slug='surabaya'),11800,'2026-05-31'),
((SELECT id FROM bahan_pokok WHERE slug='tepung-terigu'),(SELECT id FROM master_area WHERE slug='malang'),11500,'2026-05-31'),
((SELECT id FROM bahan_pokok WHERE slug='tepung-terigu'),(SELECT id FROM master_area WHERE slug='sidoarjo'),12000,'2026-05-31'),
((SELECT id FROM bahan_pokok WHERE slug='tepung-terigu'),(SELECT id FROM master_area WHERE slug='gresik'),11800,'2026-05-31'),
((SELECT id FROM bahan_pokok WHERE slug='tepung-terigu'),(SELECT id FROM master_area WHERE slug='jombang'),11300,'2026-05-31'),
((SELECT id FROM bahan_pokok WHERE slug='tepung-terigu'),(SELECT id FROM master_area WHERE slug='kediri'),11300,'2026-05-31'),
((SELECT id FROM bahan_pokok WHERE slug='tepung-terigu'),(SELECT id FROM master_area WHERE slug='madiun'),11500,'2026-05-31'),
((SELECT id FROM bahan_pokok WHERE slug='tepung-terigu'),(SELECT id FROM master_area WHERE slug='jember'),11800,'2026-05-31'),
((SELECT id FROM bahan_pokok WHERE slug='tepung-terigu'),(SELECT id FROM master_area WHERE slug='lamongan'),11300,'2026-05-31'),
((SELECT id FROM bahan_pokok WHERE slug='tepung-terigu'),(SELECT id FROM master_area WHERE slug='banyuwangi'),11500,'2026-05-31'),
((SELECT id FROM bahan_pokok WHERE slug='tepung-terigu'),(SELECT id FROM master_area WHERE slug='surabaya'),12000,'2026-06-03'),
((SELECT id FROM bahan_pokok WHERE slug='tepung-terigu'),(SELECT id FROM master_area WHERE slug='malang'),11800,'2026-06-03'),
((SELECT id FROM bahan_pokok WHERE slug='tepung-terigu'),(SELECT id FROM master_area WHERE slug='sidoarjo'),12200,'2026-06-03'),
((SELECT id FROM bahan_pokok WHERE slug='tepung-terigu'),(SELECT id FROM master_area WHERE slug='gresik'),12000,'2026-06-03'),
((SELECT id FROM bahan_pokok WHERE slug='tepung-terigu'),(SELECT id FROM master_area WHERE slug='jombang'),11500,'2026-06-03'),
((SELECT id FROM bahan_pokok WHERE slug='tepung-terigu'),(SELECT id FROM master_area WHERE slug='kediri'),11500,'2026-06-03'),
((SELECT id FROM bahan_pokok WHERE slug='tepung-terigu'),(SELECT id FROM master_area WHERE slug='madiun'),11800,'2026-06-03'),
((SELECT id FROM bahan_pokok WHERE slug='tepung-terigu'),(SELECT id FROM master_area WHERE slug='jember'),12000,'2026-06-03'),
((SELECT id FROM bahan_pokok WHERE slug='tepung-terigu'),(SELECT id FROM master_area WHERE slug='lamongan'),11500,'2026-06-03'),
((SELECT id FROM bahan_pokok WHERE slug='tepung-terigu'),(SELECT id FROM master_area WHERE slug='banyuwangi'),11800,'2026-06-03'),
((SELECT id FROM bahan_pokok WHERE slug='tepung-terigu'),(SELECT id FROM master_area WHERE slug='surabaya'),12000,'2026-06-06'),
((SELECT id FROM bahan_pokok WHERE slug='tepung-terigu'),(SELECT id FROM master_area WHERE slug='malang'),11800,'2026-06-06'),
((SELECT id FROM bahan_pokok WHERE slug='tepung-terigu'),(SELECT id FROM master_area WHERE slug='sidoarjo'),12200,'2026-06-06'),
((SELECT id FROM bahan_pokok WHERE slug='tepung-terigu'),(SELECT id FROM master_area WHERE slug='gresik'),12000,'2026-06-06'),
((SELECT id FROM bahan_pokok WHERE slug='tepung-terigu'),(SELECT id FROM master_area WHERE slug='lamongan'),11500,'2026-06-06'),
((SELECT id FROM bahan_pokok WHERE slug='tepung-terigu'),(SELECT id FROM master_area WHERE slug='jombang'),11500,'2026-06-06'),
((SELECT id FROM bahan_pokok WHERE slug='tepung-terigu'),(SELECT id FROM master_area WHERE slug='kediri'),11500,'2026-06-06'),
((SELECT id FROM bahan_pokok WHERE slug='tepung-terigu'),(SELECT id FROM master_area WHERE slug='madiun'),11800,'2026-06-06'),
((SELECT id FROM bahan_pokok WHERE slug='tepung-terigu'),(SELECT id FROM master_area WHERE slug='jember'),12000,'2026-06-06'),
((SELECT id FROM bahan_pokok WHERE slug='tepung-terigu'),(SELECT id FROM master_area WHERE slug='banyuwangi'),11800,'2026-06-06'),
((SELECT id FROM bahan_pokok WHERE slug='tepung-terigu'),(SELECT id FROM master_area WHERE slug='surabaya'),12200,'2026-06-07'),
((SELECT id FROM bahan_pokok WHERE slug='tepung-terigu'),(SELECT id FROM master_area WHERE slug='malang'),12000,'2026-06-07'),
((SELECT id FROM bahan_pokok WHERE slug='tepung-terigu'),(SELECT id FROM master_area WHERE slug='sidoarjo'),12400,'2026-06-07'),
((SELECT id FROM bahan_pokok WHERE slug='tepung-terigu'),(SELECT id FROM master_area WHERE slug='gresik'),12200,'2026-06-07'),
((SELECT id FROM bahan_pokok WHERE slug='tepung-terigu'),(SELECT id FROM master_area WHERE slug='jombang'),11700,'2026-06-07'),
((SELECT id FROM bahan_pokok WHERE slug='tepung-terigu'),(SELECT id FROM master_area WHERE slug='kediri'),11700,'2026-06-07'),
((SELECT id FROM bahan_pokok WHERE slug='tepung-terigu'),(SELECT id FROM master_area WHERE slug='madiun'),12000,'2026-06-07'),
((SELECT id FROM bahan_pokok WHERE slug='tepung-terigu'),(SELECT id FROM master_area WHERE slug='jember'),12200,'2026-06-07'),
((SELECT id FROM bahan_pokok WHERE slug='tepung-terigu'),(SELECT id FROM master_area WHERE slug='lamongan'),11700,'2026-06-07'),
((SELECT id FROM bahan_pokok WHERE slug='tepung-terigu'),(SELECT id FROM master_area WHERE slug='banyuwangi'),12000,'2026-06-07')

ON CONFLICT (bahan_pokok_id, area_id, tanggal) DO UPDATE SET harga = EXCLUDED.harga;